// Generated by tools/scripts/agent_capability_manifest.py --write.
// Every typed binding is mechanically referenced below.

#include <pulp/audio/instrument_voice_allocator.hpp>
#include <pulp/midi/mpe_voice_tracker.hpp>
#include <pulp/sequence/host_transport_projector.hpp>
#include <pulp/signal/saturator.hpp>
#include <pulp/timebase/quantize.hpp>
#include <pulp/timebase/tick.hpp>

int main() {
    {
        // audio.instrument-voice-allocator
        static_assert(sizeof(pulp::audio::InstrumentVoiceAllocator) > 0);
        pulp::audio::InstrumentVoiceAllocator probe_value{}; (void)probe_value.prepare(1);
    }
    {
        // midi.mpe-voice-tracker
        static_assert(sizeof(pulp::midi::MpeVoiceTracker) > 0);
        pulp::midi::MpeVoiceTracker probe_value{}; (void)probe_value.reset();
    }
    {
        // sequence.host-transport-projector
        static_assert(sizeof(pulp::sequence::HostTransportProjector) > 0);
        pulp::sequence::HostTransportProjector probe_value{}; (void)probe_value.reset();
    }
    {
        // signal.saturator
        static_assert(sizeof(pulp::signal::SaturatorT<float>) > 0);
        pulp::signal::SaturatorT<float> probe_value{}; (void)probe_value.prepare(48000.0);
    }
    {
        // timebase.swing
        static_assert(sizeof(pulp::timebase::SwingRatio) > 0);
        auto *volatile binding_5 = &pulp::timebase::swing_position;
        (void)binding_5;
        auto *volatile binding_6 = &pulp::timebase::unswing_position;
        (void)binding_6;
        (void)pulp::timebase::swing_position(pulp::timebase::TickPosition{1}, pulp::timebase::TickDuration{2}, pulp::timebase::kStraightSwing);
    }
    {
        // timebase.tick
        static_assert(sizeof(pulp::timebase::TickPosition) > 0);
        pulp::timebase::TickPosition probe_value{1}; (void)probe_value;
    }
    return 0;
}
