// Tests for the kit's snare and rimshot/clave voices. These are struck
// resonators plus (for the snare) a filtered-noise snappy, so what matters is
// what they actually emit: the snare must carry BOTH a tonal shell and a
// broadband noise crack, its balance knob must move real energy between the
// two, and the rim/clave must be a short bright tick whose ring pitch is a real,
// controllable resonance. Every claim here is a rendered-and-measured number.
//
// Reference targets are measured constants from the reference drum machine's
// pads (offline renders); no reference audio is stored, and every sample is
// generated by the circuit model. The voices are calibrated to those numbers.

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "harness/rt_allocation_probe.hpp"
#include "support/modal_analysis.hpp"

#include <pulp/audio/analysis/audio_spectrum.hpp>
#include <pulp/audio/buffer.hpp>

#include <rim_clave_voice.hpp>
#include <snare_voice.hpp>

#include <algorithm>
#include <cmath>
#include <span>
#include <vector>

namespace {

using pulp::examples::RimClaveVoice;
using pulp::examples::SnareVoice;
using namespace pulp::test::audio;

constexpr double kFs = 48000.0;

/// The same five numbers the reference pads were measured with: peak, the
/// −60 dB decay, the zero-cross rate over the active region, and the onset
/// spectral centroid and flatness. Centroid/flatness are read from a
/// Hann-windowed magnitude spectrum over a 32768-sample window at the onset,
/// matching how the reference targets were taken.
struct SpectralMetrics {
    double peak = 0.0;
    double t60_s = 0.0;
    double zcr_hz = 0.0;
    double centroid_hz = 0.0;
    double flatness = 0.0;  ///< 0 = pure tone, → 1 = white noise.
};

SpectralMetrics measure(std::span<const float> x, double fs) {
    SpectralMetrics m;
    const std::size_t n = x.size();
    std::size_t peak_i = 0;
    for (std::size_t i = 0; i < n; ++i) {
        const float a = std::fabs(x[i]);
        if (a > m.peak) {
            m.peak = a;
            peak_i = i;
        }
    }
    const float thr = static_cast<float>(m.peak / 1000.0);
    std::size_t last = peak_i;
    for (std::size_t i = 0; i < n; ++i)
        if (std::fabs(x[i]) > thr) last = i;
    m.t60_s = static_cast<double>(last) / fs;

    if (last > peak_i + 1) {
        std::size_t zc = 0;
        for (std::size_t i = peak_i + 1; i <= last; ++i)
            if ((x[i - 1] >= 0.0f) != (x[i] >= 0.0f)) ++zc;
        m.zcr_hz = static_cast<double>(zc) / (static_cast<double>(last - peak_i) / fs) * 0.5;
    }

    const int fft_length = 32768;
    const std::size_t avail = (n > peak_i) ? (n - peak_i) : 0;
    const std::size_t seg = std::min<std::size_t>(fft_length, avail);
    if (seg >= 4096) {
        std::vector<float> buf(x.begin() + static_cast<std::ptrdiff_t>(peak_i),
                               x.begin() + static_cast<std::ptrdiff_t>(peak_i + seg));
        buf.resize(fft_length, 0.0f);
        float* ch0 = buf.data();
        pulp::audio::BufferView<const float> bv(&ch0, 1, fft_length);
        ResponseOptions ro;
        ro.fft_length = fft_length;
        ro.window = Window::hann;
        const double checks[1] = {1000.0};
        const auto curve = magnitude_spectrum_curve(bv, fs, std::span<const double>(checks, 1), ro);
        double num = 0.0, den = 0.0, log_sum = 0.0, lin_sum = 0.0;
        int cnt = 0;
        for (const auto& p : curve.full) {
            if (p.hz < 20.0 || p.hz > 20000.0) continue;
            const double lin = std::pow(10.0, p.magnitude_db / 20.0);
            num += p.hz * lin;
            den += lin;
            log_sum += std::log(lin + 1e-12);
            lin_sum += lin;
            ++cnt;
        }
        if (den > 0.0) m.centroid_hz = num / den;
        if (cnt > 0 && lin_sum > 0.0) m.flatness = std::exp(log_sum / cnt) / (lin_sum / cnt);
    }
    return m;
}

/// Render one snare hit. Balance/velocity as given; the hit lands 10 ms in so
/// the onset window is clean and the tail rings out inside the buffer.
std::vector<float> render_snare(double balance, double velocity = 1.0, double duration_s = 1.0) {
    SnareVoice voice;
    voice.prepare(kFs);
    voice.set_balance(balance);
    std::vector<float> y(static_cast<std::size_t>(duration_s * kFs), 0.0f);
    const int hit = static_cast<int>(0.01 * kFs);
    for (int n = 0; n < static_cast<int>(y.size()); ++n) {
        if (n == hit) voice.trigger(velocity);
        y[static_cast<std::size_t>(n)] = voice.process();
    }
    return y;
}

std::vector<float> render_rim(double tune, double decay, double velocity = 1.0,
                              double duration_s = 0.3) {
    RimClaveVoice voice;
    voice.prepare(kFs);
    voice.set_tune(tune);
    voice.set_decay(decay);
    std::vector<float> y(static_cast<std::size_t>(duration_s * kFs), 0.0f);
    const int hit = static_cast<int>(0.01 * kFs);
    for (int n = 0; n < static_cast<int>(y.size()); ++n) {
        if (n == hit) voice.trigger(velocity);
        y[static_cast<std::size_t>(n)] = voice.process();
    }
    return y;
}

}  // namespace

// ---------------------------------------------------------------------------
// The snare's defining property: a tonal shell AND a broadband snappy, present
// together. A voice that were only a ring, or only noise, would fail one half.
// ---------------------------------------------------------------------------

TEST_CASE("the snare carries both a tonal shell and a broadband snappy", "[kit][snare]") {
    // Balance 0 is the bare shell: a struck-resonator ring with a real,
    // measurable pitch and a near-zero spectral flatness (it is a tone).
    const auto tone = render_snare(0.0);
    const auto shell = measure_mode(tone, kFs, SnareVoice::kBody1Hz);
    INFO("shell mode " << summarize(shell));
    REQUIRE(shell.freq_hz == Catch::Approx(SnareVoice::kBody1Hz).epsilon(0.06));
    REQUIRE(shell.confidence > 0.5);
    const auto tone_m = measure(tone, kFs);
    REQUIRE(tone_m.flatness < 0.05);  // a tone, not noise

    // Balance 1 is the bare snappy: broadband noise, high flatness, bright.
    const auto snap = render_snare(1.0);
    const auto snap_m = measure(snap, kFs);
    INFO("snappy centroid " << snap_m.centroid_hz << " flatness " << snap_m.flatness);
    REQUIRE(snap_m.flatness > 0.5);        // broadband, not a tone
    REQUIRE(snap_m.centroid_hz > 5000.0);  // bright crack
}

TEST_CASE("the tone/snap balance moves energy between shell and snappy", "[kit][snare]") {
    // The balance knob is the snare's most characterful control; turning it up
    // must trade the low tonal shell for the bright noise, so both the onset
    // centroid and the spectral flatness rise monotonically with it.
    double last_centroid = 0.0;
    double last_flatness = 0.0;
    for (double balance : {0.2, 0.4, 0.6, 0.8}) {
        const auto m = measure(render_snare(balance), kFs);
        INFO("balance " << balance << " centroid " << m.centroid_hz << " flatness " << m.flatness);
        REQUIRE(m.centroid_hz > last_centroid);
        REQUIRE(m.flatness > last_flatness);
        last_centroid = m.centroid_hz;
        last_flatness = m.flatness;
    }
}

TEST_CASE("the snare lands on the reference pad", "[kit][snare][calibration]") {
    // Default balance, full velocity. The reference snare pad (measured offline)
    // is a ~0.44 peak, ~0.24 s, onset centroid ~6.7 kHz, flatness ~0.61 crack.
    // These are a delivered match, not merely the right shape; if the body
    // feedback, the snappy filter or the default balance regresses, the sound
    // walks off the reference and this fails.
    const auto m = measure(render_snare(SnareVoice::kDefaultBalance), kFs);
    INFO("snare peak " << m.peak << " T60 " << m.t60_s << " centroid " << m.centroid_hz
                       << " flatness " << m.flatness);
    REQUIRE(m.peak == Catch::Approx(0.436).epsilon(0.20));
    REQUIRE(m.t60_s == Catch::Approx(0.239).epsilon(0.20));
    REQUIRE(m.centroid_hz == Catch::Approx(6690.0).epsilon(0.20));
    REQUIRE(m.flatness == Catch::Approx(0.609).epsilon(0.15));
}

TEST_CASE("snare velocity is loudness, not timbre", "[kit][snare]") {
    // Velocity scales the strike and the snappy together, so a half-velocity hit
    // is exactly half the level -- as on the reference pad, where velocity is a
    // linear gain and does not change the spectrum.
    const auto full = measure(render_snare(SnareVoice::kDefaultBalance, 1.0), kFs);
    const auto half = measure(render_snare(SnareVoice::kDefaultBalance, 0.5), kFs);
    REQUIRE(full.peak / half.peak == Catch::Approx(2.0).epsilon(0.02));
}

TEST_CASE("snare shell rings superpose rather than machine-gunning", "[kit][snare][retrigger]") {
    // The bodies are struck additively into a resonator that is never reset on a
    // hit, so a strike that lands in a live ring must differ from one into
    // silence. A voice that cleared state on note-on would render the two alike
    // -- the machine-gun failure. Measured on the bare shell (balance 0) so the
    // comparison is the deterministic ring, not the decorrelated noise.
    constexpr double gap = 0.050;
    SnareVoice ringing, fresh;
    for (auto* v : {&ringing, &fresh}) {
        v->prepare(kFs);
        v->set_balance(0.0);
    }
    const int first = static_cast<int>(0.01 * kFs);
    const int second = static_cast<int>((0.01 + gap) * kFs);
    const int total = static_cast<int>((0.01 + gap + 0.4) * kFs);
    double diff = 0.0, energy = 0.0;
    for (int n = 0; n < total; ++n) {
        if (n == first) ringing.trigger(1.0);
        if (n == second) {
            ringing.trigger(1.0);
            fresh.trigger(1.0);
        }
        const float a = ringing.process();
        const float b = fresh.process();
        if (n >= second) {
            diff += static_cast<double>(a - b) * (a - b);
            energy += static_cast<double>(b) * b;
        }
    }
    // The second strike lands in the first's live ring, so the two diverge.
    REQUIRE(std::sqrt(diff / energy) > 0.1);
}

// ---------------------------------------------------------------------------
// Rimshot / clave: one short bridged-T ring, noise-excited. A short bright tick
// whose pitch is a real, controllable resonance.
// ---------------------------------------------------------------------------

TEST_CASE("the rimshot/clave is a short bright tick", "[kit][rim-clave][calibration]") {
    // The reference rim/clave pad is a ~35 ms tick: a low tonal ring under a
    // bright, noisy onset (centroid ~3.1 kHz, well above the ~850 Hz ring, and
    // a spectral flatness ~0.3 that a clean resonator ring could never reach).
    const auto m = measure(render_rim(1.0, 0.5), kFs);
    INFO("rim peak " << m.peak << " T60 " << m.t60_s << " centroid " << m.centroid_hz
                     << " flatness " << m.flatness);
    REQUIRE(m.peak == Catch::Approx(0.295).epsilon(0.25));
    REQUIRE(m.t60_s < 0.060);  // short by construction
    REQUIRE(m.t60_s == Catch::Approx(0.035).epsilon(0.35));
    // Bright: the onset centroid sits far above the ring fundamental, which only
    // the noisy excitation can produce.
    REQUIRE(m.centroid_hz > 2000.0);
    REQUIRE(m.centroid_hz == Catch::Approx(3083.0).epsilon(0.30));
    // Noisy: clearly not a clean sinusoid, clearly not white.
    REQUIRE(m.flatness > 0.15);
    REQUIRE(m.flatness == Catch::Approx(0.312).epsilon(0.25));
}

TEST_CASE("the rim/clave ring is a real resonance that tracks the tune", "[kit][rim-clave]") {
    // The tick's pitch is the resonator's centre frequency, not a scripted
    // number: tuning the ring must move the measured pitch in proportion. Read
    // at the longest decay, where the ring rings out cleanly enough to fit a
    // confident mode. This is what separates a modelled resonance from a noise
    // burst gated to a fixed length.
    double last_freq = 0.0;
    for (double tune : {1.0, 1.5, 2.0}) {
        const auto y = render_rim(tune, 1.0);
        const auto mode = measure_mode(y, kFs, RimClaveVoice::kRingHz * tune);
        INFO("tune " << tune << " -> " << summarize(mode));
        REQUIRE(mode.freq_hz == Catch::Approx(RimClaveVoice::kRingHz * tune).epsilon(0.06));
        REQUIRE(mode.freq_hz > last_freq);
        last_freq = mode.freq_hz;
    }
}

TEST_CASE("the rim/clave decay knob lengthens the tail", "[kit][rim-clave]") {
    const auto shortest = measure(render_rim(1.0, 0.0), kFs);
    const auto longest = measure(render_rim(1.0, 1.0), kFs);
    INFO("T60 short " << shortest.t60_s << " long " << longest.t60_s);
    REQUIRE(longest.t60_s > shortest.t60_s * 1.3);
}

TEST_CASE("rim/clave velocity is loudness, not timbre", "[kit][rim-clave]") {
    const auto full = measure(render_rim(1.0, 0.5, 1.0), kFs);
    const auto half = measure(render_rim(1.0, 0.5, 0.5), kFs);
    REQUIRE(full.peak / half.peak == Catch::Approx(2.0).epsilon(0.02));
}

// ---------------------------------------------------------------------------
// Realtime contract. Every per-sample and per-parameter call runs on the audio
// thread in a plugin, so none of them may allocate.
// ---------------------------------------------------------------------------

TEST_CASE("the snare voice allocates nothing on the audio thread", "[kit][snare][rt-safety]") {
    SnareVoice voice;
    voice.prepare(kFs);
    pulp::test::RtAllocationProbe probe;
    for (int block = 0; block < 200; ++block) {
        voice.set_balance(0.004 * (block % 100));
        voice.set_decay(0.01 * (block % 100));
        voice.set_tune(0.9 + 0.002 * (block % 100));
        if (block % 8 == 0) voice.trigger(0.5 + 0.005 * (block % 80));
        for (int n = 0; n < 64; ++n) voice.process();
        voice.snap_denormals();
    }
    REQUIRE(probe.allocation_count() == 0);
}

TEST_CASE("the rim/clave voice allocates nothing on the audio thread",
          "[kit][rim-clave][rt-safety]") {
    RimClaveVoice voice;
    voice.prepare(kFs);
    pulp::test::RtAllocationProbe probe;
    for (int block = 0; block < 200; ++block) {
        voice.set_decay(0.01 * (block % 100));
        voice.set_tune(0.8 + 0.004 * (block % 100));
        if (block % 8 == 0) voice.trigger(0.6);
        for (int n = 0; n < 64; ++n) voice.process();
        voice.snap_denormals();
    }
    REQUIRE(probe.allocation_count() == 0);
}
