#include "test_design_import_shared.hpp"

#include <pulp/runtime/crypto.hpp>

TEST_CASE("generate_pulp_cpp checkpoint artifact stays byte-exact",
          "[view][import][cpp-codegen][golden]") {
    DesignIR ir;
    ir.source = DesignSource::jsx;
    ir.root.type = "frame";
    ir.root.name = "Checkpoint Panel";
    ir.root.stable_anchor_id = "checkpoint-panel";
    ir.root.layout.direction = LayoutDirection::row;
    ir.root.layout.gap = 12.0f;
    ir.root.style.width = 240.0f;
    ir.root.style.height = 96.0f;
    ir.root.style.background_color = "#102030";
    ir.root.style.border_radius = 8.0f;

    ir.tokens.colors.emplace("Panel Background", "#102030");
    ir.tokens.dimensions.emplace("Control Gap", 12.0f);
    ir.tokens.strings.emplace("Panel Title", "Checkpoint");

    IRAssetRef asset;
    asset.asset_id = "brand-mark";
    asset.original_uri = "resource://brand-mark.svg";
    asset.local_path = "/opt/pulp/assets/brand-mark.svg";
    asset.content_hash = "sha256:checkpoint";
    asset.mime = "image/svg+xml";
    asset.width = 32;
    asset.height = 32;
    ir.asset_manifest.assets.push_back(asset);

    IRNode image;
    image.type = "image";
    image.name = "Brand Mark";
    image.stable_anchor_id = "brand-mark-view";
    image.style.width = 32.0f;
    image.style.height = 32.0f;
    image.attributes["asset_ref"] = "brand-mark";
    ir.root.children.push_back(std::move(image));

    IRNode knob;
    knob.type = "frame";
    knob.name = "Drive";
    knob.stable_anchor_id = "drive-knob";
    knob.audio_widget = AudioWidgetType::knob;
    knob.audio_label = "Drive";
    knob.audio_default = 0.625f;
    knob.style.width = 48.0f;
    knob.style.height = 48.0f;
    knob.attributes["pulpRouteId"] = "checkpoint.drive";
    knob.attributes["pulpParamKey"] = "drive";
    knob.attributes["pulpBindingModule"] = "main";
    knob.attributes["pulpBindingParam"] = "drive";
    knob.attributes["pulpEventContract"] = "onChange:set_param:drive";
    knob.attributes["pulpGestureContract"] = "rotary_drag:begin/update/end";
    ir.root.children.push_back(std::move(knob));

    CppExportOptions opts;
    opts.function_name = "build_checkpoint_panel";
    opts.binding_function_name = "bind_checkpoint_panel";
    opts.namespace_name = "pulp::test::checkpoint";
    opts.header_filename = "checkpoint_panel.hpp";
    opts.include_comments = false;

    const auto result = generate_pulp_cpp(ir, ir.asset_manifest, opts);
    const auto header_hash = pulp::runtime::sha256_hex(result.header);
    const auto source_hash = pulp::runtime::sha256_hex(result.source);
    const auto binding_hash = pulp::runtime::sha256_hex(result.binding_manifest);

    INFO("CppExportResult golden changed. Review the generated bytes intentionally "
         "before updating checkpoint sizes or SHA-256 values.");
    INFO("header bytes=" << result.header.size() << " sha256=" << header_hash);
    INFO("source bytes=" << result.source.size() << " sha256=" << source_hash);
    INFO("binding_manifest bytes=" << result.binding_manifest.size()
         << " sha256=" << binding_hash);

    CHECK(result.header.size() == 385);
    CHECK(header_hash == "22ab424522a62b3158bcbd503c2c2c371f58c50e94dfc447053dab328cbbf31e");
    CHECK(result.source.size() == 5276);
    CHECK(source_hash == "0b59c5851ff3837b81cbc106c18532e81fe56d62d54dbd60b084fc5141d7d72b");
    CHECK(result.binding_manifest.size() == 413);
    CHECK(binding_hash == "1afbdd18d296b7d27a0b72f42c106e485cc7640a02771b51267c5c66e71d95a5");
}
