// A pixel-level proof that the inspector's semantic-knob panel actually renders.
//
// The knob model (schema, token-vs-local resolution, apply_knob) and the
// overlay's paint/hit logic are covered headlessly elsewhere with a
// RecordingCanvas (draw-command capture, no pixels). This test closes the last
// gap: it configures an InspectorOverlay exactly as a GPU host does — full panel
// (not the bare manipulate-only layer), a declared knob schema, and live sinks
// that persist local writes into a design artifact's EDITMODE block and enqueue
// agent requests — then renders that overlay through the real Skia raster path
// to a PNG. A wrapper View forwards its paint() to overlay.paint(), so the
// screenshot machinery (render_to_png) composites the panel with real pixels,
// no window required. The image is asserted non-trivial AND the panel is proven
// populated (knobs drew hit-rects, the agent field drew) so the PNG can never be
// a blank surface, and a click is driven through the rendered panel to prove the
// surfaced control is live, not decorative.

#include <catch2/catch_test_macros.hpp>

#include <pulp/inspect/inspector_overlay.hpp>
#include <pulp/inspect/tweak_store.hpp>
#include <pulp/inspect/agent_request_queue.hpp>
#include <pulp/design/design_knobs.hpp>
#include <pulp/canvas/canvas.hpp>
#include <pulp/view/screenshot.hpp>
#include <pulp/view/view.hpp>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

using namespace pulp::view;
using namespace pulp::inspect;

namespace {

// A minimal generated artifact with one EDITMODE block for local writes to land.
constexpr const char* kArtifact =
    "// @generated by pulp\n"
    "export const tweaks = /*EDITMODE-BEGIN*/{}/*EDITMODE-END*/;\n"
    "render(tweaks);\n";

// The declared knobs a host installs: a minimalism slider (one token write, one
// local write), a theme flip, and a layout variant — the taxonomy the panel is
// meant to present. A write's "value" is the actual JSON value; a bare number
// stays bare, a string keeps its quotes.
constexpr const char* kKnobJson = R"({
  "knobs": [
    {"id":"minimalism","label":"Minimalism","kind":"slider","positions":[
      {"label":"airy","at":0,"writes":[
        {"key":"accent.saturation","value":1.0},
        {"key":"decoration.density","value":"rich"}]},
      {"label":"dense","at":1,"writes":[
        {"key":"accent.saturation","value":0.35},
        {"key":"decoration.density","value":"sparse"}]}
    ]},
    {"id":"theme","label":"Theme","kind":"enum","positions":[
      {"label":"light","writes":[{"key":"appearance","value":"light"}]},
      {"label":"dark","writes":[{"key":"appearance","value":"dark"}]}
    ]},
    {"id":"layout","label":"Layout","kind":"enum","positions":[
      {"label":"stacked","writes":[{"key":"layout.mode","value":"stacked"}]},
      {"label":"split","writes":[{"key":"layout.mode","value":"split"}]}
    ]}
  ]
})";

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

void write_file(const std::string& path, const std::string& s) {
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out << s;
}

// A view whose only job is to forward its paint into the inspector overlay, so
// the Skia screenshot pass paints the panel like a live host frame would.
struct OverlayHostView : View {
    InspectorOverlay* overlay = nullptr;
    void paint(pulp::canvas::Canvas& canvas) override {
        if (overlay) overlay->paint(canvas);
    }
};

}  // namespace

TEST_CASE("host wiring: the knob panel renders to a Skia PNG and is live",
          "[inspect][overlay][knobs][host][screenshot]") {
    namespace fs = std::filesystem;
    auto dir = fs::temp_directory_path() / "pulp_knob_panel_shot";
    std::error_code ec;
    fs::remove_all(dir, ec);
    fs::create_directories(dir, ec);
    const std::string artifact_path = (dir / "ui.js").string();
    const std::string project = dir.string();
    write_file(artifact_path, kArtifact);

    auto schema = pulp::design::parse_knob_schema(kKnobJson);
    REQUIRE(schema.has_value());

    // accent.saturation is the only bound theme token, so the minimalism slider
    // splits one write to the theme layer and one to the artifact's local block.
    const std::vector<std::string> theme_tokens = {"accent.saturation"};

    constexpr int W = 960;
    constexpr int H = 720;

    OverlayHostView host;
    host.set_bounds({0, 0, static_cast<float>(W), static_cast<float>(H)});

    InspectorOverlay overlay(host);
    overlay.set_active(true);
    overlay.set_manipulate_only(false);   // full panel, not the bare layer
    overlay.set_tweaks_panel_visible(true);
    overlay.set_knob_schema(*schema);

    std::vector<pulp::design::KnobWrite> applied_token_writes;
    overlay.set_knob_apply_sink(
        [&](const InspectorOverlay::KnobApplyEdit& e) {
            const auto* knob = pulp::design::find_knob(*schema, e.knob_id);
            REQUIRE(knob != nullptr);
            auto result = pulp::design::apply_knob(read_file(artifact_path), *knob,
                                                   e.value, theme_tokens);
            REQUIRE(result.has_value());
            write_file(artifact_path, result->text);
            applied_token_writes = result->token_writes;
        });
    overlay.set_agent_request_sink(
        [&](const InspectorOverlay::AgentRequestEdit& e) {
            AgentRequest r;
            r.text = e.text;
            r.design = "ui";
            r.created_at = "2026-07-07T00:00:00Z";
            enqueue_to_file(queue_path(project), r);
        });

    TweakStore store;
    overlay.set_tweak_store(&store);
    host.overlay = &overlay;

    // Render the panel through the real Skia raster path.
    auto png = render_to_png(host, W, H, 2.0f, ScreenshotBackend::skia);
    if (png.empty()) SKIP("Skia raster backend unavailable");
    REQUIRE(png.size() > 2000);
    render_to_file(host, W, H, (dir / "knob-panel.png").string(), 2.0f,
                   ScreenshotBackend::skia);
    // Optional durable capture for eyeballing the rendered panel; off in CI so
    // the test litters nothing (the temp copy above is cleaned below).
    if (const char* out = std::getenv("PULP_KNOB_PANEL_SHOT_OUT"))
        render_to_file(host, W, H, out, 2.0f, ScreenshotBackend::skia);

    // The painted panel is populated, not blank: every declared knob drew its
    // hit-rects, and the agent field drew (it only renders when a sink is set).
    REQUIRE_FALSE(overlay.knob_hits().empty());
    bool saw_minimalism = false, saw_theme = false, saw_layout = false;
    for (const auto& h : overlay.knob_hits()) {
        if (h.knob_id == "minimalism") saw_minimalism = true;
        if (h.knob_id == "theme") saw_theme = true;
        if (h.knob_id == "layout") saw_layout = true;
    }
    REQUIRE(saw_minimalism);
    REQUIRE(saw_theme);
    REQUIRE(saw_layout);
    REQUIRE(overlay.agent_field_bounds().width > 0.0f);

    // The surfaced control is live: clicking the minimalism slider's "dense"
    // anchor drives apply_knob, persisting the local write into the artifact and
    // routing the token write to the host.
    Point dense{-1, -1};
    for (const auto& h : overlay.knob_hits())
        if (h.knob_id == "minimalism" && h.value == "1")
            dense = {h.bounds.x + h.bounds.width / 2, h.bounds.y + h.bounds.height / 2};
    REQUIRE(dense.x >= 0.0f);
    MouseEvent click;
    click.position = dense;
    click.is_down = true;
    overlay.handle_mouse_event(click);

    const std::string after = read_file(artifact_path);
    REQUIRE(after.find("decoration.density") != std::string::npos);
    REQUIRE(after.find("sparse") != std::string::npos);
    REQUIRE(after.find("accent.saturation") == std::string::npos);  // token write stayed out of local
    REQUIRE(applied_token_writes.size() == 1);
    REQUIRE(applied_token_writes[0].key == "accent.saturation");

    fs::remove_all(dir, ec);
}
