// Generated by tools/scripts/agent_capability_manifest.py --write.
// Every advertised public symbol is included and instantiated here.

#include <pulp/audio/instrument_voice_allocator.hpp>
#include <pulp/midi/mpe_voice_tracker.hpp>
#include <pulp/sequence/host_transport_projector.hpp>
#include <pulp/signal/saturator.hpp>
#include <pulp/timebase/quantize.hpp>
#include <pulp/timebase/tick.hpp>

int main() {
    {
        // audio.instrument-voice-allocator
        pulp::audio::InstrumentVoiceAllocator value; (void)value;
    }
    {
        // midi.mpe-voice-tracker
        pulp::midi::MpeVoiceTracker value; (void)value;
    }
    {
        // sequence.host-transport-projector
        pulp::sequence::HostTransportProjector value; (void)value;
    }
    {
        // signal.saturator
        pulp::signal::SaturatorT<float> value; (void)value;
    }
    {
        // timebase.swing
        pulp::timebase::SwingRatio value{}; (void)pulp::timebase::swing_position({}, {1}, value);
    }
    {
        // timebase.tick
        pulp::timebase::TickPosition value{}; (void)value;
    }
    return 0;
}
