// End-to-end host wiring for the inspector's semantic-knob panel + send-to-agent
// field: the overlay emits (knob_id, value) / free-text through its sinks, and a
// host closure applies the change against the REAL core — persisting local writes
// into a design artifact's EDITMODE block via pulp::design::apply_knob and
// enqueuing agent requests via pulp::inspect::enqueue_to_file. This is the
// reference wiring a GPU host installs, exercised without a window so the whole
// round-trip (click → artifact rewrite; type → queue file) is asserted directly.

#include <catch2/catch_test_macros.hpp>

#include <pulp/inspect/inspector_overlay.hpp>
#include <pulp/inspect/tweak_store.hpp>
#include <pulp/inspect/agent_request_queue.hpp>
#include <pulp/design/design_knobs.hpp>
#include <pulp/canvas/canvas.hpp>

#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

using namespace pulp::view;
using namespace pulp::inspect;

namespace {

// A minimal generated artifact with one EDITMODE block for local writes to land.
constexpr const char* kArtifact =
    "// @generated by pulp\n"
    "export const tweaks = /*EDITMODE-BEGIN*/{}/*EDITMODE-END*/;\n"
    "render(tweaks);\n";

// A "minimalism" slider whose two anchors each write one theme-token key
// (accent.saturation) and one local key (decoration.density).
// A write's "value" is the actual JSON value; KnobWrite::json_value is its
// serialization (a bare number stays bare, a string keeps its quotes).
constexpr const char* kKnobJson = R"({
  "knobs": [
    {"id":"minimalism","label":"Minimalism","kind":"slider","positions":[
      {"label":"airy","at":0,"writes":[
        {"key":"accent.saturation","value":1.0},
        {"key":"decoration.density","value":"rich"}]},
      {"label":"dense","at":1,"writes":[
        {"key":"accent.saturation","value":0.35},
        {"key":"decoration.density","value":"sparse"}]}
    ]}
  ]
})";

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

void write_file(const std::string& path, const std::string& s) {
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out << s;
}

}  // namespace

TEST_CASE("host wiring: a knob click rewrites the artifact and splits token writes",
          "[inspect][overlay][knobs][host]") {
    namespace fs = std::filesystem;
    auto dir = fs::temp_directory_path() / "pulp_knob_host_apply";
    std::error_code ec;
    fs::remove_all(dir, ec);
    fs::create_directories(dir, ec);
    const std::string artifact_path = (dir / "ui.js").string();
    write_file(artifact_path, kArtifact);

    auto schema = pulp::design::parse_knob_schema(kKnobJson);
    REQUIRE(schema.has_value());

    // The bound theme: accent.saturation is a real token, decoration.density is
    // not — so the slider's writes split one to the theme layer, one to local.
    const std::vector<std::string> theme_tokens = {"accent.saturation"};

    // The host closure: exactly what a GPU host installs on the sink.
    std::vector<pulp::design::KnobWrite> applied_token_writes;
    View root;
    root.set_bounds({0, 0, 500, 1000});
    InspectorOverlay overlay(root);
    overlay.set_active(true);
    overlay.set_tweaks_panel_visible(true);
    overlay.set_knob_schema(*schema);
    overlay.set_knob_apply_sink(
        [&](const InspectorOverlay::KnobApplyEdit& e) {
            const auto* knob = pulp::design::find_knob(*schema, e.knob_id);
            REQUIRE(knob != nullptr);
            auto result = pulp::design::apply_knob(read_file(artifact_path), *knob,
                                                   e.value, theme_tokens);
            REQUIRE(result.has_value());
            write_file(artifact_path, result->text);  // persist local writes
            applied_token_writes = result->token_writes;  // host applies at theme layer
        });

    TweakStore store;
    overlay.set_tweak_store(&store);
    pulp::canvas::RecordingCanvas canvas;
    overlay.paint(canvas);  // populate knob hit-rects

    // Click the slider's "dense" anchor (emits its numeric anchor "1").
    Point dense{-1, -1};
    for (const auto& h : overlay.knob_hits())
        if (h.knob_id == "minimalism" && h.value == "1")
            dense = {h.bounds.x + h.bounds.width / 2, h.bounds.y + h.bounds.height / 2};
    REQUIRE(dense.x >= 0.0f);
    MouseEvent click;
    click.position = dense;
    click.is_down = true;
    overlay.handle_mouse_event(click);

    // Local write persisted into the artifact's EDITMODE block...
    const std::string after = read_file(artifact_path);
    REQUIRE(after.find("decoration.density") != std::string::npos);
    REQUIRE(after.find("sparse") != std::string::npos);
    // ...markers preserved, surrounding bytes untouched.
    REQUIRE(after.find("/*EDITMODE-BEGIN*/") != std::string::npos);
    REQUIRE(after.find("/*EDITMODE-END*/") != std::string::npos);
    REQUIRE(after.find("render(tweaks);") != std::string::npos);
    // The token write did NOT leak into the local block — it went to the host.
    REQUIRE(after.find("accent.saturation") == std::string::npos);
    REQUIRE(applied_token_writes.size() == 1);
    REQUIRE(applied_token_writes[0].key == "accent.saturation");
    REQUIRE(applied_token_writes[0].json_value == "0.35");

    fs::remove_all(dir, ec);
}

TEST_CASE("host wiring: send-to-agent enqueues a request to the project queue",
          "[inspect][overlay][knobs][host]") {
    namespace fs = std::filesystem;
    auto dir = fs::temp_directory_path() / "pulp_knob_host_agent";
    std::error_code ec;
    fs::remove_all(dir, ec);
    fs::create_directories(dir, ec);
    const std::string project = dir.string();

    View root;
    root.set_bounds({0, 0, 500, 1000});
    InspectorOverlay overlay(root);
    overlay.set_active(true);
    overlay.set_tweaks_panel_visible(true);
    // A schema so the panel renders; the agent field renders because a sink is set.
    auto schema = pulp::design::parse_knob_schema(kKnobJson);
    overlay.set_knob_schema(*schema);
    overlay.set_agent_request_sink(
        [&](const InspectorOverlay::AgentRequestEdit& e) {
            AgentRequest r;
            r.text = e.text;
            r.design = "ui";
            r.created_at = "2026-07-06T18:00:00Z";  // host supplies the clock
            enqueue_to_file(queue_path(project), r);
        });

    TweakStore store;
    overlay.set_tweak_store(&store);
    pulp::canvas::RecordingCanvas canvas;
    overlay.paint(canvas);

    Rect fb = overlay.agent_field_bounds();
    REQUIRE(fb.width > 0.0f);
    MouseEvent focus;
    focus.position = {fb.x + fb.width / 2, fb.y + fb.height / 2};
    focus.is_down = true;
    overlay.handle_mouse_event(focus);
    REQUIRE(overlay.agent_field_active());

    TextInputEvent te;
    te.text = "make the header tighter";
    overlay.handle_text_input(te);
    KeyEvent enter;
    enter.key = KeyCode::enter;
    enter.is_down = true;
    REQUIRE(overlay.handle_key_event(enter));

    // The request landed in the project's queue file.
    auto pending = read_pending_file(queue_path(project));
    REQUIRE(pending.size() == 1);
    REQUIRE(pending[0].text == "make the header tighter");
    REQUIRE(pending[0].design == "ui");
    REQUIRE(overlay.agent_text_buffer().empty());  // cleared after submit

    fs::remove_all(dir, ec);
}
