"""Declarative installed agent capability records."""
from agent_capability_registry_types import binding, capability

EXPORTS = [
    capability(
        key="signal.streaming-analysis-frontends", domain="signal",
        summary="Prepared streaming chroma and onset-novelty analysis frontends.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control; may allocate retained FFT storage",
                   "process": "audio analysis owner", "reset": "audio analysis owner",
                   "release": "destruction off audio"},
        state_model=(
            "Fixed-capacity window, history, and scratch plus retained FFT storage and "
            "cadence, timestamp, chroma, and novelty state."
        ),
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="prepared planar finite audio blocks",
        output_domain="timestamped chroma or onset-novelty frames",
        units=["samples", "frames", "hertz", "normalized magnitude"],
        latency="analysis readiness N-1 samples; chroma center lookback N/2",
        tail="no padded analysis tail", scheduling="streaming hop cadence",
        bindings=[
            binding(role="chroma", kind="cpp_type", include="pulp/signal/analysis_frontends.hpp",
                    qualified_name="pulp::signal::ChromaFrontEndT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:5ccf5005856974faaf4e834abd28a0fc9e25cd816cf8a8a91d3baffc0f92a17e"),
            binding(role="onset_novelty", kind="cpp_type", include="pulp/signal/analysis_frontends.hpp",
                    qualified_name="pulp::signal::OnsetNoveltyFrontEndT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:5ccf5005856974faaf4e834abd28a0fc9e25cd816cf8a8a91d3baffc0f92a17e"),
        ],
        _link_probes=[
            {"role": "chroma", "binding": "pulp::signal::ChromaFrontEndT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
            {"role": "onset_novelty", "binding": "pulp::signal::OnsetNoveltyFrontEndT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
        ],
    ),
    capability(
        key="signal.routing-primitives", domain="signal",
        summary=(
            "Bounded matrix, mid-side, N-way crossfade, click-free switching, and path-latency "
            "alignment primitives."
        ),
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control for matrix and aligner storage",
                   "process": "audio", "reset": "audio", "release": "destruction off audio"},
        state_model=(
            "Fixed matrix ramps and switch weights plus prepared bounded per-path delay storage."
        ),
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="audio buffers, signed gains, path positions, and intrinsic latencies",
        output_domain="routed, transformed, switched, and latency-aligned audio",
        units=["samples", "frames", "linear gain", "path index"],
        latency="zero except aligner maximum declared path latency",
        tail="prepared delay history until drained or reset", scheduling="sample-continuous",
        bindings=[
            binding(role="matrix", kind="cpp_type", include="pulp/signal/audio_matrix_mixer.hpp",
                    qualified_name="pulp::signal::AudioMatrixMixerT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:36ef815dfd9072f7bba8d72aa0e0d53662952e1ee470f1c6b0cd4d64413c55ac"),
            binding(role="mid_side", kind="cpp_function", include="pulp/signal/mid_side.hpp",
                    qualified_name="pulp::signal::mid_side_encode_block<float>", target="Pulp::signal",
                    header_fingerprint="sha256:709cb80f95a21bd20ec21ac9f055da2d41cf47b86ce91cdd444a408e00ff6443",
                    address_expression=("static_cast<bool (*)(const float*, const float*, float*, "
                                        "float*, std::size_t) noexcept>("
                                        "&pulp::signal::mid_side_encode_block<float>)")),
            binding(role="nway", kind="cpp_function", include="pulp/signal/nway_crossfade.hpp",
                    qualified_name="pulp::signal::nway_constant_power_gains<float>", target="Pulp::signal",
                    header_fingerprint="sha256:b1d33521a93b3cefd167f9441b6523b83fdffe1b873a20fb50caedac790ce9be",
                    address_expression=("static_cast<bool (*)(float, std::span<float>) noexcept>("
                                        "&pulp::signal::nway_constant_power_gains<float>)")),
            binding(role="aligner", kind="cpp_type", include="pulp/signal/path_latency_aligner.hpp",
                    qualified_name="pulp::signal::PathLatencyAlignerT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:a7874bab7001e6c6ad31fd85a7176ec13af44c5047bf38d631e207ce3ae914c6"),
            binding(role="switcher", kind="cpp_type", include="pulp/signal/path_switcher.hpp",
                    qualified_name="pulp::signal::ClickFreePathSwitcherT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:adbf41862725587e477711ac144f5326cdcff3a31560aba47708a42d5cd471f1"),
        ],
        _link_probes=[
            {"role": "matrix", "binding": "pulp::signal::AudioMatrixMixerT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
            {"role": "mid_side", "binding": "pulp::signal::mid_side_encode_block<float>",
             "operation": "function_call", "arguments": "nullptr, nullptr, nullptr, nullptr, 0"},
            {"role": "nway", "binding": "pulp::signal::nway_constant_power_gains<float>",
             "operation": "function_call", "arguments": "0.0f, std::span<float>{}"},
            {"role": "aligner", "binding": "pulp::signal::PathLatencyAlignerT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
            {"role": "switcher", "binding": "pulp::signal::ClickFreePathSwitcherT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
        ],
    ),
    capability(
        key="signal.modulation-primitives", domain="signal",
        summary="Shared curve vocabulary, bounded breakpoint envelopes, and rise/fall generators.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control configuration",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed-capacity breakpoint program plus sample phase and stage state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="authored endpoints, curves, sample durations, and triggers",
        output_domain="sample-synchronous caller-domain modulation values",
        units=["samples", "frames", "caller-defined value", "normalized progress"],
        latency="zero", tail="program-defined until idle", scheduling="sample-synchronous",
        bindings=[
            binding(role="curve", kind="cpp_type", include="pulp/signal/modulation_curve.hpp",
                    qualified_name="pulp::signal::ModulationCurve", target="Pulp::signal",
                    header_fingerprint="sha256:da89147c18e3c0479bf02294273bc7ec8ff76bc83cc7e198e645b14fe100a298"),
            binding(role="breakpoint", kind="cpp_type", include="pulp/signal/breakpoint_envelope.hpp",
                    qualified_name="pulp::signal::BreakpointEnvelopeT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:c70262f82754eff2117acabf88d55e8ccc86d0e783d6cea6e04d6af6a671a9f7"),
            binding(role="rise_fall", kind="cpp_type", include="pulp/signal/rise_fall_generator.hpp",
                    qualified_name="pulp::signal::RiseFallGeneratorT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:67185305462aff7fef2f089d00f0bf6eeaa5708436e3f042fca6b8271c4b3fa3"),
        ],
        _link_probes=[
            {"role": "curve", "binding": "pulp::signal::ModulationCurve",
             "operation": "construct", "arguments": ""},
            {"role": "breakpoint", "binding": "pulp::signal::BreakpointEnvelopeT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
            {"role": "rise_fall", "binding": "pulp::signal::RiseFallGeneratorT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
        ],
    ),
    capability(
        key="signal.dither-quantizer", domain="signal",
        summary="Seeded quantization with selectable TPDF dither and first- or second-order shaping.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "none", "process": "audio",
                   "reset": "audio", "release": "none"},
        state_model="Fixed random generator and first- or second-order quantization error feedback.",
        seed_model="public uint32 seed",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="audio samples, bit depth, dither mode, and shaping order",
        output_domain="quantized audio samples", units=["samples", "bits", "normalized amplitude"],
        latency="zero", tail="continuous dither while enabled; reset clears error state",
        scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/dither.hpp",
                         qualified_name="pulp::signal::DitherQuantizerT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:72536ca7644208062b3769cceddfc8aa935d4b441db999b5a61171947446a9af")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::DitherQuantizerT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.stochastic-sources", domain="signal",
        summary="Seeded dust, LFSR, tilted continuous noise, and velvet-noise grid sources.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control configuration and NoiseTilt prepare",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed integer RNG, LFSR, and grid state plus fixed NoiseTilt biquad state.",
        seed_model="public seed per instance",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="seed, event density, register mask, spectral tilt, and level",
        output_domain="bounded stochastic audio samples, impulses, and control values",
        units=["samples", "hertz", "decibels per octave", "normalized amplitude"],
        latency="zero", tail="zero", scheduling="sample-synchronous",
        bindings=[
            binding(role="dust", kind="cpp_type", include="pulp/signal/dust.hpp",
                    qualified_name="pulp::signal::DustT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:89ad91c2a9a54ab6f897d379c3587df4566c402abad75b1f71a802b66291684d"),
            binding(role="lfsr", kind="cpp_type", include="pulp/signal/lfsr.hpp",
                    qualified_name="pulp::signal::LfsrT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:16f353a4e8c715db25f84696bf5ff50ecdbd96aa29364dc3be1232c9e8a209de"),
            binding(role="tilt", kind="cpp_type", include="pulp/signal/noise_tilt.hpp",
                    qualified_name="pulp::signal::NoiseTiltT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:016c8e7e818ad23543da6e37c1e96e41557ed53f898afe80f8d9d65666912adb"),
            binding(role="velvet", kind="cpp_type", include="pulp/signal/velvet_noise.hpp",
                    qualified_name="pulp::signal::VelvetNoiseGridT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:22c73b19189ad33fe12be75c3e8d20f6c7b098810756e31c6bd2dc3f02b75973"),
        ],
        _link_probes=[
            {"role": role, "binding": name, "operation": "member_call", "member": "reset", "arguments": ""}
            for role, name in [
                ("dust", "pulp::signal::DustT<float>"), ("lfsr", "pulp::signal::LfsrT<float>"),
                ("tilt", "pulp::signal::NoiseTiltT<float>"),
                ("velvet", "pulp::signal::VelvetNoiseGridT<float>"),
            ]
        ],
    ),
    capability(
        key="signal.fm-operator-engine", domain="signal",
        summary="Fixed-capacity eight-operator FM and phase-modulation synthesis engine.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control", "process": "audio",
                   "reset": "audio", "release": "none"},
        state_model="Fixed operator routing, phase, feedback, and linear envelope state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="note frequency, velocity, operator settings, and routing matrices",
        output_domain="mono FM or phase-modulated audio",
        units=["samples", "hertz", "frames", "linear gain", "radians"],
        latency="zero", tail="exact longest configured release", scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/fm_operator_engine.hpp",
                         qualified_name="pulp::signal::FmOperatorEngineT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:b92825aa49b916e8c346bf3331fa1dc45759e9589b16a726d861e13c0815c452")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::FmOperatorEngineT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.fractional-delay", domain="signal",
        summary="Prepared causal fractional-delay history and line with Lagrange or Thiran interpolation.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control; may allocate bounded history",
                   "process": "audio", "reset": "audio", "release": "destruction off audio"},
        state_model="Prepared bounded circular history plus interpolation and first-order all-pass state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="audio samples and causal fractional delay requests",
        output_domain="delayed interpolated audio or explicit status",
        units=["samples", "frames"],
        latency="zero processing overhead; requested delay is signal-path latency",
        tail="prepared delay history until overwritten or reset", scheduling="sample-synchronous",
        bindings=[
            binding(role="line", kind="cpp_type", include="pulp/signal/fractional_delay.hpp",
                    qualified_name="pulp::signal::FractionalDelayLineT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:3689804c0a0eccd03298d9949f883cd99fd0035793fed20f4ada5a2e4c90a125"),
            binding(role="history", kind="cpp_type", include="pulp/signal/fractional_delay.hpp",
                    qualified_name="pulp::signal::FractionalDelayHistoryT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:3689804c0a0eccd03298d9949f883cd99fd0035793fed20f4ada5a2e4c90a125"),
        ],
        _link_probes=[
            {"role": "line", "binding": "pulp::signal::FractionalDelayLineT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
            {"role": "history", "binding": "pulp::signal::FractionalDelayHistoryT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
        ],
    ),
    capability(
        key="signal.nonlinear-shaping", domain="signal",
        summary="Antialiased multistage wavefolding, Chebyshev harmonic shaping, and ring modulation.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control; may allocate oversampler storage",
                   "process": "audio", "reset": "audio", "release": "destruction off audio"},
        state_model="Oversampler state plus fixed shaper stages, DC policy, harmonics, and carrier state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="audio and shaping, alias-policy, harmonic, or carrier controls",
        output_domain="nonlinearly shaped audio",
        units=["samples", "hertz", "normalized amplitude", "oversampling factor"],
        latency="reported by alias policy", tail="twice FIR latency or infinite for nonzero DC output",
        scheduling="sample-synchronous",
        bindings=[
            binding(role="wavefolder", kind="cpp_type", include="pulp/signal/nonlinear_shaping.hpp",
                    qualified_name="pulp::signal::MultistageWavefolderT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:bce155041cc613f9e47890bd07c1a4fa9717695dc3fb5c43c32d4152a471a219"),
            binding(role="chebyshev", kind="cpp_type", include="pulp/signal/nonlinear_shaping.hpp",
                    qualified_name="pulp::signal::ChebyshevHarmonicShaperT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:bce155041cc613f9e47890bd07c1a4fa9717695dc3fb5c43c32d4152a471a219"),
            binding(role="ring", kind="cpp_type", include="pulp/signal/nonlinear_shaping.hpp",
                    qualified_name="pulp::signal::NonlinearRingModulatorT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:bce155041cc613f9e47890bd07c1a4fa9717695dc3fb5c43c32d4152a471a219"),
        ],
        _link_probes=[
            {"role": role, "binding": name, "operation": "member_call", "member": "reset", "arguments": ""}
            for role, name in [
                ("wavefolder", "pulp::signal::MultistageWavefolderT<float>"),
                ("chebyshev", "pulp::signal::ChebyshevHarmonicShaperT<float>"),
                ("ring", "pulp::signal::NonlinearRingModulatorT<float>"),
            ]
        ],
    ),
    capability(
        key="signal.scope-capture", domain="signal",
        summary="Fixed-capacity triggered waveform capture with pretrigger and holdoff.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control configuration",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed pretrigger ring plus armed, triggered, holdoff, and capture state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="audio samples and trigger, pretrigger, holdoff, and capture policy",
        output_domain="fixed-capacity captured waveform frame",
        units=["samples", "frames", "normalized amplitude"],
        latency="zero audio-path latency; capture readiness is separate",
        tail="none", scheduling="sample-synchronous trigger observation",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/scope_capture.hpp",
                         qualified_name="pulp::signal::ScopeCaptureT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:0989e11d3171977da2f2e61d945fb1442fe9a9dfa9df94eb436b19fed3f104b5")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::ScopeCaptureT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.spectrum-trace", domain="signal",
        summary="Fixed-capacity FFT-bin aggregation, smoothing, weighting, and peak-hold trace.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control configuration",
                   "process": "audio analysis", "reset": "audio", "release": "none"},
        state_model="Fixed trace, smoothing, weighting, and peak-hold arrays without FFT ownership.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite FFT magnitude bins and display-band configuration",
        output_domain="conditioned spectrum trace bands",
        units=["bins", "hertz", "decibels", "frames"],
        latency="zero algorithmic", tail="smoothing and peak state until reset",
        scheduling="one update per supplied spectrum frame",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/spectrum_trace.hpp",
                         qualified_name="pulp::signal::SpectrumTraceT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:2db177e808a86cbe881d3a8c636eb33716db1a0ed556fbf1049a5d23583c5bee")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::SpectrumTraceT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.six-band-eq", domain="signal",
        summary="Fixed six-band stereo equalizer with atomic parameter updates and bounded transitions.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control coefficient design",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed per-channel six-band biquad banks plus optional transition bank state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="audio plus six plain-domain frequency, gain, and Q controls",
        output_domain="equalized audio", units=["samples", "hertz", "decibels", "Q"],
        latency="zero", tail="recursive IIR decay", scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/six_band_eq.hpp",
                         qualified_name="pulp::signal::SixBandEqT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:85f2051455ad88b04aa92f73aa44605ec07007acd8761df8deecaa755b08066a")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::SixBandEqT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.source-filter-analysis", domain="signal",
        summary="Prepared offline cepstral spectral-envelope and linear-predictive analysis.",
        rt_class="offline",
        lifecycle={"construction": "control", "prepare": "offline; may allocate bounded storage",
                   "process": "offline allocation-free after prepare",
                   "reset": "reprepare or next analysis transaction",
                   "release": "destruction off audio"},
        state_model="Bounded FFT, scratch, coefficient, and model storage with transactional publication.",
        seed_model="none",
        determinism={"repeatability": "tolerance_bounded", "block_partition": "not_applicable",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="log-magnitude frames or finite time-domain samples",
        output_domain="cepstral envelope or linear-predictive model",
        units=["bins", "samples", "normalized coefficients", "power"],
        latency="offline whole-frame analysis", tail="none", scheduling="offline request",
        bindings=[
            binding(role="cepstral", kind="cpp_type", include="pulp/signal/source_filter_analysis.hpp",
                    qualified_name="pulp::signal::CepstralEnvelopeAnalyzerT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:eb64faa37ff3e4b93fc884943fda3ea4acc723b61b9b8593abac3f0102dd3d26"),
            binding(role="lpc", kind="cpp_type", include="pulp/signal/source_filter_analysis.hpp",
                    qualified_name="pulp::signal::LpcAnalyzerT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:eb64faa37ff3e4b93fc884943fda3ea4acc723b61b9b8593abac3f0102dd3d26"),
        ],
        _link_probes=[
            {"role": "cepstral", "binding": "pulp::signal::CepstralEnvelopeAnalyzerT<float>",
             "operation": "construct", "arguments": ""},
            {"role": "lpc", "binding": "pulp::signal::LpcAnalyzerT<float>",
             "operation": "construct", "arguments": ""},
        ],
    ),
    capability(
        key="signal.unison-voice-primitives", domain="signal",
        summary="Deterministic unison voice layout and PolyBLEP supersaw oscillator bank.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control configure and prepare",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed deterministic layout parameters and bounded oscillator array.",
        seed_model="public seed and note-instance identity",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="note frequency, unison specification, seed, and absolute frame",
        output_domain="stereo unison audio and per-child layout parameters",
        units=["samples", "hertz", "cents", "frames", "pan", "linear gain"],
        latency="zero", tail="continuous while voice is active", scheduling="absolute-frame audio",
        bindings=[
            binding(role="layout", kind="cpp_type", include="pulp/signal/unison.hpp",
                    qualified_name="pulp::signal::UnisonLayout<>", target="Pulp::signal",
                    header_fingerprint="sha256:0a3a14899d57ff5040b47823bb98c36ed055bf98b6946d2a8892c44a95a686a5"),
            binding(role="supersaw", kind="cpp_type", include="pulp/signal/supersaw.hpp",
                    qualified_name="pulp::signal::SupersawT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:c790c2b734d6a86f02ffedd560a0b14ba7529dbb5ce50b4e93a29b414217f338"),
        ],
        _link_probes=[
            {"role": "layout", "binding": "pulp::signal::UnisonLayout<>",
             "operation": "member_call", "member": "configure",
             "arguments": "pulp::signal::UnisonSpec{}"},
            {"role": "supersaw", "binding": "pulp::signal::SupersawT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
        ],
    ),
    capability(
        key="signal.true-peak-limiter", domain="signal",
        summary="Prepared intersample true-peak limiter with explicit lookahead and channel linking.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control; may allocate detector and delay storage",
                   "process": "audio", "reset": "audio", "release": "destruction off audio"},
        state_model="Prepared intersample detector, scheduling horizon, lookahead delay, and gain state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite interleaved audio, ceiling, lookahead, release, and channel-link policy",
        output_domain="true-peak-limited audio and gain-reduction telemetry",
        units=["samples", "frames", "decibels true peak", "milliseconds"],
        latency="detector latency plus scheduling horizon plus user lookahead",
        tail="exact latency_samples", scheduling="sample-synchronous lookahead",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/true_peak_limiter.hpp",
                         qualified_name="pulp::signal::TruePeakLimiterT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:027278e6f446a6eb769576cea18e0007648d7d5bcd25231023f1d09a844a84ca")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::TruePeakLimiterT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.dynamics-envelope-contract", domain="signal",
        summary="Canonical mono/stereo peak or RMS envelope followers and gain-reduction vocabulary.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control prepare and setters",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed attack-release detector state and canonical scalar gain-reduction value.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="signed audio samples and attack, release, detector, and stereo-link policy",
        output_domain="mono or stereo envelopes and non-negative attenuation magnitude",
        units=["samples", "milliseconds", "decibels", "normalized link"],
        latency="zero", tail="recursive envelope decay until reset", scheduling="sample-synchronous",
        bindings=[
            binding(role="mono", kind="cpp_type", include="pulp/signal/dynamics_contract.hpp",
                    qualified_name="pulp::signal::EnvelopeFollowerT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:576ed92bd47a0cce545d9eb5df9a5e83732829944550fff7416c552de2506a2f"),
            binding(role="stereo", kind="cpp_type", include="pulp/signal/dynamics_contract.hpp",
                    qualified_name="pulp::signal::StereoEnvelopeFollowerT<float>", target="Pulp::signal",
                    header_fingerprint="sha256:576ed92bd47a0cce545d9eb5df9a5e83732829944550fff7416c552de2506a2f"),
        ],
        _link_probes=[
            {"role": "mono", "binding": "pulp::signal::EnvelopeFollowerT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
            {"role": "stereo", "binding": "pulp::signal::StereoEnvelopeFollowerT<float>",
             "operation": "member_call", "member": "reset", "arguments": ""},
        ],
    ),
    capability(
        key="signal.linkwitz-riley-crossover", domain="signal",
        summary="Fixed-capacity multi-band Linkwitz-Riley crossover with bounded realtime retuning.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control prepare and bounded sweep configuration",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed cascaded crossover and sweep banks with recursive filter state.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="audio, ordered crossover frequencies, band count, and transition samples",
        output_domain="phase-aligned crossover bands",
        units=["samples", "hertz", "bands", "frames"],
        latency="zero", tail="recursive IIR decay", scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/linkwitz_riley.hpp",
                         qualified_name="pulp::signal::LinkwitzRileyCrossoverT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:38fca0b926e0b4cb492528f95a69af89eb7ec5a0e83ed8692eb195c0cd35fa64")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::LinkwitzRileyCrossoverT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.multi-channel-meter", domain="signal",
        summary="Fixed-storage peak, RMS, loudness, correlation, and clip metering for up to 16 channels.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control", "process": "audio",
                   "reset": "audio", "release": "none"},
        state_model="Fixed peak, RMS, K-weighted loudness, correlation, and clip accumulators.",
        seed_model="none",
        determinism={"repeatability": "tolerance_bounded", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite planar audio, channel count, roles, and sample rate",
        output_domain="lock-free multi-channel meter snapshot",
        units=["samples", "frames", "decibels full scale", "LUFS", "correlation"],
        latency="measurement-window readiness; no audio-path delay",
        tail="measurement history until reset", scheduling="block accumulation and snapshot",
        bindings=[binding(role="entrypoint", kind="cpp_type", include="pulp/signal/multi_channel_meter.hpp",
                         qualified_name="pulp::signal::MultiChannelMeterT<float>", target="Pulp::signal",
                         header_fingerprint="sha256:a9437e126faff12dfc60d80e59381fe0f5f005b3638d445d06daf4b8cb2fd695")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::MultiChannelMeterT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.transient-designer", domain="signal",
        summary="Zero-latency attack and sustain shaping from independent peak envelopes.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed fast and slow peak-envelope state plus contrast and gain telemetry.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite mono audio and attack, sustain, fast, and slow envelope controls",
        output_domain="transient-shaped mono audio plus contrast and gain telemetry",
        units=["samples", "milliseconds", "decibels", "normalized contrast"],
        latency="zero", tail="detector history until reset", scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/transient_designer.hpp",
                         qualified_name="pulp::signal::TransientDesignerT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:f82fbba753fd01410ff7117cf86f9f8868d071a3979c36d87f677f99cbc34ae2")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::TransientDesignerT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.headphone-crossfeed", domain="signal",
        summary="Bounded delayed and low-pass-filtered stereo headphone crossfeed.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed stereo delay arrays, one-pole filter state, and derived mix controls.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite stereo audio plus amount, delay, cutoff, and enable controls",
        output_domain="speaker-like crossfed stereo audio",
        units=["samples", "milliseconds", "hertz", "linear gain", "normalized amount"],
        latency="zero direct-path algorithmic latency",
        tail="asymptotic one-pole decay while crossfeed is active",
        scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/headphone_crossfeed.hpp",
                         qualified_name="pulp::signal::HeadphoneCrossfeedT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:ed91124815b320271a1246f87fa35655cc02ef989a9caa6cab734af0a363268c")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::HeadphoneCrossfeedT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.spectral-band-mask", domain="signal",
        summary=(
            "Fixed-capacity zoomable band layouts compiled into allocation-free "
            "complex-spectrum gain masks."
        ),
        rt_class="mixed",
        lifecycle={
            "construction": "control",
            "prepare": "control-side immutable mask compilation",
            "process": "audio spectral-frame owner",
            "reset": "none",
            "release": "none",
        },
        state_model=(
            "Fixed 64-slot finite-gain and categorical-mute layout plus a fixed "
            "8193-bin compiled gain table."
        ),
        seed_model="none",
        determinism={"repeatability": "tolerance_bounded", "block_partition": "not_applicable",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain=(
            "finite linear or logarithmic band layouts, prepared FFT geometry, and "
            "coherent channel groups of one-sided complex spectra"
        ),
        output_domain="immutable gain tables and in-place masked complex spectra",
        units=["bins", "channels", "frames", "hertz", "decibels", "linear gain"],
        latency="zero additional frame-domain latency",
        tail="none",
        scheduling="control-side table compilation then one supplied spectral frame per apply call",
        bindings=[
            binding(role="layout", kind="cpp_type",
                    include="pulp/signal/spectral_band_mask.hpp",
                    qualified_name="pulp::signal::SpectralBandLayoutT<float>",
                    target="Pulp::signal",
                    header_fingerprint="sha256:2c8d911425699a83465c1fd5adf554ab7218a5e1de584b63413629eb699ccb3d"),
            binding(role="table", kind="cpp_type",
                    include="pulp/signal/spectral_band_mask.hpp",
                    qualified_name="pulp::signal::SpectralMaskTableT<float>",
                    target="Pulp::signal",
                    header_fingerprint="sha256:2c8d911425699a83465c1fd5adf554ab7218a5e1de584b63413629eb699ccb3d"),
            binding(role="compile", kind="cpp_function",
                    include="pulp/signal/spectral_band_mask.hpp",
                    qualified_name="pulp::signal::build_spectral_mask<float>",
                    target="Pulp::signal",
                    header_fingerprint="sha256:2c8d911425699a83465c1fd5adf554ab7218a5e1de584b63413629eb699ccb3d",
                    address_expression=(
                        "static_cast<bool (*)(const pulp::signal::SpectralBandLayoutT<float>&, "
                        "int, float, pulp::signal::SpectralMaskTableT<float>&) noexcept>("
                        "&pulp::signal::build_spectral_mask<float>)"
                    )),
            binding(role="apply", kind="cpp_function",
                    include="pulp/signal/spectral_band_mask.hpp",
                    qualified_name="pulp::signal::apply_spectral_mask<float>",
                    target="Pulp::signal",
                    header_fingerprint="sha256:2c8d911425699a83465c1fd5adf554ab7218a5e1de584b63413629eb699ccb3d",
                    address_expression=(
                        "static_cast<bool (*)(std::complex<float>* const*, int, int, "
                        "const pulp::signal::SpectralMaskTableT<float>&) noexcept>("
                        "&pulp::signal::apply_spectral_mask<float>)"
                    )),
        ],
        _link_probes=[
            {"role": "layout", "binding": "pulp::signal::SpectralBandLayoutT<float>",
             "operation": "construct", "arguments": ""},
            {"role": "table", "binding": "pulp::signal::SpectralMaskTableT<float>",
             "operation": "construct", "arguments": ""},
            {"role": "compile", "binding": "pulp::signal::build_spectral_mask<float>",
             "operation": "function_call", "arguments": (
                 "pulp::signal::SpectralBandLayoutT<float>{}, 1024, 48000.0f, "
                 "[]() -> pulp::signal::SpectralMaskTableT<float>& { "
                 "static pulp::signal::SpectralMaskTableT<float> table; return table; }()"
             )},
            {"role": "apply", "binding": "pulp::signal::apply_spectral_mask<float>",
             "operation": "function_call", "arguments": (
                 "nullptr, 0, 0, pulp::signal::SpectralMaskTableT<float>{}"
             )},
        ],
    ),
    capability(
        key="signal.spectral-gate", domain="signal",
        summary="Allocation-free scalar or per-bin gating of caller-owned complex spectra.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "none",
                   "process": "audio", "reset": "none", "release": "none"},
        state_model="Fixed scalar threshold only; spectral frames and optional curves are caller-owned.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "not_applicable",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite coherent channel groups of one-sided complex spectra and thresholds",
        output_domain="in-place gated complex spectra",
        units=["bins", "channels", "linear magnitude"],
        latency="zero frame-domain latency", tail="none", scheduling="one supplied spectral frame",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/spectral_gate_blur.hpp",
                         qualified_name="pulp::signal::SpectralGateT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:75cf322be3a308259d63737d67320b94a926c9b9fb290c6a751dd07ee781d845")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::SpectralGateT<float>",
                       "operation": "member_call", "member": "set_threshold_magnitude",
                       "arguments": "0.0f"}],
    ),
    capability(
        key="signal.spectral-frame-blur", domain="signal",
        summary="Prepared causal finite moving-average blur of complex spectral-frame magnitudes.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control; allocates bounded history",
                   "process": "audio frame owner", "reset": "audio frame owner",
                   "release": "destruction off audio"},
        state_model="Prepared bounded magnitude history, running means, counts, and retained phases.",
        seed_model="none",
        determinism={"repeatability": "tolerance_bounded", "block_partition": "not_applicable",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="prepared coherent channel groups of one-sided complex spectra",
        output_domain="in-place temporally blurred complex spectra",
        units=["bins", "channels", "frames", "linear magnitude", "bytes"],
        latency="zero additional frame-domain latency",
        tail="at most blur_frames retained analysis frames",
        scheduling="one supplied spectral frame per process call",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/spectral_gate_blur.hpp",
                         qualified_name="pulp::signal::SpectralFrameBlurT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:75cf322be3a308259d63737d67320b94a926c9b9fb290c6a751dd07ee781d845")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::SpectralFrameBlurT<float>",
                       "operation": "member_call", "member": "prepare", "arguments": "1, 1, 1"}],
    ),
    capability(
        key="signal.dynamic-eq", domain="signal",
        summary="Fixed-state threshold-driven single-band dynamic equalization.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control coefficient design",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed band-pass biquad, peak envelope, parameters, and gain telemetry.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite mono audio plus frequency, Q, threshold, range, and timing controls",
        output_domain="dynamically equalized mono audio plus detector and gain telemetry",
        units=["samples", "hertz", "Q", "decibels", "milliseconds", "normalized activity"],
        latency="zero", tail="recursive biquad and envelope decay until reset",
        scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/dynamic_eq.hpp",
                         qualified_name="pulp::signal::DynamicEqBandT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:eb6ed3b73030b8046706e6dfb8bfe9a143134b7dea59c289ce142fdcbb12254b")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::DynamicEqBandT<float>",
                       "operation": "member_call", "member": "reset", "arguments": ""}],
    ),
    capability(
        key="signal.spectral-morph", domain="signal",
        summary="Allocation-free magnitude and phase morphing between coherent complex spectra.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control; allocation-free geometry setup",
                   "process": "audio frame owner", "reset": "audio frame owner", "release": "none"},
        state_model="Fixed interpolation policy and prepared channel/bin geometry; spectral frames are caller-owned.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="two prepared coherent channel groups of one-sided complex spectra and normalized morph amounts",
        output_domain="caller-owned magnitude- and phase-morphed complex spectra",
        units=["bins", "channels", "linear magnitude", "radians", "normalized amount"],
        latency="zero additional frame-domain latency", tail="none",
        scheduling="one supplied paired spectral frame or disjoint bin partitions",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/spectral_morph.hpp",
                         qualified_name="pulp::signal::SpectralMorphT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:0991d2973294306182824a6d8b579007946dff976407511ce064774677c1adb3")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::SpectralMorphT<float>",
                       "operation": "member_call", "member": "prepare", "arguments": "1, 129"}],
    ),
    capability(
        key="signal.cross-feedback-multitap-delay", domain="signal",
        summary="Prepared wet-only stereo multitap delay with bounded normalized cross-feedback.",
        rt_class="mixed",
        lifecycle={"construction": "control", "prepare": "control; allocates bounded stereo delay storage",
                   "process": "audio", "reset": "audio", "release": "destruction off audio"},
        state_model="Prepared stereo delay histories, up to eight tap definitions, derived pan weights, and a bounded feedback matrix.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite stereo audio plus bounded tap, feedback, cross-feedback, pan, and width controls",
        output_domain="wet-only delayed stereo audio",
        units=["samples", "milliseconds", "linear gain", "normalized amount", "tap index"],
        latency="zero direct-path algorithmic latency",
        tail="latest tap delay without feedback; unbounded decay while a nonzero feedback route is active",
        scheduling="sample-continuous",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/cross_feedback_multitap_delay.hpp",
                         qualified_name="pulp::signal::CrossFeedbackMultitapDelayT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:14184a88f394c3da92e4d39d7c8c5f9b481f5729acfafd7a0a7e5d773ee68e98")],
        _link_probes=[{"role": "entrypoint",
                       "binding": "pulp::signal::CrossFeedbackMultitapDelayT<float>",
                       "operation": "member_call", "member": "prepare",
                       "arguments": "48000.0, 100.0"}],
    ),
    capability(
        key="signal.de-esser", domain="signal",
        summary="Prepared split-band de-essing with an independent frequency-selective detector.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control coefficient design",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed detector biquad, peak envelope, Linkwitz-Riley split, configuration, modes, and gain telemetry.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite mono audio plus detector, split, threshold, range, timing, bypass, and listen controls",
        output_domain="de-essed mono or detector-listen audio plus detector and gain-reduction telemetry",
        units=["samples", "hertz", "Q", "decibels", "milliseconds"],
        latency="zero", tail="recursive detector, envelope, and crossover decay until reset",
        scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/de_esser.hpp",
                         qualified_name="pulp::signal::DeEsserT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:fd61c1c4680c790d8617ec55164367d535cc079878e2bcb9780077c59bbf040d")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::DeEsserT<float>",
                       "operation": "member_call", "member": "prepare", "arguments": "48000.0f"}],
    ),
    capability(
        key="signal.expander", domain="signal",
        summary="Prepared bounded stereo upward or downward expansion with shared dynamics telemetry.",
        rt_class="audio",
        lifecycle={"construction": "control", "prepare": "control detector setup",
                   "process": "audio", "reset": "audio", "release": "none"},
        state_model="Fixed two-channel envelope state, bounded curve configuration, bypass state, and signed gain telemetry.",
        seed_model="none",
        determinism={"repeatability": "bit_exact", "block_partition": "invariant",
                     "platform_scope": "same_build", "transport_history": "irrelevant"},
        input_domain="finite stereo audio plus expansion mode, threshold, ratio, range, knee, timing, detector, and link controls",
        output_domain="expanded stereo audio plus signed gain and gain-reduction telemetry",
        units=["samples", "decibels", "ratio", "milliseconds", "normalized link"],
        latency="zero", tail="none", scheduling="sample-synchronous",
        bindings=[binding(role="entrypoint", kind="cpp_type",
                         include="pulp/signal/expander.hpp",
                         qualified_name="pulp::signal::ExpanderT<float>",
                         target="Pulp::signal",
                         header_fingerprint="sha256:bf318bbe864c1ea706eed101e63f6469602a7c7c639ce86bffb650c13ef08741")],
        _link_probes=[{"role": "entrypoint", "binding": "pulp::signal::ExpanderT<float>",
                       "operation": "member_call", "member": "prepare", "arguments": "48000.0f"}],
    ),
]
