#!/usr/bin/env python3
"""Generate the CI routing + landing digest inside CLAUDE.md.

The block between `<!-- generated:start id=ci-routing-digest -->` and its end
marker is rendered from checked-in state only: the routing contract
(`runner_topology.json`), the workflows, and the advertised-labels snapshot,
through the same offline evaluation as `runner_topology_check.py
--mode=static`. It is always in an agent's context, so a routing fact that
changes in the contract reaches the next session without anyone remembering to
edit prose.

It carries dates, never ages: an age computed at generation time would make the
block stale every morning and turn `--check` into a calendar.

    python3 tools/scripts/ci_routing_digest.py --check   # exit 1 when stale (ctest)
    python3 tools/scripts/ci_routing_digest.py --write   # regenerate the block
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE))

import runner_topology_check as rtc  # noqa: E402
import runner_topology_static as st  # noqa: E402
from tools_registry_check import _splice  # noqa: E402

BLOCK_ID = "ci-routing-digest"
DOC = ROOT / "CLAUDE.md"


def _hosts(detail: str) -> list[str]:
    handles = detail[len("by "):].split(", ") if detail.startswith("by ") else []
    return sorted({handle.split(":")[0] for handle in handles})


def _lane_line(variable: str, rows: list[st.Row]) -> str:
    expect = [r for r in rows if r.source == "expect"]
    verdicts = sorted({r.verdict for r in expect})
    text = "/".join(verdicts)
    if verdicts == [st.REACHABLE]:
        events = sorted({r.event for r in expect if r.event != "*"})
        workflows = sorted({r.workflow for r in expect if r.workflow})
        hosts = sorted({h for r in expect for h in _hosts(r.detail)})
        scope = f" on {', '.join(events)}" if events else f" from {', '.join(workflows)}"
        text += f"{scope} by {', '.join(hosts)}"
    elif verdicts == [st.UNKNOWN]:
        text += f" ({expect[0].detail})"
    fallback = [r for r in rows if r.source == "unset_fallback" and r.verdict == st.UNSERVED]
    if fallback:
        text += "; its unset fallback is UNSERVED"
    return f"- `{variable}`: {text}"


def render(contract: rtc.Contract, snapshot: st.Snapshot, workflows_dir: Path) -> str:
    rows = st.evaluate(contract, snapshot, workflows_dir, rtc.DEFAULT_REPO)
    by_lane: dict[str, list[st.Row]] = {}
    for row in rows:
        by_lane.setdefault(row.variable, []).append(row)
    required = [lane.variable for lane in contract.lanes if lane.severity == "required"]
    advisory = [lane.variable for lane in contract.lanes if lane.severity != "required"]
    counts: dict[str, int] = {}
    for variable in advisory:
        for verdict in {r.verdict for r in by_lane[variable] if r.source == "expect"}:
            counts[verdict] = counts.get(verdict, 0) + 1
    undeclared = sum(1 for r in rows if r.verdict == st.UNDECLARED)
    commit = (snapshot.generated_from.get("commit") or "unknown")[:12]

    lines = [
        "Offline routing verdicts from `runner_topology_check.py --mode=static`: "
        f"DECLARED supply (`tools/scripts/fleet_advertised_labels.json` @ `{commit}`), "
        "never live service; `--mode=report` is the live check.",
        "",
        "Required lanes:",
    ]
    lines += [_lane_line(variable, by_lane[variable]) for variable in required]
    summary = ", ".join(f"{n} {verdict}" for verdict, n in sorted(counts.items()))
    lines.append(f"- Advisory lanes: {summary}. Selector variables with no lane: "
                 f"{undeclared} (UNDECLARED, info).")
    lines += ["", "Active routing overrides (`runner_topology.json` `overrides`; "
                  "an expired one fails every mode):"]
    overrides = contract.raw.get("overrides", []) or []
    if overrides:
        for o in overrides:
            lines.append(f"- `{o.get('id')}`: `{o.get('subject')}` = `{o.get('value')}`, "
                         f"owner {o.get('owner')}, since {o.get('since')}, "
                         f"expires {o.get('expires')}. Revert when: "
                         f"{o.get('revert_condition')}")
    else:
        lines.append("- none")
    lines += [
        "",
        "Landing API traps (verify with "
        "`decisions_contract.py --mode probe --live`, manual only):",
        "- REST `pulls/<n>.auto_merge` (and GraphQL `autoMergeRequest`) read null "
        "for a PR the merge queue already holds; read GraphQL `mergeQueueEntry`.",
        "- Classic branch protection omits a ruleset-based merge queue; query "
        "`repos/<o>/<r>/rulesets` before concluding there is no queue.",
        "",
        "GENERATED by `tools/scripts/ci_routing_digest.py --write`. Do not edit by hand.",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate the block")
    mode.add_argument("--check", action="store_true", help="fail when stale (default)")
    ap.add_argument("--doc", type=Path, default=DOC)
    ap.add_argument("--contract", type=Path, default=rtc.DEFAULT_CONTRACT)
    ap.add_argument("--workflows-dir", type=Path, default=ROOT / ".github" / "workflows")
    args = ap.parse_args(argv)

    contract = rtc.load_contract(args.contract)
    snapshot = st.load_snapshot(args.contract.resolve().parent / contract.static_snapshot)
    block = render(contract, snapshot, args.workflows_dir)
    text = args.doc.read_text(encoding="utf-8")
    spliced = _splice(text, block, BLOCK_ID)
    if spliced is None:
        print(f"ERROR: {args.doc.name} is missing <!-- generated:start id={BLOCK_ID} --> / "
              f"<!-- generated:end id={BLOCK_ID} -->", file=sys.stderr)
        return 1
    if args.write:
        if spliced != text:
            args.doc.write_text(spliced, encoding="utf-8")
            print(f"wrote the {BLOCK_ID} block in {args.doc.name}")
        else:
            print(f"{BLOCK_ID} block already up to date")
        return 0
    if spliced != text:
        print(f"ERROR: the {BLOCK_ID} block in {args.doc.name} is stale or hand-edited. "
              "Regenerate it: python3 tools/scripts/ci_routing_digest.py --write",
              file=sys.stderr)
        return 1
    print(f"{BLOCK_ID} block in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
