#!/usr/bin/env python3
"""Audit the bounded Faust/Cmajor provenance and optional-tool contract."""

from __future__ import annotations

import argparse
from pathlib import Path

REFERENCE_HEADERS = {
    "gain": Path("examples/faust-gain/reference_gain.hpp"),
    "filter": Path("examples/faust-filter/reference_filter.hpp"),
    "tremolo": Path("examples/faust-tremolo/reference_tremolo.hpp"),
}

AUDITED_TEXT_PATHS = (
    Path("core/dsl/include/pulp/dsl/faust_base.hpp"),
    Path("tools/cmake/PulpFaust.cmake"),
    Path("docs/guides/faust.md"),
    Path("docs/guides/examples.md"),
    Path("docs/contracts/phase1-reality-snapshot.yaml"),
    Path("docs/reference/capabilities.md"),
    Path("docs/reference/cmake.md"),
    Path("docs/reference/modules.md"),
    Path("docs/status/cmake-functions.yaml"),
    Path("examples/faust-gain/CMakeLists.txt"),
    Path("examples/faust-tremolo/CMakeLists.txt"),
    *REFERENCE_HEADERS.values(),
)

UNSUPPORTED_PHRASES = (
    "checked-in generated",
    "pre-generated",
    "Generated by FAUST offline codegen from",
    "using pre-generated",
    "Re-generate with:",
    "offline code generation into checked-in C++ headers",
    "prove the generated-C++ path",
)


def _read(root: Path, relative: Path, errors: list[str]) -> str:
    path = root / relative
    if not path.is_file():
        errors.append(f"missing required path: {relative}")
        return ""
    return path.read_text(encoding="utf-8")


def audit(root: Path) -> list[str]:
    root = root.resolve()
    errors: list[str] = []

    for relative in AUDITED_TEXT_PATHS:
        text = _read(root, relative, errors)
        for phrase in UNSUPPORTED_PHRASES:
            if phrase.casefold() in text.casefold():
                errors.append(f"{relative}: unsupported checked-in generation claim: {phrase}")

    marker = "Pulp-owned reference DSP implementation"
    for stem, relative in REFERENCE_HEADERS.items():
        reference = _read(root, relative, errors)
        if marker not in reference:
            errors.append(f"{relative}: missing Pulp-owned reference marker")
        if f"class Faust{stem.title()}Dsp" not in reference:
            errors.append(f"{relative}: expected reference DSP class is missing")
        if not (root / relative.parent / f"{stem}.dsp").is_file():
            errors.append(f"{relative.parent}/{stem}.dsp: optional authoring example is missing")

        directory = relative.parent
        shim_relative = directory / f"generated_{stem}.hpp"
        shim = _read(root, shim_relative, errors)
        expected_include = f'#include "reference_{stem}.hpp"'
        if "Compatibility forwarding header" not in shim or expected_include not in shim:
            errors.append(f"{shim_relative}: compatibility forwarding contract is broken")
        if "class Faust" in shim or "void compute" in shim:
            errors.append(f"{shim_relative}: compatibility header contains an implementation")

        adapter_relative = directory / f"faust_{stem}.hpp"
        adapter = _read(root, adapter_relative, errors)
        if expected_include not in adapter or f'"generated_{stem}.hpp"' in adapter:
            errors.append(f"{adapter_relative}: adapter does not use the canonical reference header")

    dependencies = _read(root, Path("DEPENDENCIES.md"), errors)
    for tool, boundary in (
        ("Cmajor toolchain (`cmaj`)", "Developer supplies and licenses the executable independently"),
        ("Faust compiler (`faust`)", "Developer supplies the executable independently"),
    ):
        if dependencies.count(tool) != 1 or boundary not in dependencies:
            errors.append(f"DEPENDENCIES.md: missing optional external-tool boundary for {tool}")
    if "not claimed compiler output" not in dependencies:
        errors.append("DEPENDENCIES.md: missing Faust reference-provenance boundary")

    notice = _read(root, Path("NOTICE.md"), errors)
    for heading in ("## faust", "## cmajor"):
        if heading in notice.casefold():
            errors.append(f"NOTICE.md: unsupported redistributed-tool attribution: {heading}")

    cmajor_guide = _read(root, Path("docs/guides/cmajor.md"), errors)
    cmajor_helper = _read(root, Path("tools/scripts/cmajor_external.py"), errors)
    if "external toolchain" not in cmajor_guide.casefold() or "does not bundle" not in cmajor_helper.casefold():
        errors.append("Cmajor external-only support boundary is missing")

    faust_cmake = _read(root, Path("tools/cmake/PulpFaust.cmake"), errors)
    if "find_program(FAUST_COMPILER faust)" not in faust_cmake:
        errors.append("PulpFaust.cmake: optional compiler discovery is missing")
    if "FATAL_ERROR" in faust_cmake or "FetchContent" in faust_cmake:
        errors.append("PulpFaust.cmake: Faust must remain optional and externally supplied")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    errors = audit(args.root)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print("DSP provenance audit: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
