#!/usr/bin/env python3
"""Generate Pulp's independently derived minimum-phase BLEP residual table.

Method reference: Eli Brandt, "Hard Sync Without Aliasing", ICMC 2001.
https://www.cs.cmu.edu/~eli/papers/icmc01-hardsync.pdf
"""

from __future__ import annotations

import argparse
import cmath
import math
from pathlib import Path
import struct
import sys


KERNEL_SAMPLES = 32
PHASES_PER_SAMPLE = 64
TABLE_SIZE = KERNEL_SAMPLES * PHASES_PER_SAMPLE


def fft(values: list[complex], *, inverse: bool = False) -> list[complex]:
    count = len(values)
    if count == 0 or count & (count - 1):
        raise ValueError("FFT length must be a nonzero power of two")

    result = list(values)
    target = 0
    for source in range(1, count):
        bit = count >> 1
        while target & bit:
            target ^= bit
            bit >>= 1
        target ^= bit
        if source < target:
            result[source], result[target] = result[target], result[source]

    length = 2
    direction = 1.0 if inverse else -1.0
    while length <= count:
        root = cmath.exp(direction * 2j * math.pi / length)
        half = length // 2
        for begin in range(0, count, length):
            twiddle = 1.0 + 0.0j
            for offset in range(half):
                even = result[begin + offset]
                odd = result[begin + offset + half] * twiddle
                result[begin + offset] = even + odd
                result[begin + offset + half] = even - odd
                twiddle *= root
        length *= 2

    if inverse:
        return [value / count for value in result]
    return result


def generate_residual() -> list[float]:
    center = (TABLE_SIZE - 1) * 0.5
    impulse = []
    for index in range(TABLE_SIZE):
        time = (index - center) / PHASES_PER_SAMPLE
        sinc = 1.0 if time == 0.0 else math.sin(math.pi * time) / (math.pi * time)
        window = 0.42 - 0.5 * math.cos(2.0 * math.pi * index / (TABLE_SIZE - 1))
        window += 0.08 * math.cos(4.0 * math.pi * index / (TABLE_SIZE - 1))
        impulse.append(sinc * window / PHASES_PER_SAMPLE)

    impulse_sum = sum(impulse)
    impulse = [value / impulse_sum for value in impulse]
    spectrum = fft([complex(value) for value in impulse])
    log_magnitude = [complex(math.log(max(abs(value), 1.0e-16))) for value in spectrum]
    cepstrum = fft(log_magnitude, inverse=True)

    minimum_cepstrum = [0.0j] * TABLE_SIZE
    minimum_cepstrum[0] = complex(cepstrum[0].real)
    minimum_cepstrum[TABLE_SIZE // 2] = complex(cepstrum[TABLE_SIZE // 2].real)
    for index in range(1, TABLE_SIZE // 2):
        minimum_cepstrum[index] = complex(2.0 * cepstrum[index].real)

    minimum_spectrum = [cmath.exp(value) for value in fft(minimum_cepstrum)]
    minimum_impulse = [value.real for value in fft(minimum_spectrum, inverse=True)]
    minimum_sum = sum(minimum_impulse)
    minimum_impulse = [value / minimum_sum for value in minimum_impulse]

    accumulated = 0.0
    residual = []
    for value in minimum_impulse:
        accumulated += value
        residual.append(accumulated - 1.0)
    residual[-1] = 0.0
    residual.append(0.0)
    return residual


def float_hex(value: float) -> str:
    # Python/libm releases can differ in the last few double bits of cmath.exp.
    # Quantize to one part in ten thousand before narrowing so the checked-in table
    # is byte-reproducible across supported generator interpreters. The audio
    # regression below independently gates any effect of that quantization.
    version_stable = round(value, 4)
    narrowed = struct.unpack("!f", struct.pack("!f", version_stable))[0]
    if narrowed == 0.0:
        return "0.0f"
    return narrowed.hex() + "f"


def render_header(residual: list[float]) -> str:
    values = []
    for begin in range(0, len(residual), 4):
        row = ", ".join(float_hex(value) for value in residual[begin : begin + 4])
        values.append(f"    {row},")
    return f"""#pragma once

// Generated by tools/scripts/generate_minblep_table.py. The construction is
// independent: a Blackman-windowed sinc is converted to minimum phase through
// its real cepstrum, integrated, normalized to an exact unit endpoint, and
// stored as the residual from an already-applied step. Values are quantized to
// 1e-4 before float narrowing for byte stability across Python/libm versions.
// Method reference: Eli Brandt, "Hard Sync Without Aliasing", ICMC 2001,
// https://www.cs.cmu.edu/~eli/papers/icmc01-hardsync.pdf

#include <array>
#include <cstddef>

namespace pulp::signal::osc::detail {{

inline constexpr std::size_t kMinBlepKernelSamples = {KERNEL_SAMPLES};
inline constexpr std::size_t kMinBlepPhasesPerSample = {PHASES_PER_SAMPLE};
inline constexpr std::array<float, {len(residual)}> kMinBlepResidual = {{
{chr(10).join(values)}
}};

}} // namespace pulp::signal::osc::detail
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("core/signal/include/pulp/signal/osc/detail/minblep_table.hpp"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render_header(generate_residual())
    if args.check:
        if not args.output.exists() or args.output.read_text() != rendered:
            print(f"minBLEP table is stale: regenerate {args.output}", file=sys.stderr)
            return 1
        print(f"minBLEP table is reproducible: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
