#!/usr/bin/env bash
# gpu_ledger_merge_driver.sh — resolve a generated-ledger conflict to a value
# that is invalid on purpose, so it cannot be committed quietly.
#
# docs/status/gpu-vellum-handoff.yaml and its receipt are generated by
# gpu_handoff_provenance.py and pin blob/tree identities for ~100 rows against
# one exact commit. They are regenerated whenever main moves, so every
# long-lived branch collides on them: 113 of the last ~3,100 commits on main
# exist only to re-pin after a merge.
#
# A driver that *computed* a merged value would emit a stale-but-plausible pin
# and git would commit it silently; merge=ours has the same property, because a
# stale-but-ancestral pin still passes the always-on provenance tier. So this
# driver deliberately produces a value no tier accepts: "regenerate-me" fails
# the 40-hex identity check in gpu_recipe_catalog.validate_handoff and the
# blob comparison in validate_handoff_routing, and gates.sh greps for it before
# the push. The merge stops being a hand-resolved conflict and becomes one
# mechanical regeneration, with no way to skip it unnoticed.
#
# Two fields carry the lie, one per file: the ledger's "object_id" pins, and
# the receipt's "handoff_sha256", which binds the receipt to the exact ledger
# bytes and is the only receipt field that could otherwise merge to a
# plausible-looking stale digest. Null object_ids are the ledger's "this Vellum
# path does not exist yet" contract and must survive untouched, which the
# quoted-value match already guarantees.
#
# Git calls this from the top of the working tree for merge, rebase,
# cherry-pick and stash alike, so all four paths get the same resolution.
# $1 is %A (ours; also the output file), $2 is %B (theirs).
set -euo pipefail
sed -E 's/("(object_id|handoff_sha256)"[[:space:]]*:[[:space:]]*)"[^"]*"/\1"regenerate-me"/g' "$2" > "$1"
