#!/usr/bin/env bash
# gpu_ledger_merge_driver.sh — resolve a generated-ledger conflict to a value
# that is invalid on purpose, so it cannot be committed quietly.
#
# docs/status/gpu-vellum-handoff.yaml and its receipt are generated by
# gpu_handoff_provenance.py and pin blob/tree identities for ~100 rows against
# one exact commit. They are regenerated whenever main moves, so every
# long-lived branch collides on them: 113 of the last ~3,100 commits on main
# exist only to re-pin after a merge.
#
# A driver that *computed* a merged value would emit a stale-but-plausible pin
# and git would commit it silently; merge=ours has the same property, because a
# stale-but-ancestral pin still passes the always-on provenance tier. So this
# driver deliberately produces a value no tier accepts: "regenerate-me" fails
# the 40-hex identity check in gpu_recipe_catalog.validate_handoff and the blob
# comparison in validate_handoff_routing, and gpu_ledger_sentinel_check.py
# rejects it from the pre-push hook before it can reach CI. The merge stops
# being a hand-resolved conflict and becomes one mechanical regeneration, with
# no way to skip it unnoticed.
#
# Poison ONLY what `write` can regenerate. That is the pulp_paths identities --
# derived from this repository's own history -- plus the receipt's
# handoff_sha256, which binds the receipt to exact ledger bytes and is
# otherwise the one receipt field that could merge to a plausible stale digest.
# vellum_paths rows are CONSTANTS pinned to a fixed foreign revision and are
# validated against a hardcoded table, so the generator does not rewrite them:
# poisoning one produces damage no repair command can undo. The rows are told
# apart by the "repo" key, which the serializer emits first in every row. Null
# object_ids encode "this Vellum path does not exist yet" and the quoted-value
# match already leaves them alone.
#
# Git calls this from the top of the working tree for merge, rebase,
# cherry-pick and stash alike, so all four paths get the same resolution.
# $1 is %A (ours; also the output file), $2 is %B (theirs).
set -euo pipefail
awk '
  /"repo": "Generous-Corp\/pulp"/    { pulp = 1 }
  /"repo": "Generous-Corp\/vellum"/  { pulp = 0 }
  pulp && /"object_id": "/           { sub(/"object_id": "[^"]*"/, "\"object_id\": \"regenerate-me\""); pulp = 0 }
  /"handoff_sha256": "/              { sub(/"handoff_sha256": "[^"]*"/, "\"handoff_sha256\": \"regenerate-me\"") }
  { print }
' "$2" > "$1"
