#!/usr/bin/env python3
"""Assert that every required gate actually ran for an exact merged commit."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


INCIDENT_TITLE = "Required gate liveness: checks missing from merged commit"


class LivenessError(RuntimeError):
    pass


@dataclass(frozen=True)
class Finding:
    context: str
    reason: str


def required_contexts(path: Path) -> tuple[str, ...]:
    doc = json.loads(path.read_text(encoding="utf-8"))
    contexts: list[str] = []
    for rule in doc.get("rules", []):
        if rule.get("type") != "required_status_checks":
            continue
        for check in rule.get("parameters", {}).get("required_status_checks", []):
            context = check.get("context")
            if context and context not in contexts:
                contexts.append(context)
    if not contexts:
        raise LivenessError(f"{path}: required-check contract is empty")
    return tuple(contexts)


def evaluate(required: Sequence[str], check_runs: Sequence[dict]) -> list[Finding]:
    findings: list[Finding] = []
    for context in required:
        matches = [run for run in check_runs if run.get("name") == context]
        if not matches:
            findings.append(Finding(context, "missing: no check-run with this name exists on the target SHA"))
            continue
        # A push may create a skipped duplicate of a required merge-group
        # check on the same SHA (for example, the cache-warming Build and Test
        # workflow deliberately skips its `macos` alias on push). A skipped
        # duplicate did not execute the gate and must not shadow a real run.
        # If every matching run skipped, keep the newest one so the gate still
        # fails closed.
        executed = [run for run in matches if run.get("conclusion") != "skipped"]
        candidates = executed or matches

        # A rerun creates a new check-run with a larger ID. Among runs that
        # actually executed, an old green must never mask the latest
        # failed/pending rerun on the same SHA.
        latest = max(
            enumerate(candidates),
            key=lambda item: (int(item[1].get("id") or 0), item[0]),
        )[1]
        if latest.get("status") == "completed" and latest.get("conclusion") == "success":
            continue
        state = (
            f"{latest.get('status', '<missing>')}/"
            f"{latest.get('conclusion') or '<none>'}"
        )
        findings.append(Finding(context, "latest run did not complete successfully: " + state))
    return findings


def gh_json(args: Sequence[str]) -> object:
    result = subprocess.run(["gh", *args], capture_output=True, text=True, check=True)
    return json.loads(result.stdout) if result.stdout.strip() else []


def fetch_check_runs(repo: str, sha: str) -> list[dict]:
    pages = gh_json(
        [
            "api",
            "--paginate",
            "--slurp",
            "-H",
            "Accept: application/vnd.github+json",
            f"repos/{repo}/commits/{sha}/check-runs?per_page=100",
        ]
    )
    return [run for page in pages for run in page.get("check_runs", [])]


def find_open_incident(repo: str) -> dict | None:
    pages = gh_json(
        [
            "api",
            "--paginate",
            "--slurp",
            f"repos/{repo}/issues?state=open&per_page=100",
        ]
    )
    return next(
        (
            issue
            for page in pages
            for issue in page
            if "pull_request" not in issue and issue.get("title") == INCIDENT_TITLE
        ),
        None,
    )


def open_incident(repo: str, sha: str, findings: Sequence[Finding]) -> None:
    match = find_open_incident(repo)
    lines = [
        f"Required-check coverage failed for merged commit `{sha}`.",
        "",
        "The check names come from `.github/rulesets/main-protection.json`; each must have a",
        "completed successful check-run bound to this exact SHA.",
        "",
    ]
    lines.extend(f"- `{finding.context}`: {finding.reason}" for finding in findings)
    lines.extend(
        [
            "",
            "A missing check usually means a workflow/path filter stopped matching or a job/check",
            "was renamed without updating the required-check contract.",
            "",
            "_Auto-generated by `.github/workflows/required-gate-liveness.yml`._",
        ]
    )
    body = "\n".join(lines)
    if match:
        subprocess.run(
            ["gh", "api", f"repos/{repo}/issues/{match['number']}", "-X", "PATCH", "-f", f"body={body}"],
            check=True,
        )
    else:
        subprocess.run(
            ["gh", "api", f"repos/{repo}/issues", "-f", f"title={INCIDENT_TITLE}", "-f", f"body={body}"],
            check=True,
        )


def close_incident(repo: str, sha: str) -> None:
    match = find_open_incident(repo)
    if not match:
        return
    subprocess.run(
        [
            "gh",
            "api",
            f"repos/{repo}/issues/{match['number']}/comments",
            "-f",
            f"body=All required gates ran successfully for `{sha}`; closing.",
        ],
        check=True,
    )
    subprocess.run(
        ["gh", "api", f"repos/{repo}/issues/{match['number']}", "-X", "PATCH", "-f", "state=closed"],
        check=True,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ruleset", type=Path, default=Path(".github/rulesets/main-protection.json"))
    parser.add_argument("--repo", default=os.environ.get("REPO"))
    parser.add_argument("--sha", default=os.environ.get("TARGET_SHA"))
    parser.add_argument("--attempts", type=int, default=12)
    parser.add_argument("--interval-seconds", type=float, default=10.0)
    parser.add_argument("--no-issue", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not args.repo or not args.sha:
        print("FAIL: --repo/REPO and --sha/TARGET_SHA are required", file=sys.stderr)
        return 2
    try:
        required = required_contexts(args.ruleset)
        findings: list[Finding] = []
        for attempt in range(1, args.attempts + 1):
            runs = fetch_check_runs(args.repo, args.sha)
            findings = evaluate(required, runs)
            if not findings:
                if not args.no_issue:
                    close_incident(args.repo, args.sha)
                print(f"OK: {len(required)} required gates ran successfully for {args.sha}")
                return 0
            if attempt < args.attempts:
                print(f"Attempt {attempt}/{args.attempts}: required gates not complete; retrying")
                time.sleep(args.interval_seconds)
        if not args.no_issue:
            open_incident(args.repo, args.sha, findings)
        for finding in findings:
            print(f"FAIL: {finding.context}: {finding.reason}", file=sys.stderr)
        return 1
    except (LivenessError, OSError, json.JSONDecodeError, subprocess.CalledProcessError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
