#!/usr/bin/env python3
"""Schema-drift gate for the timeline schema registry.

Regenerates the timeline schema manifest from the built-in registry (via the
`pulp-timeline-schema-emit` binary) and asserts it is byte-identical to the
committed artifact. Any divergence is drift: the registry changed without the
generated artifact being regenerated, or the artifact was hand-edited.

    schema_drift_check.py                 # check committed artifact (CI gate)
    schema_drift_check.py --update        # regenerate committed artifact
    schema_drift_check.py --emit-cmd '<argv>'   # override the generator command

Exit codes:
    0  in sync (or artifact successfully updated)
    1  drift detected (committed artifact does not match freshly generated bytes)
    2  operational error (generator missing, unreadable artifact, bad usage)

This script is standalone and has no third-party dependencies. It is wired into
the timeline test suite as the `timeline-schema-drift` ctest (see
test/cmake/timeline_tests.cmake), so a normal `ctest` run enforces the gate.
Wiring it into a GitHub workflow as a standalone required check is separate and
owned by the CI layer.
"""

from __future__ import annotations

import argparse
import difflib
import os
import shlex
import subprocess
import sys
from pathlib import Path

# Repo-relative defaults, resolved from this file's location
# (<repo>/tools/scripts/schema_drift_check.py). Gate scripts live under
# tools/scripts/ repo-wide; the subsystem-local generator binary it drives lives
# under core/timeline/tools/.
_THIS = Path(__file__).resolve()
_REPO_ROOT = _THIS.parents[2]
DEFAULT_ARTIFACT = _REPO_ROOT / "core" / "timeline" / "schema" / "timeline_schema.json"


def _default_emit_candidates() -> list[Path]:
    """Likely locations of the built generator binary, most specific first."""
    name = "pulp-timeline-schema-emit"
    return [
        _REPO_ROOT / "build" / "core" / "timeline" / name,
        _REPO_ROOT / "build" / name,
        _REPO_ROOT / "build" / "bin" / name,
    ]


def _resolve_emit_cmd(explicit: str | None) -> list[str]:
    if explicit:
        return shlex.split(explicit)
    env = os.environ.get("PULP_SCHEMA_EMIT_CMD")
    if env:
        return shlex.split(env)
    for candidate in _default_emit_candidates():
        if candidate.exists() and os.access(candidate, os.X_OK):
            return [str(candidate)]
    raise FileNotFoundError(
        "pulp-timeline-schema-emit not found; build it or pass --emit-cmd. "
        "Looked in: " + ", ".join(str(p) for p in _default_emit_candidates())
    )


def _generate(emit_cmd: list[str]) -> bytes:
    proc = subprocess.run(emit_cmd, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError(
            f"generator {emit_cmd!r} exited {proc.returncode}: "
            f"{proc.stderr.decode('utf-8', 'replace')}"
        )
    return proc.stdout


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--artifact",
        type=Path,
        default=DEFAULT_ARTIFACT,
        help="path to the committed schema artifact",
    )
    parser.add_argument(
        "--emit-cmd",
        default=None,
        help="command (argv string) that prints the freshly generated schema",
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="regenerate the committed artifact instead of checking it",
    )
    args = parser.parse_args(argv)

    try:
        emit_cmd = _resolve_emit_cmd(args.emit_cmd)
        generated = _generate(emit_cmd)
    except (FileNotFoundError, RuntimeError) as exc:
        print(f"schema-drift-check: {exc}", file=sys.stderr)
        return 2

    if args.update:
        args.artifact.parent.mkdir(parents=True, exist_ok=True)
        args.artifact.write_bytes(generated)
        print(f"schema-drift-check: wrote {args.artifact}", file=sys.stderr)
        return 0

    if not args.artifact.exists():
        print(
            f"schema-drift-check: committed artifact missing: {args.artifact}\n"
            "  run with --update to create it",
            file=sys.stderr,
        )
        return 1

    committed = args.artifact.read_bytes()
    if committed == generated:
        return 0

    # Drift: show a readable diff to make the fix obvious.
    committed_lines = committed.decode("utf-8", "replace").splitlines(keepends=True)
    generated_lines = generated.decode("utf-8", "replace").splitlines(keepends=True)
    diff = difflib.unified_diff(
        committed_lines,
        generated_lines,
        fromfile=f"committed:{args.artifact}",
        tofile="generated",
    )
    sys.stderr.write(
        "schema-drift-check: DRIFT — committed artifact does not match the "
        "registry.\n  Regenerate with: schema_drift_check.py --update\n"
    )
    sys.stderr.writelines(diff)
    if not committed_lines or not generated_lines:
        sys.stderr.write(
            f"\n  (committed {len(committed)} bytes vs generated {len(generated)} bytes)\n"
        )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
