#!/usr/bin/env python3
"""Unit tests for reap_stranded_tracker.{parse_body,decide}.

Guards the SHA-keyed "release: stuck" auto-close logic used by
.github/workflows/watchdog-reaper.yml. Run with:

    python3 -m pytest tools/scripts/test_reap_stranded_tracker.py -v

or without pytest:

    python3 tools/scripts/test_reap_stranded_tracker.py
"""

from __future__ import annotations

import importlib.util
import pathlib
import unittest

SCRIPT = pathlib.Path(__file__).parent / "reap_stranded_tracker.py"

spec = importlib.util.spec_from_file_location("reap_stranded_tracker", SCRIPT)
rst = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(rst)


# A faithful sample of the body auto-release.yml's stranded detector writes.
FULL_SHA = "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678"
SAMPLE_BODY = f"""_Auto-generated by `.github/workflows/auto-release.yml` on 2026-07-15 12:00 UTC._

**Symptom:** A user-facing fix/feat merged to `main` without a bump.

**Tip commit:** `{FULL_SHA}`
**Analyzed range:** `deadbeefdeadbeefdeadbeefdeadbeefdeadbeef..{FULL_SHA}`
**PR:** #4242
**Subject:** `fix(view): correct caret stroke`
**Live release signal:** `fix(view): correct caret stroke`
**Uncovered surfaces:** `sdk,plugin`
**Recovery levels:** `sdk=patch,plugin=patch`

**Resolution:**
"""


class ParseBodyTests(unittest.TestCase):
    def test_extracts_full_sha_and_surfaces(self):
        tip, surfaces = rst.parse_body(SAMPLE_BODY)
        self.assertEqual(tip, FULL_SHA)
        self.assertEqual(surfaces, ["sdk", "plugin"])

    def test_single_surface(self):
        body = SAMPLE_BODY.replace("`sdk,plugin`", "`sdk`")
        tip, surfaces = rst.parse_body(body)
        self.assertEqual(tip, FULL_SHA)
        self.assertEqual(surfaces, ["sdk"])

    def test_sha_lowercased(self):
        body = SAMPLE_BODY.replace(FULL_SHA, FULL_SHA.upper())
        tip, _ = rst.parse_body(body)
        self.assertEqual(tip, FULL_SHA)

    def test_missing_fields_return_empty(self):
        tip, surfaces = rst.parse_body("no machine-readable fields here")
        self.assertEqual(tip, "")
        self.assertEqual(surfaces, [])

    def test_empty_body(self):
        self.assertEqual(rst.parse_body(""), ("", []))


class DecideTests(unittest.TestCase):
    def test_all_surfaces_shipped_closes(self):
        close, reason = rst.decide(
            FULL_SHA,
            ["sdk", "plugin"],
            ["v0.80.1", "plugin-v0.42.0", "v0.80.0"],
        )
        self.assertTrue(close)
        self.assertIn("v0.80.1", reason)
        self.assertIn("plugin-v0.42.0", reason)

    def test_sdk_shipped_but_plugin_not_keeps_open(self):
        # Only an SDK tag contains the commit; the plugin surface is still
        # stranded — must NOT close.
        close, reason = rst.decide(FULL_SHA, ["sdk", "plugin"], ["v0.80.1"])
        self.assertFalse(close)
        self.assertIn("plugin", reason)

    def test_plugin_tag_does_not_satisfy_sdk_surface(self):
        # A plugin-v* tag must not be mistaken for an SDK (v*) release.
        close, _ = rst.decide(FULL_SHA, ["sdk"], ["plugin-v0.42.0"])
        self.assertFalse(close)

    def test_sdk_tag_does_not_satisfy_plugin_surface(self):
        close, _ = rst.decide(FULL_SHA, ["plugin"], ["v0.80.1"])
        self.assertFalse(close)

    def test_single_surface_shipped_closes(self):
        close, reason = rst.decide(FULL_SHA, ["sdk"], ["v0.80.1"])
        self.assertTrue(close)
        self.assertIn("v0.80.1", reason)

    def test_no_containing_tags_keeps_open(self):
        close, _ = rst.decide(FULL_SHA, ["sdk", "plugin"], [])
        self.assertFalse(close)

    def test_empty_tip_never_closes(self):
        close, _ = rst.decide("", ["sdk"], ["v0.80.1"])
        self.assertFalse(close)

    def test_empty_surfaces_never_closes(self):
        # A parse miss on surfaces must fail safe: an empty surface list with
        # containing tags present must NOT be read as "all surfaces covered".
        close, _ = rst.decide(FULL_SHA, [], ["v0.80.1", "plugin-v0.42.0"])
        self.assertFalse(close)

    def test_unknown_surface_never_closes(self):
        close, reason = rst.decide(FULL_SHA, ["docs"], ["v0.80.1"])
        self.assertFalse(close)
        self.assertIn("docs", reason)

    def test_unknown_surface_alongside_known_never_closes(self):
        close, _ = rst.decide(
            FULL_SHA, ["sdk", "docs"], ["v0.80.1", "plugin-v0.42.0"]
        )
        self.assertFalse(close)

    def test_plugin_prefix_not_matched_by_sdk_pattern_substring(self):
        # Regression guard: ensure the sdk pattern is anchored so that it does
        # not match inside "plugin-v...". Only plugin tags present, sdk surface.
        close, _ = rst.decide(FULL_SHA, ["sdk"], ["plugin-v1.2.3"])
        self.assertFalse(close)


if __name__ == "__main__":
    unittest.main()
