#include "forge/process_engine.hpp"

#include <array>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <sstream>

namespace forge_modular {

namespace {

/// Quote one argument for /bin/sh. Single quotes with the close-escape-reopen
/// dance, so a prompt containing a quote, a semicolon or a backtick is text
/// rather than shell.
std::string shell_quote(const std::string& s) {
    std::string out = "'";
    for (char c : s) {
        if (c == '\'') out += "'\\''";
        else out += c;
    }
    out += "'";
    return out;
}

}  // namespace

ProcessEngine::ProcessEngine(std::string tools_dir, std::string log_path)
    : tools_dir_(std::move(tools_dir)), log_path_(std::move(log_path)) {}

int ProcessEngine::run(const std::string& command, std::string& output) {
    output.clear();
    std::FILE* pipe = ::popen(command.c_str(), "r");
    if (!pipe) return -1;
    std::array<char, 4096> buffer{};
    while (std::fgets(buffer.data(), static_cast<int>(buffer.size()), pipe))
        output += buffer.data();
    const int status = ::pclose(pipe);
    return status == -1 ? -1 : WEXITSTATUS(status);
}

bool ProcessEngine::available() const {
    namespace fs = std::filesystem;
    std::error_code ec;
    return fs::exists(fs::path(tools_dir_) / "generate.py", ec) &&
           fs::exists(fs::path(tools_dir_) / "patch.py", ec);
}

bool ProcessEngine::ensure_running() {
    error_.clear();
    if (!available()) {
        error_ = "the generator is not installed";
        return false;
    }
    // Prove the interpreter runs before promising a build. Discovering a
    // missing python3 minutes in, from a log nobody opened, is how a refusal
    // reads as a hang.
    std::string out;
    if (run("python3 -c 'pass' 2>&1", out) != 0) {
        error_ = "python3 is not available on this machine";
        return false;
    }
    return true;
}

void ProcessEngine::submit(const std::string& prompt, bool patch_mode) {
    error_.clear();
    artifact_.clear();

    // The same two tools the command line drives. If the app generated by a
    // different route, only one of the two would ever be the tested one.
    const std::string tool = patch_mode ? "patch.py" : "generate.py";
    const std::string verb = patch_mode ? " build " : " ";

    std::ostringstream cmd;
    cmd << "cd " << shell_quote(tools_dir_) << " && "
        << "python3 " << tool << verb << shell_quote(prompt)
        // Truncate: BuildMonitor treats a shrinking file as a new run, so the
        // transcript starts clean rather than replaying the previous build.
        << " > " << shell_quote(log_path_) << " 2>&1 &";
    std::string out;
    // Detached: a generation lasts minutes and must not block the UI thread.
    run(cmd.str(), out);
}

std::string ProcessEngine::explain(const std::string& patch_path) const {
    namespace fs = std::filesystem;
    std::error_code ec;
    if (!fs::exists(patch_path, ec))
        return "There is no patch open to explain yet.";

    std::ostringstream cmd;
    cmd << "cd " << shell_quote(tools_dir_) << " && "
        << "python3 patch.py explain " << shell_quote(patch_path) << " 2>&1";
    std::string out;
    if (run(cmd.str(), out) != 0 || out.empty())
        return "I could not read that patch.";
    return out;
}

}  // namespace forge_modular
