#pragma once

// The generator, as a child process.
//
// The shell hands over a prompt and reads what comes back; the actual work runs
// in the Python toolchain that also backs the command line. One engine, two
// entry points -- if the app and the CLI generated by different routes, only
// one of them would ever be the tested one.
//
// Output goes to a log file rather than a pipe. A generation lasts minutes and
// outlives any single UI tick, the transcript has to survive the window being
// closed and reopened, and a file is what BuildMonitor already tails.

#include "forge/modular_shell.hpp"

#include <atomic>
#include <functional>
#include <memory>
#include <string>
#include <vector>

namespace forge_modular {

class ProcessEngine final : public EngineClient {
public:
    /// `tools_dir` holds generate.py and patch.py. `log_path` is where the
    /// FIRST run's output lands and what the shell tails until a build starts;
    /// each submit then picks its own file in `log_path`'s directory, under
    /// `runs/`. Passing an empty `log_path` keeps a fixed path (tests that
    /// hand-write a log rely on the path not moving under them).
    ProcessEngine(std::string tools_dir, std::string log_path);
    ~ProcessEngine() override;

    bool available() const override;
    bool ensure_running() override;
    void submit(const std::string& prompt, bool patch_mode,
                const forge::ModelSelection& model) override;
    void cancel_generation() override;
    std::string last_error() const override { return error_; }

    /// Answer a question about a patch from the patch itself.
    ///
    /// Derived from the file and the local inventory, with no model involved:
    /// it costs nothing to re-render, and an explanation computed from the file
    /// cannot claim a cable that is not in it. That property is worth more here
    /// than fluency -- a confident answer about a connection that does not
    /// exist is worse than no answer.
    std::string explain(const std::string& patch_path) const override;

    /// Same, off the UI thread. `done` is called with the answer on a worker,
    /// so the caller must marshal it back before touching any view. The
    /// synchronous form loads the whole module inventory and takes seconds --
    /// long enough to read as a hang.
    void explain_async(const std::string& patch_path,
                       std::function<void(std::string)> done) const override;

    /// Where the most recent run put its artifact, or empty.
    std::string last_artifact() const { return artifact_; }

    /// The log the CURRENT run is writing, which changes with every submit.
    ///
    /// Every run used to redirect into one `last-run.log`. Two generations
    /// overlapping — a second Build pressed while the first was still going,
    /// or a run left over from a previous launch of the app — then wrote over
    /// each other from offset zero, and the file the app reads for the
    /// outcome, the stage AND the artifact path became a mixture of both. It
    /// happened: two patches finished six seconds apart, the explanation on
    /// screen described one patch while the file named the other, and Rack
    /// opened something the user had not asked for. One file per run makes
    /// that impossible rather than unlikely.
    std::string log_path() const override { return log_path_; }

    /// True when a generator process is running RIGHT NOW, whoever started it.
    ///
    /// Distinct from the shell's `busy()`, which only knows about runs this
    /// editor has watched. The processor-owned child outlives an editor window
    /// but is cancelled when the processor/app itself is destroyed.
    bool generator_running() const override;
    bool try_claim_generation() override;
    void release_generation_claim() override;

    /// Run a tool and collect its output. Public so a test can drive the same
    /// path the app does rather than a private shortcut.
    ///
    /// Takes a SHELL command, and that is the thing to move away from: it
    /// pins the app to a POSIX shell, and every caller has to quote its own
    /// arguments correctly or a prompt containing a quote becomes syntax.
    /// Prefer `run_tool` for anything that is really "an executable and some
    /// arguments". What is left here is the cases that genuinely use the
    /// shell — backgrounding a long run, and asking whether a process exists
    /// — each of which needs a capability Pulp core does not expose yet.
    static int run(const std::string& command, std::string& output);

    /// Run an executable with arguments, with no shell involved.
    ///
    /// `pulp::platform::ChildProcess` takes an argv vector straight to
    /// posix_spawn or CreateProcess, so there is no quoting step to get wrong
    /// and no shell to be portable to. A prompt with a quote, a semicolon or a
    /// backtick in it is an argument, not syntax, because it never passes
    /// through a parser that could read it as syntax.
    static int run_tool(const std::string& executable,
                        const std::vector<std::string>& args,
                        std::string& output,
                        const std::string& working_dir = {});

private:
    struct RunState;
    static void append_terminal(const std::shared_ptr<RunState>& state,
                                const std::string& line);
    static void cancel_run(const std::shared_ptr<RunState>& state,
                           bool mark_inactive_cancelled);
    std::string tools_dir_;
    std::string log_path_;
    /// Directory the per-run logs go in; empty pins log_path_ where it is.
    std::string log_base_;
    std::string error_;
    std::string artifact_;
    // Probing the toolchain touches a filesystem that may be removable,
    // network-backed, or TCC-gated -- any of which can block for seconds. Doing
    // that on the UI thread is what made the app appear to freeze, so each
    // probe runs once and the answer is remembered.
    mutable std::atomic<int> available_{-1};   // -1 unknown, 0 no, 1 yes
    std::atomic<int> python_ok_{-1};
    std::atomic<bool> claimed_by_this_{false};
    std::shared_ptr<RunState> run_state_;
};

}  // namespace forge_modular
