#pragma once

// The generator, as a child process.
//
// The shell hands over a prompt and reads what comes back; the actual work runs
// in the Python toolchain that also backs the command line. One engine, two
// entry points -- if the app and the CLI generated by different routes, only
// one of them would ever be the tested one.
//
// Output goes to a log file rather than a pipe. A generation lasts minutes and
// outlives any single UI tick, the transcript has to survive the window being
// closed and reopened, and a file is what BuildMonitor already tails.

#include "forge/modular_shell.hpp"

#include <atomic>
#include <functional>
#include <string>

namespace forge_modular {

class ProcessEngine final : public EngineClient {
public:
    /// `tools_dir` holds generate.py and patch.py. `log_path` is where a run's
    /// output lands, and what the shell tails.
    ProcessEngine(std::string tools_dir, std::string log_path);

    bool available() const override;
    bool ensure_running() override;
    void submit(const std::string& prompt, bool patch_mode) override;
    std::string last_error() const override { return error_; }

    /// Answer a question about a patch from the patch itself.
    ///
    /// Derived from the file and the local inventory, with no model involved:
    /// it costs nothing to re-render, and an explanation computed from the file
    /// cannot claim a cable that is not in it. That property is worth more here
    /// than fluency -- a confident answer about a connection that does not
    /// exist is worse than no answer.
    std::string explain(const std::string& patch_path) const;

    /// Same, off the UI thread. `done` is called with the answer on a worker,
    /// so the caller must marshal it back before touching any view. The
    /// synchronous form loads the whole module inventory and takes seconds --
    /// long enough to read as a hang.
    void explain_async(const std::string& patch_path,
                       std::function<void(std::string)> done) const;

    /// Where the most recent run put its artifact, or empty.
    std::string last_artifact() const { return artifact_; }

    const std::string& log_path() const { return log_path_; }

    /// Run a tool and collect its output. Public so a test can drive the same
    /// path the app does rather than a private shortcut.
    static int run(const std::string& command, std::string& output);

private:
    std::string tools_dir_;
    std::string log_path_;
    std::string error_;
    std::string artifact_;
    // Probing the toolchain touches a filesystem that may be removable,
    // network-backed, or TCC-gated -- any of which can block for seconds. Doing
    // that on the UI thread is what made the app appear to freeze, so each
    // probe runs once and the answer is remembered.
    mutable std::atomic<int> available_{-1};   // -1 unknown, 0 no, 1 yes
    std::atomic<int> python_ok_{-1};
};

}  // namespace forge_modular
