#pragma once

/// @file safe_path.hpp
/// Path admission. A capsule path is data from an untrusted machine, so it is
/// normalized and checked before it is ever joined to a real directory.

#include <pulp/authoring_capsule/limits.hpp>
#include <pulp/authoring_capsule/status.hpp>
#include <pulp/runtime/result.hpp>

#include <string>
#include <string_view>
#include <vector>

namespace pulp::authoring_capsule {

/// Verify a member path and return it unchanged. It does not rewrite bytes
/// toward NFC: with no Unicode character database linked, the only sound
/// options are *prove already-NFC* or *reject*, and quietly returning a
/// half-normalized path would be worse than either. A path this cannot prove
/// is NFC is rejected.
///
/// Also rejects absolute paths, drive letters, UNC prefixes, any `.` or `..`
/// component, leading or trailing separators, empty components, backslashes,
/// NUL and C0 controls, trailing dots or spaces, and anything past the depth
/// or byte budget.
///
/// The accepted subset is narrow, which is affordable because a member path is
/// generated by the exporter and is never the user's filename — a sample is
/// content-addressed and the author's chosen name travels as metadata, where
/// arbitrary text is fine.
runtime::Result<std::string, CapsuleError>
admit_member_path(std::string_view raw, const CapsuleLimits& limits = kCapsuleLimitsV1);

/// Fold a normalized path to the key used for collision detection: ASCII
/// case-folded, NFC, with confusable characters mapped to a representative.
/// Two members whose keys match are a collision even when their bytes differ —
/// on a case-insensitive filesystem one would silently overwrite the other.
std::string collision_key(std::string_view normalized_path);

/// Detect a collision across a member set. Returns the first offending pair.
runtime::Result<void, CapsuleError> check_collisions(const std::vector<std::string>& normalized);

}  // namespace pulp::authoring_capsule
