// Real module geometry, measured from a running VCV Rack.
// Generated by tools/rack/export_design_data.py — do not hand-edit.
// hp and px are true; port x is a fraction of panel width, y is px
// from the panel top; name is the vendor's own name for the port.
const MODS = [
  {slug:'Core/AudioInterface2', hp:5, px:75.0, img:true, placed:true,
   ports:[['To "device output 1"',0.2868,286.0,'in',0], ['To "device output 2"',0.7135,286.0,'in',1], ['From "device input 1"',0.2868,334.0,'out',0], ['From "device input 2"',0.7135,334.0,'out',1]]},
  {slug:'Core/CV-Gate', hp:10, px:150.0, img:true, placed:true,
   ports:[['Cell 1',0.1612,231.6,'in',0], ['Cell 2',0.3886,231.6,'in',1], ['Cell 3',0.6159,231.6,'in',2], ['Cell 4',0.8433,231.6,'in',3], ['Cell 5',0.1612,265.6,'in',4], ['Cell 6',0.3886,265.6,'in',5], ['Cell 7',0.6159,265.6,'in',6], ['Cell 8',0.8433,265.6,'in',7], ['Cell 9',0.1612,299.6,'in',8], ['Cell 10',0.3886,299.6,'in',9], ['Cell 11',0.6159,299.6,'in',10], ['Cell 12',0.8433,299.6,'in',11], ['Cell 13',0.1612,333.7,'in',12], ['Cell 14',0.3886,333.6,'in',13], ['Cell 15',0.6159,333.6,'in',14], ['Cell 16',0.8433,333.6,'in',15]]},
  {slug:'Core/MIDIToCVInterface', hp:8, px:120.0, img:true, placed:true,
   ports:[['1V/octave pitch',0.1945,190.0,'out',0], ['Gate',0.4982,190.0,'out',1], ['Velocity',0.8019,190.0,'out',2], ['Aftertouch',0.1945,238.0,'out',3], ['Pitch wheel',0.4982,238.0,'out',4], ['Mod wheel',0.8019,238.0,'out',5], ['Retrigger',0.8019,286.0,'out',6], ['Clock',0.1945,286.0,'out',7], ['Clock divider',0.4982,285.6,'out',8], ['Start trigger',0.1945,334.0,'out',9], ['Stop trigger',0.4982,334.0,'out',10], ['Continue trigger',0.8019,333.6,'out',11]]},
  {slug:'ForgeModular/CARTOG', hp:4, px:60.0, img:false, placed:false,
   ports:[]},
  {slug:'Fundamental/ADSR', hp:9, px:135.0, img:true, placed:true,
   ports:[['Attack',0.1444,286.1,'in',0], ['Decay',0.3815,286.0,'in',1], ['Sustain',0.6185,286.1,'in',2], ['Release',0.8556,286.1,'in',3], ['Gate',0.3815,334.0,'in',4], ['Retrigger',0.6185,334.0,'in',5], ['Envelope',0.8556,334.0,'out',0]]},
  {slug:'Fundamental/Delay', hp:9, px:135.0, img:true, placed:true,
   ports:[['Time',0.1445,286.0,'in',0], ['Feedback',0.3815,286.0,'in',1], ['Tone',0.6185,285.9,'in',2], ['Mix',0.8555,285.9,'in',3], ['Audio',0.1445,334.0,'in',4], ['Clock',0.3815,334.0,'in',5], ['Mix',0.8555,334.0,'out',0], ['Wet',0.6185,334.0,'out',1]]},
  {slug:'Fundamental/LFO', hp:9, px:135.0, img:true, placed:true,
   ports:[['Frequency modulation',0.1444,286.0,'in',0], ['Reset',0.6185,285.9,'in',2], ['Pulse width modulation',0.8556,285.9,'in',3], ['Clock',0.3815,286.0,'in',4], ['Sine',0.1444,334.0,'out',0], ['Triangle',0.3815,334.0,'out',1], ['Sawtooth',0.6185,334.0,'out',2], ['Square',0.8556,334.0,'out',3]]},
  {slug:'Fundamental/Merge', hp:5, px:75.0, img:true, placed:true,
   ports:[['Channel 1',0.2867,124.0,'in',0], ['Channel 2',0.2867,154.0,'in',1], ['Channel 3',0.2867,184.0,'in',2], ['Channel 4',0.2867,214.0,'in',3], ['Channel 5',0.2867,244.0,'in',4], ['Channel 6',0.2867,274.0,'in',5], ['Channel 7',0.2867,304.0,'in',6], ['Channel 8',0.2867,334.0,'in',7], ['Channel 9',0.7133,124.0,'in',8], ['Channel 10',0.7133,154.0,'in',9], ['Channel 11',0.7133,184.0,'in',10], ['Channel 12',0.7133,214.0,'in',11], ['Channel 13',0.7133,244.0,'in',12], ['Channel 14',0.7133,274.0,'in',13], ['Channel 15',0.7133,304.0,'in',14], ['Channel 16',0.7133,334.0,'in',15], ['Polyphonic',0.2867,64.9,'out',0]]},
  {slug:'Fundamental/Mixer', hp:3, px:45.0, img:true, placed:true,
   ports:[['Channel 1',0.5,136.0,'in',0], ['Channel 2',0.5,166.0,'in',1], ['Channel 3',0.5,196.0,'in',2], ['Channel 4',0.5,226.0,'in',3], ['Channel 5',0.5,256.0,'in',4], ['Channel 6',0.5,286.0,'in',5], ['Mix',0.5,334.0,'out',0]]},
  {slug:'Fundamental/Mutes', hp:8, px:120.0, img:true, placed:true,
   ports:[['Row 1',0.1794,64.9,'in',0], ['Row 2',0.1794,94.8,'in',1], ['Row 3',0.1794,124.7,'in',2], ['Row 4',0.1794,154.6,'in',3], ['Row 5',0.1794,184.5,'in',4], ['Row 6',0.1794,214.4,'in',5], ['Row 7',0.1794,244.3,'in',6], ['Row 8',0.1794,274.2,'in',7], ['Row 9',0.1794,304.1,'in',8], ['Row 10',0.1794,334.0,'in',9], ['Row 1',0.8202,64.9,'out',0], ['Row 2',0.8202,94.8,'out',1], ['Row 3',0.8202,124.7,'out',2], ['Row 4',0.8202,154.6,'out',3], ['Row 5',0.8202,184.5,'out',4], ['Row 6',0.8202,214.4,'out',5], ['Row 7',0.8202,244.3,'out',6], ['Row 8',0.8202,274.2,'out',7], ['Row 9',0.8202,304.1,'out',8], ['Row 10',0.8202,334.0,'out',9]]},
  {slug:'Fundamental/Noise', hp:3, px:45.0, img:true, placed:true,
   ports:[['White noise',0.5,64.7,'out',0], ['Pink noise',0.5,109.6,'out',1], ['Red noise',0.5,154.5,'out',2], ['Violet noise',0.5,199.4,'out',3], ['Blue noise',0.5,244.3,'out',4], ['Gray noise',0.5,289.1,'out',5], ['Black noise',0.5,334.0,'out',6]]},
  {slug:'Fundamental/Octave', hp:3, px:45.0, img:true, placed:true,
   ports:[['1V/octave pitch',0.5,286.0,'in',0], ['Octave shift CV',0.5,237.9,'in',1], ['Pitch',0.5,334.0,'out',0]]},
  {slug:'Fundamental/Random', hp:9, px:135.0, img:true, placed:true,
   ports:[['Internal trigger rate',0.1417,237.8,'in',0], ['Shape',0.8528,237.9,'in',1], ['Trigger',0.1417,286.0,'in',2], ['External',0.3788,286.0,'in',3], ['Trigger probability',0.3788,237.8,'in',4], ['Random spread',0.6158,237.9,'in',5], ['Stepped',0.1417,334.0,'out',0], ['Linear',0.3788,334.0,'out',1], ['Smooth',0.8528,334.0,'out',2], ['Exponential',0.6158,334.0,'out',3], ['Trigger',0.8528,286.0,'out',4]]},
  {slug:'Fundamental/SEQ3', hp:22, px:330.0, img:true, placed:true,
   ports:[['Tempo',0.4418,51.1,'in',0], ['Clock',0.6747,51.4,'in',1], ['Reset',0.9077,51.4,'in',2], ['Steps',0.5582,51.1,'in',3], ['Run',0.7912,51.4,'in',4], ['Trigger',0.4418,334.0,'out',0], ['CV 1',0.0923,334.0,'out',1], ['CV 2',0.2088,334.0,'out',2], ['CV 3',0.3253,334.0,'out',3], ['Step 1',0.0923,286.0,'out',4], ['Step 2',0.2088,286.0,'out',5], ['Step 3',0.3253,286.0,'out',6], ['Step 4',0.4418,286.0,'out',7], ['Step 5',0.5582,286.0,'out',8], ['Step 6',0.6747,286.0,'out',9], ['Step 7',0.7912,286.0,'out',10], ['Step 8',0.9077,286.0,'out',11], ['Steps',0.5582,334.0,'out',12], ['Clock',0.6747,334.0,'out',13], ['Run',0.7912,334.0,'out',14], ['Reset',0.9077,334.0,'out',15]]},
  {slug:'Fundamental/Scope', hp:13, px:195.0, img:true, placed:true,
   ports:[['Ch 1',0.1309,334.0,'in',0], ['Ch 2',0.5,334.0,'in',1], ['External trigger',0.8691,334.0,'in',2], ['Ch 1',0.3155,334.0,'out',0], ['Ch 2',0.6846,334.0,'out',1]]},
  {slug:'Fundamental/Split', hp:5, px:75.0, img:true, placed:true,
   ports:[['Polyphonic',0.2867,64.9,'in',0], ['Channel 1',0.2867,124.0,'out',0], ['Channel 2',0.2867,154.0,'out',1], ['Channel 3',0.2867,184.0,'out',2], ['Channel 4',0.2867,214.0,'out',3], ['Channel 5',0.2867,244.0,'out',4], ['Channel 6',0.2867,274.0,'out',5], ['Channel 7',0.2867,304.0,'out',6], ['Channel 8',0.2867,334.0,'out',7], ['Channel 9',0.7133,124.0,'out',8], ['Channel 10',0.7133,154.0,'out',9], ['Channel 11',0.7133,184.0,'out',10], ['Channel 12',0.7133,214.0,'out',11], ['Channel 13',0.7133,244.0,'out',12], ['Channel 14',0.7133,274.0,'out',13], ['Channel 15',0.7133,304.0,'out',14], ['Channel 16',0.7133,334.0,'out',15]]},
  {slug:'Fundamental/VCA', hp:5, px:75.0, img:true, placed:true,
   ports:[['Channel 1 exponential CV',0.26,124.6,'in',0], ['Channel 1 linear CV',0.7327,124.6,'in',1], ['Channel 1',0.26,167.8,'in',2], ['Channel 2 exponential CV',0.26,288.0,'in',3], ['Channel 2 linear CV',0.7327,288.0,'in',4], ['Channel 2',0.26,331.2,'in',5], ['Channel 1',0.7327,167.8,'out',0], ['Channel 2',0.7327,331.2,'out',1]]},
  {slug:'Fundamental/VCF', hp:7, px:105.0, img:true, placed:true,
   ports:[['Frequency',0.1967,285.9,'in',0], ['Resonance',0.5015,285.9,'in',1], ['Drive',0.8062,285.9,'in',2], ['Audio',0.1967,334.0,'in',3], ['Lowpass filter',0.5015,334.0,'out',0], ['Highpass filter',0.8062,334.0,'out',1]]},
  {slug:'Fundamental/VCO', hp:9, px:135.0, img:true, placed:true,
   ports:[['1V/octave pitch',0.3815,286.0,'in',0], ['Frequency modulation',0.1445,286.0,'in',1], ['Sync',0.6186,286.0,'in',2], ['Pulse width modulation',0.8563,286.0,'in',3], ['Sine',0.1445,334.0,'out',0], ['Triangle',0.3815,334.0,'out',1], ['Sawtooth',0.6186,334.0,'out',2], ['Square',0.8556,334.0,'out',3]]},
];

// Corrections this replaces, measured against the hand-written values:
//   Fundamental/LFO   drawn 6 HP -> actually 9
//   Fundamental/ADSR  drawn 8 HP -> actually 9
//   Fundamental/VCF   drawn 8 HP -> actually 7
//   Fundamental/VCA   drawn 6 HP -> actually 5
