// Generated by schema_ts_emit.py from core/timeline/schema/timeline_schema.json.
// Do not edit by hand: this file is a projection of the timeline schema manifest,
// regenerated and drift-checked in CI. Change the SchemaRegistry (and regenerate
// the manifest) instead of editing this file.
// Manifest version: 1

/** `pulp.timeline.asset` — domain Document, schema version 2. */
export interface PulpTimelineAsset {
  content_hash: string;
  frame_count: number | string;
  id: number | string;
  locators: readonly unknown[];
  loop_info?: Record<string, unknown>;
  name: string;
  representations: readonly unknown[];
  sample_rate: Record<string, unknown>;
  storage_policy: string;
}

/** `pulp.timeline.asset_representation` — domain AssetRepresentation, schema version 1. */
export interface PulpTimelineAssetRepresentation {
  content_hash: string;
  locators: readonly unknown[];
  role: string;
  storage_policy: string;
}

/** `pulp.timeline.automation_lane` — domain Document, schema version 1. */
export interface PulpTimelineAutomationLane {
  id: number | string;
  points: readonly unknown[];
  target: Record<string, unknown>;
}

/** `pulp.timeline.automation_target.device_parameter` — domain Document, schema version 1. */
export interface PulpTimelineAutomationTargetDeviceParameter {
  device_placement_id: number | string;
  parameter_id: number | string;
}

/** `pulp.timeline.clip` — domain Document, schema version 1. */
export interface PulpTimelineClip {
  content: Record<string, unknown>;
  fade_in_duration?: number | string;
  fade_out_duration?: number | string;
  gain_linear_bits?: number | string;
  id: number | string;
  time_range: Record<string, unknown>;
}

/** `pulp.timeline.content.empty` — domain Content, schema version 1. */
export interface PulpTimelineContentEmpty {}

/** `pulp.timeline.content.media` — domain Content, schema version 1. */
export interface PulpTimelineContentMedia {
  asset_id: number | string;
  frame_count: number | string;
  source_start: number | string;
}

/** `pulp.timeline.content.notes` — domain Content, schema version 1. */
export interface PulpTimelineContentNotes {
  notes: readonly unknown[];
}

/** `pulp.timeline.device_placement` — domain Document, schema version 1. */
export interface PulpTimelineDevicePlacement {
  id: number | string;
}

/** `pulp.timeline.project` — domain Document, schema version 1. */
export interface PulpTimelineProject {
  assets: readonly unknown[];
  id: number | string;
  identities?: readonly unknown[];
  meter_map?: readonly unknown[];
  name: string;
  next_item_id: number | string;
  root_sequence_id: number | string;
  sequences: readonly unknown[];
  tempo_map?: readonly unknown[];
}

/** `pulp.timeline.sequence` — domain Document, schema version 1. */
export interface PulpTimelineSequence {
  absolute_duration: Record<string, unknown>;
  id: number | string;
  musical_duration: number | string;
  name: string;
  tracks: readonly unknown[];
}

/** `pulp.timeline.take` — domain Document, schema version 1. */
export interface PulpTimelineTake {
  asset_id: number | string;
  frame_count: number | string;
  id: number | string;
  placement_start: number | string;
  sample_rate: Record<string, unknown>;
  source_start: number | string;
}

/** `pulp.timeline.take_lane` — domain Document, schema version 2. */
export interface PulpTimelineTakeLane {
  comp_segments: readonly unknown[];
  id: number | string;
  name: string;
  takes: readonly unknown[];
}

/** `pulp.timeline.track` — domain Document, schema version 6. */
export interface PulpTimelineTrack {
  active_take_lane_id: number | string;
  automation_lanes: readonly unknown[];
  clips: readonly unknown[];
  device_chain: readonly unknown[];
  freeze?: Record<string, unknown>;
  id: number | string;
  name: string;
  record_armed: boolean;
  take_lanes: readonly unknown[];
}

/** Every schema-type name registered in the timeline manifest. */
export type TimelineSchemaTypeName =
  | "pulp.timeline.asset"
  | "pulp.timeline.asset_representation"
  | "pulp.timeline.automation_lane"
  | "pulp.timeline.automation_target.device_parameter"
  | "pulp.timeline.clip"
  | "pulp.timeline.content.empty"
  | "pulp.timeline.content.media"
  | "pulp.timeline.content.notes"
  | "pulp.timeline.device_placement"
  | "pulp.timeline.project"
  | "pulp.timeline.sequence"
  | "pulp.timeline.take"
  | "pulp.timeline.take_lane"
  | "pulp.timeline.track";

/** Maps each schema-type name to its generated interface. */
export interface TimelineSchemaTypeMap {
  "pulp.timeline.asset": PulpTimelineAsset;
  "pulp.timeline.asset_representation": PulpTimelineAssetRepresentation;
  "pulp.timeline.automation_lane": PulpTimelineAutomationLane;
  "pulp.timeline.automation_target.device_parameter": PulpTimelineAutomationTargetDeviceParameter;
  "pulp.timeline.clip": PulpTimelineClip;
  "pulp.timeline.content.empty": PulpTimelineContentEmpty;
  "pulp.timeline.content.media": PulpTimelineContentMedia;
  "pulp.timeline.content.notes": PulpTimelineContentNotes;
  "pulp.timeline.device_placement": PulpTimelineDevicePlacement;
  "pulp.timeline.project": PulpTimelineProject;
  "pulp.timeline.sequence": PulpTimelineSequence;
  "pulp.timeline.take": PulpTimelineTake;
  "pulp.timeline.take_lane": PulpTimelineTakeLane;
  "pulp.timeline.track": PulpTimelineTrack;
}
