// Generated by schema_ts_emit.py from core/timeline/schema/timeline_schema.json.
// Do not edit by hand: this file is a projection of the timeline schema manifest,
// regenerated and drift-checked in CI. Change the SchemaRegistry (and regenerate
// the manifest) instead of editing this file.
// Manifest version: 1

/** `pulp.timeline.asset` — domain Document, schema version 2. */
export interface PulpTimelineAsset {
  content_hash: string;
  frame_count: number | string;
  id: number | string;
  locators: readonly unknown[];
  loop_info?: Record<string, unknown>;
  name: string;
  representations: readonly unknown[];
  sample_rate: Record<string, unknown>;
  storage_policy: string;
}

/** `pulp.timeline.asset_representation` — domain AssetRepresentation, schema version 1. */
export interface PulpTimelineAssetRepresentation {
  content_hash: string;
  locators: readonly unknown[];
  role: string;
  storage_policy: string;
}

/** `pulp.timeline.automation_lane` — domain Document, schema version 1. */
export interface PulpTimelineAutomationLane {
  id: number | string;
  points: readonly unknown[];
  target: Record<string, unknown>;
}

/** `pulp.timeline.automation_target.device_parameter` — domain Document, schema version 1. */
export interface PulpTimelineAutomationTargetDeviceParameter {
  device_placement_id: number | string;
  parameter_id: number | string;
}

/** `pulp.timeline.automation_target.track_mixer` — domain Document, schema version 1. */
export interface PulpTimelineAutomationTargetTrackMixer {
  parameter: string;
}

/** `pulp.timeline.chord_scale_event` — domain Document, schema version 1. */
export interface PulpTimelineChordScaleEvent {
  chord_quality: string;
  chord_root: number | string;
  position: number | string;
  scale_mode: string;
  scale_root: number | string;
}

/** `pulp.timeline.clip` — domain Document, schema version 2. */
export interface PulpTimelineClip {
  content: Record<string, unknown>;
  fade_in_duration?: number | string;
  fade_out_duration?: number | string;
  gain_linear_bits?: number | string;
  id: number | string;
  time_conform: string;
  time_range: Record<string, unknown>;
}

/** `pulp.timeline.command.clone_sequence` — domain Command, schema version 1. */
export interface PulpTimelineCommandCloneSequence {
  cloned_sequence_id: number | string;
  id_remap: readonly unknown[];
  source_sequence_id: number | string;
}

/** `pulp.timeline.command.create_asset` — domain Command, schema version 1. */
export interface PulpTimelineCommandCreateAsset {
  asset: PulpTimelineAsset;
}

/** `pulp.timeline.command.insert_automation_lane` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertAutomationLane {
  lane: PulpTimelineAutomationLane;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.insert_clip` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertClip {
  clip: PulpTimelineClip;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.insert_marker` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertMarker {
  marker: PulpTimelineMarker;
  sequence_id: number | string;
}

/** `pulp.timeline.command.insert_region` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertRegion {
  region: PulpTimelineRegion;
  sequence_id: number | string;
}

/** `pulp.timeline.command.insert_scene` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertScene {
  before_scene_id?: number | string;
  scene: PulpTimelineScene;
  sequence_id: number | string;
}

/** `pulp.timeline.command.insert_sequence` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertSequence {
  sequence: PulpTimelineSequence;
}

/** `pulp.timeline.command.insert_slot` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertSlot {
  before_slot_id?: number | string;
  scene_id: number | string;
  sequence_id: number | string;
  slot: PulpTimelineSlot;
}

/** `pulp.timeline.command.insert_take` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertTake {
  lane_id: number | string;
  sequence_id: number | string;
  take: PulpTimelineTake;
  track_id: number | string;
}

/** `pulp.timeline.command.insert_take_lane` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertTakeLane {
  lane: PulpTimelineTakeLane;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.insert_track` — domain Command, schema version 1. */
export interface PulpTimelineCommandInsertTrack {
  before_track_id?: number | string;
  sequence_id: number | string;
  track: PulpTimelineTrack;
}

/** `pulp.timeline.command.move_clip` — domain Command, schema version 1. */
export interface PulpTimelineCommandMoveClip {
  clip_id: number | string;
  expected_range: Record<string, unknown>;
  replacement_range: Record<string, unknown>;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.remove_asset` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveAsset {
  asset_id: number | string;
}

/** `pulp.timeline.command.remove_automation_lane` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveAutomationLane {
  lane_id: number | string;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.remove_clip` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveClip {
  clip_id: number | string;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.remove_marker` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveMarker {
  marker_id: number | string;
  sequence_id: number | string;
}

/** `pulp.timeline.command.remove_region` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveRegion {
  region_id: number | string;
  sequence_id: number | string;
}

/** `pulp.timeline.command.remove_scene` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveScene {
  scene_id: number | string;
  sequence_id: number | string;
}

/** `pulp.timeline.command.remove_sequence` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveSequence {
  sequence_id: number | string;
}

/** `pulp.timeline.command.remove_slot` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveSlot {
  scene_id: number | string;
  sequence_id: number | string;
  slot_id: number | string;
}

/** `pulp.timeline.command.remove_take` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveTake {
  lane_id: number | string;
  sequence_id: number | string;
  take_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.remove_take_lane` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveTakeLane {
  lane_id: number | string;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.remove_track` — domain Command, schema version 1. */
export interface PulpTimelineCommandRemoveTrack {
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.replace_note_content` — domain Command, schema version 1. */
export interface PulpTimelineCommandReplaceNoteContent {
  clip_id: number | string;
  expected: readonly unknown[];
  replacement: readonly unknown[];
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_active_take_lane` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetActiveTakeLane {
  expected_lane_id: number | string;
  replacement_lane_id: number | string;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_chord_scale_lane` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetChordScaleLane {
  expected: readonly unknown[];
  replacement: readonly unknown[];
  sequence_id: number | string;
}

/** `pulp.timeline.command.set_clip_playback_properties` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetClipPlaybackProperties {
  clip_id: number | string;
  expected: Record<string, unknown>;
  replacement: Record<string, unknown>;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_clip_sequence_ref` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetClipSequenceRef {
  clip_id: number | string;
  expected: Record<string, unknown>;
  replacement: Record<string, unknown>;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_groove` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetGroove {
  expected: PulpTimelineGrooveTemplate;
  replacement: PulpTimelineGrooveTemplate;
  sequence_id: number | string;
}

/** `pulp.timeline.command.set_meter_map` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetMeterMap {
  expected: readonly unknown[];
  replacement: readonly unknown[];
}

/** `pulp.timeline.command.set_note_velocity` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetNoteVelocity {
  clip_id: number | string;
  expected_velocity: number | string;
  note_id: number | string;
  replacement_velocity: number | string;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_record_arm` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetRecordArm {
  expected: boolean;
  replacement: boolean;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_take_comp` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetTakeComp {
  expected: readonly unknown[];
  lane_id: number | string;
  replacement: readonly unknown[];
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_tempo_map` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetTempoMap {
  expected: readonly unknown[];
  replacement: readonly unknown[];
}

/** `pulp.timeline.command.set_track_freeze` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetTrackFreeze {
  expected?: Record<string, unknown>;
  replacement?: Record<string, unknown>;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.command.set_track_mixer` — domain Command, schema version 1. */
export interface PulpTimelineCommandSetTrackMixer {
  expected: Record<string, unknown>;
  replacement: Record<string, unknown>;
  sequence_id: number | string;
  track_id: number | string;
}

/** `pulp.timeline.content.empty` — domain Content, schema version 1. */
export interface PulpTimelineContentEmpty {}

/** `pulp.timeline.content.media` — domain Content, schema version 1. */
export interface PulpTimelineContentMedia {
  asset_id: number | string;
  frame_count: number | string;
  source_start: number | string;
}

/** `pulp.timeline.content.notes` — domain Content, schema version 2. */
export interface PulpTimelineContentNotes {
  modifier_seed: number | string;
  modifiers: readonly unknown[];
  notes: readonly unknown[];
}

/** `pulp.timeline.content.sequence_ref` — domain Content, schema version 1. */
export interface PulpTimelineContentSequenceRef {
  sequence_id: number | string;
  source_start: number | string;
}

/** `pulp.timeline.device_placement` — domain Document, schema version 1. */
export interface PulpTimelineDevicePlacement {
  id: number | string;
}

/** `pulp.timeline.groove_step` — domain Document, schema version 1. */
export interface PulpTimelineGrooveStep {
  timing_offset: number | string;
  velocity_scale: number | string;
}

/** `pulp.timeline.groove_template` — domain Document, schema version 1. */
export interface PulpTimelineGrooveTemplate {
  name: string;
  step: number | string;
  steps: readonly PulpTimelineGrooveStep[];
  swing_denominator: number | string;
  swing_grid: number | string;
  swing_numerator: number | string;
  timing_strength: number | string;
  velocity_strength: number | string;
}

/** `pulp.timeline.marker` — domain Document, schema version 1. */
export interface PulpTimelineMarker {
  color?: number | string;
  id: number | string;
  name: string;
  position: number | string;
}

/** `pulp.timeline.project` — domain Document, schema version 2. */
export interface PulpTimelineProject {
  assets: readonly unknown[];
  id: number | string;
  identities?: readonly unknown[];
  meter_map?: readonly unknown[];
  name: string;
  next_item_id: number | string;
  root_sequence_id: number | string;
  sequences: readonly unknown[];
  session_start?: Record<string, unknown>;
  tempo_map?: readonly unknown[];
}

/** `pulp.timeline.region` — domain Document, schema version 1. */
export interface PulpTimelineRegion {
  color?: number | string;
  duration: number | string;
  id: number | string;
  name: string;
  position: number | string;
}

/** `pulp.timeline.scene` — domain Document, schema version 1. */
export interface PulpTimelineScene {
  id: number | string;
  name: string;
  slots: readonly unknown[];
}

/** `pulp.timeline.sequence` — domain Document, schema version 6. */
export interface PulpTimelineSequence {
  absolute_duration: Record<string, unknown>;
  chord_scale_lane: readonly unknown[];
  groove: PulpTimelineGrooveTemplate;
  id: number | string;
  markers: readonly unknown[];
  musical_duration: number | string;
  name: string;
  regions: readonly unknown[];
  scenes: readonly unknown[];
  track_order: readonly unknown[];
  tracks: readonly unknown[];
}

/** `pulp.timeline.slot` — domain Document, schema version 1. */
export interface PulpTimelineSlot {
  clip_id: number | string;
  follow: Record<string, unknown>;
  id: number | string;
  launch_quantize: Record<string, unknown>;
}

/** `pulp.timeline.take` — domain Document, schema version 1. */
export interface PulpTimelineTake {
  asset_id: number | string;
  frame_count: number | string;
  id: number | string;
  placement_start: number | string;
  sample_rate: Record<string, unknown>;
  source_start: number | string;
}

/** `pulp.timeline.take_lane` — domain Document, schema version 2. */
export interface PulpTimelineTakeLane {
  comp_segments: readonly unknown[];
  id: number | string;
  name: string;
  takes: readonly unknown[];
}

/** `pulp.timeline.track` — domain Document, schema version 7. */
export interface PulpTimelineTrack {
  active_take_lane_id: number | string;
  automation_lanes: readonly unknown[];
  clips: readonly unknown[];
  device_chain: readonly unknown[];
  freeze?: Record<string, unknown>;
  id: number | string;
  mixer?: Record<string, unknown>;
  name: string;
  record_armed: boolean;
  take_lanes: readonly unknown[];
}

/** Every schema-type name registered in the timeline manifest. */
export type TimelineSchemaTypeName =
  | "pulp.timeline.asset"
  | "pulp.timeline.asset_representation"
  | "pulp.timeline.automation_lane"
  | "pulp.timeline.automation_target.device_parameter"
  | "pulp.timeline.automation_target.track_mixer"
  | "pulp.timeline.chord_scale_event"
  | "pulp.timeline.clip"
  | "pulp.timeline.command.clone_sequence"
  | "pulp.timeline.command.create_asset"
  | "pulp.timeline.command.insert_automation_lane"
  | "pulp.timeline.command.insert_clip"
  | "pulp.timeline.command.insert_marker"
  | "pulp.timeline.command.insert_region"
  | "pulp.timeline.command.insert_scene"
  | "pulp.timeline.command.insert_sequence"
  | "pulp.timeline.command.insert_slot"
  | "pulp.timeline.command.insert_take"
  | "pulp.timeline.command.insert_take_lane"
  | "pulp.timeline.command.insert_track"
  | "pulp.timeline.command.move_clip"
  | "pulp.timeline.command.remove_asset"
  | "pulp.timeline.command.remove_automation_lane"
  | "pulp.timeline.command.remove_clip"
  | "pulp.timeline.command.remove_marker"
  | "pulp.timeline.command.remove_region"
  | "pulp.timeline.command.remove_scene"
  | "pulp.timeline.command.remove_sequence"
  | "pulp.timeline.command.remove_slot"
  | "pulp.timeline.command.remove_take"
  | "pulp.timeline.command.remove_take_lane"
  | "pulp.timeline.command.remove_track"
  | "pulp.timeline.command.replace_note_content"
  | "pulp.timeline.command.set_active_take_lane"
  | "pulp.timeline.command.set_chord_scale_lane"
  | "pulp.timeline.command.set_clip_playback_properties"
  | "pulp.timeline.command.set_clip_sequence_ref"
  | "pulp.timeline.command.set_groove"
  | "pulp.timeline.command.set_meter_map"
  | "pulp.timeline.command.set_note_velocity"
  | "pulp.timeline.command.set_record_arm"
  | "pulp.timeline.command.set_take_comp"
  | "pulp.timeline.command.set_tempo_map"
  | "pulp.timeline.command.set_track_freeze"
  | "pulp.timeline.command.set_track_mixer"
  | "pulp.timeline.content.empty"
  | "pulp.timeline.content.media"
  | "pulp.timeline.content.notes"
  | "pulp.timeline.content.sequence_ref"
  | "pulp.timeline.device_placement"
  | "pulp.timeline.groove_step"
  | "pulp.timeline.groove_template"
  | "pulp.timeline.marker"
  | "pulp.timeline.project"
  | "pulp.timeline.region"
  | "pulp.timeline.scene"
  | "pulp.timeline.sequence"
  | "pulp.timeline.slot"
  | "pulp.timeline.take"
  | "pulp.timeline.take_lane"
  | "pulp.timeline.track";

/** Maps each schema-type name to its generated interface. */
export interface TimelineSchemaTypeMap {
  "pulp.timeline.asset": PulpTimelineAsset;
  "pulp.timeline.asset_representation": PulpTimelineAssetRepresentation;
  "pulp.timeline.automation_lane": PulpTimelineAutomationLane;
  "pulp.timeline.automation_target.device_parameter": PulpTimelineAutomationTargetDeviceParameter;
  "pulp.timeline.automation_target.track_mixer": PulpTimelineAutomationTargetTrackMixer;
  "pulp.timeline.chord_scale_event": PulpTimelineChordScaleEvent;
  "pulp.timeline.clip": PulpTimelineClip;
  "pulp.timeline.command.clone_sequence": PulpTimelineCommandCloneSequence;
  "pulp.timeline.command.create_asset": PulpTimelineCommandCreateAsset;
  "pulp.timeline.command.insert_automation_lane": PulpTimelineCommandInsertAutomationLane;
  "pulp.timeline.command.insert_clip": PulpTimelineCommandInsertClip;
  "pulp.timeline.command.insert_marker": PulpTimelineCommandInsertMarker;
  "pulp.timeline.command.insert_region": PulpTimelineCommandInsertRegion;
  "pulp.timeline.command.insert_scene": PulpTimelineCommandInsertScene;
  "pulp.timeline.command.insert_sequence": PulpTimelineCommandInsertSequence;
  "pulp.timeline.command.insert_slot": PulpTimelineCommandInsertSlot;
  "pulp.timeline.command.insert_take": PulpTimelineCommandInsertTake;
  "pulp.timeline.command.insert_take_lane": PulpTimelineCommandInsertTakeLane;
  "pulp.timeline.command.insert_track": PulpTimelineCommandInsertTrack;
  "pulp.timeline.command.move_clip": PulpTimelineCommandMoveClip;
  "pulp.timeline.command.remove_asset": PulpTimelineCommandRemoveAsset;
  "pulp.timeline.command.remove_automation_lane": PulpTimelineCommandRemoveAutomationLane;
  "pulp.timeline.command.remove_clip": PulpTimelineCommandRemoveClip;
  "pulp.timeline.command.remove_marker": PulpTimelineCommandRemoveMarker;
  "pulp.timeline.command.remove_region": PulpTimelineCommandRemoveRegion;
  "pulp.timeline.command.remove_scene": PulpTimelineCommandRemoveScene;
  "pulp.timeline.command.remove_sequence": PulpTimelineCommandRemoveSequence;
  "pulp.timeline.command.remove_slot": PulpTimelineCommandRemoveSlot;
  "pulp.timeline.command.remove_take": PulpTimelineCommandRemoveTake;
  "pulp.timeline.command.remove_take_lane": PulpTimelineCommandRemoveTakeLane;
  "pulp.timeline.command.remove_track": PulpTimelineCommandRemoveTrack;
  "pulp.timeline.command.replace_note_content": PulpTimelineCommandReplaceNoteContent;
  "pulp.timeline.command.set_active_take_lane": PulpTimelineCommandSetActiveTakeLane;
  "pulp.timeline.command.set_chord_scale_lane": PulpTimelineCommandSetChordScaleLane;
  "pulp.timeline.command.set_clip_playback_properties": PulpTimelineCommandSetClipPlaybackProperties;
  "pulp.timeline.command.set_clip_sequence_ref": PulpTimelineCommandSetClipSequenceRef;
  "pulp.timeline.command.set_groove": PulpTimelineCommandSetGroove;
  "pulp.timeline.command.set_meter_map": PulpTimelineCommandSetMeterMap;
  "pulp.timeline.command.set_note_velocity": PulpTimelineCommandSetNoteVelocity;
  "pulp.timeline.command.set_record_arm": PulpTimelineCommandSetRecordArm;
  "pulp.timeline.command.set_take_comp": PulpTimelineCommandSetTakeComp;
  "pulp.timeline.command.set_tempo_map": PulpTimelineCommandSetTempoMap;
  "pulp.timeline.command.set_track_freeze": PulpTimelineCommandSetTrackFreeze;
  "pulp.timeline.command.set_track_mixer": PulpTimelineCommandSetTrackMixer;
  "pulp.timeline.content.empty": PulpTimelineContentEmpty;
  "pulp.timeline.content.media": PulpTimelineContentMedia;
  "pulp.timeline.content.notes": PulpTimelineContentNotes;
  "pulp.timeline.content.sequence_ref": PulpTimelineContentSequenceRef;
  "pulp.timeline.device_placement": PulpTimelineDevicePlacement;
  "pulp.timeline.groove_step": PulpTimelineGrooveStep;
  "pulp.timeline.groove_template": PulpTimelineGrooveTemplate;
  "pulp.timeline.marker": PulpTimelineMarker;
  "pulp.timeline.project": PulpTimelineProject;
  "pulp.timeline.region": PulpTimelineRegion;
  "pulp.timeline.scene": PulpTimelineScene;
  "pulp.timeline.sequence": PulpTimelineSequence;
  "pulp.timeline.slot": PulpTimelineSlot;
  "pulp.timeline.take": PulpTimelineTake;
  "pulp.timeline.take_lane": PulpTimelineTakeLane;
  "pulp.timeline.track": PulpTimelineTrack;
}
