// Generated by schema_js_emit.py from core/timeline/schema/timeline_schema.json.
// Do not edit by hand: this file is a projection of the timeline schema manifest,
// regenerated and drift-checked in CI. Change the SchemaRegistry (and regenerate
// the manifest) instead of editing this file.
// Manifest version: 1

export const timelineSchemaManifestVersion = 1;

// Frozen runtime descriptor for every timeline schema type, keyed by schema name.
export const timelineSchema = Object.freeze({
  "pulp.timeline.asset": Object.freeze({
    schemaType: "pulp.timeline.asset",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "content_hash", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "frame_count", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "locators", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "name", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "representations", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "sample_rate", kind: "Object", jsType: "object", required: true }),
      Object.freeze({ name: "storage_policy", kind: "String", jsType: "string", required: true }),
    ]),
  }),
  "pulp.timeline.asset_representation": Object.freeze({
    schemaType: "pulp.timeline.asset_representation",
    domain: "AssetRepresentation",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "content_hash", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "locators", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "role", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "storage_policy", kind: "String", jsType: "string", required: true }),
    ]),
  }),
  "pulp.timeline.automation_lane": Object.freeze({
    schemaType: "pulp.timeline.automation_lane",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "points", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "target", kind: "Object", jsType: "object", required: true }),
    ]),
  }),
  "pulp.timeline.automation_target.device_parameter": Object.freeze({
    schemaType: "pulp.timeline.automation_target.device_parameter",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "device_placement_id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "parameter_id", kind: "U32", jsType: "number", required: true }),
    ]),
  }),
  "pulp.timeline.clip": Object.freeze({
    schemaType: "pulp.timeline.clip",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "content", kind: "Object", jsType: "object", required: true }),
      Object.freeze({ name: "fade_in_duration", kind: "U64String", jsType: "string", required: false }),
      Object.freeze({ name: "fade_out_duration", kind: "U64String", jsType: "string", required: false }),
      Object.freeze({ name: "gain_linear_bits", kind: "U64String", jsType: "string", required: false }),
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "time_range", kind: "Object", jsType: "object", required: true }),
    ]),
  }),
  "pulp.timeline.content.empty": Object.freeze({
    schemaType: "pulp.timeline.content.empty",
    domain: "Content",
    version: 1,
    fields: Object.freeze([]),
  }),
  "pulp.timeline.content.media": Object.freeze({
    schemaType: "pulp.timeline.content.media",
    domain: "Content",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "asset_id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "frame_count", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "source_start", kind: "I64String", jsType: "string", required: true }),
    ]),
  }),
  "pulp.timeline.content.notes": Object.freeze({
    schemaType: "pulp.timeline.content.notes",
    domain: "Content",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "notes", kind: "Array", jsType: "array", required: true }),
    ]),
  }),
  "pulp.timeline.device_placement": Object.freeze({
    schemaType: "pulp.timeline.device_placement",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
    ]),
  }),
  "pulp.timeline.project": Object.freeze({
    schemaType: "pulp.timeline.project",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "assets", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "identities", kind: "Array", jsType: "array", required: false }),
      Object.freeze({ name: "meter_map", kind: "Array", jsType: "array", required: false }),
      Object.freeze({ name: "name", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "next_item_id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "root_sequence_id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "sequences", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "tempo_map", kind: "Array", jsType: "array", required: false }),
    ]),
  }),
  "pulp.timeline.sequence": Object.freeze({
    schemaType: "pulp.timeline.sequence",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "absolute_duration", kind: "Object", jsType: "object", required: true }),
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "musical_duration", kind: "I64String", jsType: "string", required: true }),
      Object.freeze({ name: "name", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "tracks", kind: "Array", jsType: "array", required: true }),
    ]),
  }),
  "pulp.timeline.take": Object.freeze({
    schemaType: "pulp.timeline.take",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "asset_id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "frame_count", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "placement_start", kind: "I64String", jsType: "string", required: true }),
      Object.freeze({ name: "sample_rate", kind: "Object", jsType: "object", required: true }),
      Object.freeze({ name: "source_start", kind: "I64String", jsType: "string", required: true }),
    ]),
  }),
  "pulp.timeline.take_lane": Object.freeze({
    schemaType: "pulp.timeline.take_lane",
    domain: "Document",
    version: 1,
    fields: Object.freeze([
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "name", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "takes", kind: "Array", jsType: "array", required: true }),
    ]),
  }),
  "pulp.timeline.track": Object.freeze({
    schemaType: "pulp.timeline.track",
    domain: "Document",
    version: 5,
    fields: Object.freeze([
      Object.freeze({ name: "active_take_lane_id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "automation_lanes", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "clips", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "device_chain", kind: "Array", jsType: "array", required: true }),
      Object.freeze({ name: "id", kind: "U64String", jsType: "string", required: true }),
      Object.freeze({ name: "name", kind: "String", jsType: "string", required: true }),
      Object.freeze({ name: "record_armed", kind: "Boolean", jsType: "boolean", required: true }),
      Object.freeze({ name: "take_lanes", kind: "Array", jsType: "array", required: true }),
    ]),
  }),
});

// Every registered timeline schema-type name, sorted.
export const timelineSchemaTypeNames = Object.freeze([
  "pulp.timeline.asset",
  "pulp.timeline.asset_representation",
  "pulp.timeline.automation_lane",
  "pulp.timeline.automation_target.device_parameter",
  "pulp.timeline.clip",
  "pulp.timeline.content.empty",
  "pulp.timeline.content.media",
  "pulp.timeline.content.notes",
  "pulp.timeline.device_placement",
  "pulp.timeline.project",
  "pulp.timeline.sequence",
  "pulp.timeline.take",
  "pulp.timeline.take_lane",
  "pulp.timeline.track",
]);
