// SPDX-License-Identifier: MIT

// The production bridge from a captured materialized browser document to an
// owned, reviewable source tree.  This module deliberately does not compile
// JavaScript or infer component boundaries: the captured HTML remains the
// executable authority, while the emitted tree gives agents stable files to
// inspect and edit.  Runtime compilation stays in materialized-runtime-
// transform.mjs so the two contracts cannot drift.

import {
  mkdir,
  readFile,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import {
  applyMaterializedIdsMap,
  normalizeMaterializedIdsMap,
  serializeMaterializedIdsMap,
} from './materialized_ids_map.mjs';
import {
  isMaterializedBrowserDocumentSchema,
  normalizeMaterializedBindingDocument,
  MATERIALIZED_BINDING_KINDS,
} from './materialized_binding_contract.mjs';

const SOURCE_SCHEMA = 'pulp-materialized-runtime-source-v1';

function fail(message) {
  throw new Error(`materialized source emitter ${message}`);
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [
      key, canonical(value[key]),
    ]));
  }
  return value;
}

export function canonicalJson(value) {
  return `${JSON.stringify(canonical(value), null, 2)}\n`;
}

function sourceIdentityStatus(binding) {
  const source = binding?.source && typeof binding.source === 'object'
    ? { ...binding, ...binding.source } : binding;
  const explicit = source?.data_pulp_id ?? source?.pulp_id ??
    source?.source_id ?? source?.stable_id;
  const fields = [source?.component ?? source?.component_name ??
    source?.source_component_name, source?.local_path ?? source?.localPath ??
    source?.source_local_path, source?.content_hash ?? source?.contentHash];
  const present = fields.filter((field) => field !== undefined &&
    field !== null && field !== '').length;
  if (explicit !== undefined && explicit !== null && explicit !== '') {
    // An explicit source id is a stable identity even when an adapter cannot
    // provide the source tuple.  The tuple is still required when an ids map
    // is requested, because otherwise an edit cannot be carried forward.
    return { kind: present === 3 ? 'complete' : 'explicit', present };
  }
  if (present === 0) return { kind: 'missing', present };
  if (present !== 3) return { kind: 'partial', present };
  return { kind: 'complete', present };
}

function allBindings(document) {
  const rows = [];
  for (const kind of MATERIALIZED_BINDING_KINDS) {
    const list = document[`${kind}_bindings`];
    if (!Array.isArray(list)) fail(`${kind}_bindings must be an array`);
    list.forEach((binding, index) => rows.push({ kind, index, binding }));
  }
  return rows;
}

function validateStableIdentities(document, { requireTuple }) {
  const rows = allBindings(document);
  if (rows.length === 0) fail('contains no bindings; stable identity cannot be proven');
  const missing = rows.filter((row) => sourceIdentityStatus(row.binding).kind === 'missing');
  const partial = rows.filter((row) => sourceIdentityStatus(row.binding).kind === 'partial');
  if (partial.length) {
    const first = partial[0];
    fail(`has partial source identity at ${first.kind}[${first.index}]`);
  }
  if (requireTuple) {
    const noTuple = rows.filter((row) => sourceIdentityStatus(row.binding).kind === 'explicit');
    if (noTuple.length) {
      const first = noTuple[0];
      fail(`stable ids require a source tuple at ${first.kind}[${first.index}]`);
    }
  } else if (missing.length) {
    const first = missing[0];
    fail(`has missing source identity at ${first.kind}[${first.index}]`);
  }
  return rows;
}

function sourceTsx(document) {
  // Keep the source as a data boundary. This is valid TSX and is intentionally
  // boring: future source writers may replace it with component splitting while
  // the materialized runtime contract and IDs remain unchanged.
  const html = JSON.stringify(String(document.html || ''));
  return `// Generated by pulp import-design --emit materialized-runtime.\n` +
    `// Edit the source design and re-run the importer; do not hand-edit the runtime sidecar.\n` +
    `export const materializedHtml = ${html};\n\n` +
    `export function MaterializedDocument() {\n` +
    `  return <div dangerouslySetInnerHTML={{__html: materializedHtml}} />;\n` +
    `}\n`;
}

function tokensCss(document) {
  const background = String(document?.surface_style?.background_color || '').trim();
  const safe = background && !/[;{}<>]/.test(background) ? background : 'transparent';
  return `/* Generated by pulp import-design; source tokens are captured at import time. */\n` +
    `:root {\n  --pulp-surface-background: ${safe};\n}\n`;
}

function buildToml({ idsMode, bindingsPath, runtimePath }) {
  return `schema = "${SOURCE_SCHEMA}"\n` +
    `ids = "${idsMode}"\n` +
    `runtime_document = "${runtimePath}"\n` +
    `bindings = "${bindingsPath}"\n`;
}

/**
 * Emit a deterministic materialized runtime source tree.
 *
 * `idsMode=stable` requires complete source tuples for every binding and
 * writes/updates `ids.map.json`.  The default `positional` mode is retained
 * for old captures and deliberately reports no stability guarantee.
 */
export async function emitMaterializedRuntime({
  document,
  outputDirectory,
  idsMode = 'positional',
  idsMap,
} = {}) {
  if (!document || typeof document !== 'object' || Array.isArray(document))
    fail('document is invalid');
  if (!isMaterializedBrowserDocumentSchema(document))
    fail('document must use pulp-materialized-browser-document-v1 or v2');
  if (!outputDirectory || typeof outputDirectory !== 'string')
    fail('output directory is required');
  if (idsMode !== 'stable' && idsMode !== 'positional')
    fail('ids mode must be stable or positional');

  let normalized = normalizeMaterializedBindingDocument(document, {
    upgradeSchema: true,
  });
  let map = normalizeMaterializedIdsMap(idsMap);
  if (idsMode === 'stable') {
    validateStableIdentities(normalized, { requireTuple: true });
    // Apply the persistent source map to the ordered binding lists.  The
    // existing v2 projection is derived data and must be discarded before the
    // mutation; retaining it would make the map/list consistency check compare
    // ids from the pre-apply document with the newly assigned ids.
    const sourceDocument = { ...normalized };
    delete sourceDocument.bindings_by_id;
    const applied = applyMaterializedIdsMap(sourceDocument, map);
    map = applied.idsMap;
    normalized = normalizeMaterializedBindingDocument(applied.document, {
      upgradeSchema: true,
    });
    // `applyMaterializedIdsMap` writes the source id into the capture rows;
    // schema-v2 normalization must retain it in every list.
    validateStableIdentities(normalized, { requireTuple: false });
  }

  const out = path.resolve(outputDirectory);
  const files = new Map([
    ['src/MaterializedDocument.tsx', sourceTsx(normalized)],
    ['styles/tokens.css', tokensCss(normalized)],
    ['bindings/editor.bindings.json', canonicalJson({
      schema: SOURCE_SCHEMA,
      ids: idsMode,
      bindings_by_id: normalized.bindings_by_id,
    })],
    ['runtime/materialized-document.json', canonicalJson(normalized)],
    ['build.toml', buildToml({
      idsMode,
      bindingsPath: 'bindings/editor.bindings.json',
      runtimePath: 'runtime/materialized-document.json',
    })],
  ]);
  if (idsMode === 'stable') files.set('ids.map.json', serializeMaterializedIdsMap(map));

  await Promise.all([...files].map(async ([relative, body]) => {
    const destination = path.join(out, relative);
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, body, 'utf8');
  }));
  return {
    schema: SOURCE_SCHEMA,
    ids: idsMode,
    files: [...files.keys()],
    outputDirectory: out,
    document: normalized,
    idsMap: map,
  };
}

async function main(argv) {
  const value = (name, required = true) => {
    const index = argv.indexOf(name);
    if (index < 0 || index + 1 >= argv.length || argv[index + 1].startsWith('--')) {
      if (required) fail(`${name} is required`);
      return '';
    }
    return argv[index + 1];
  };
  if (argv.includes('--help') || argv.includes('-h')) {
    console.log('Usage: materialized_source_emitter.mjs --in <document.json> --out <dir> [--ids stable|positional] [--ids-map <ids.map.json>]');
    return;
  }
  const input = value('--in');
  const out = value('--out');
  const ids = value('--ids', false) || 'positional';
  const mapPath = value('--ids-map', false);
  const document = JSON.parse(await readFile(input, 'utf8'));
  const idsMap = mapPath ? JSON.parse(await readFile(mapPath, 'utf8')) : undefined;
  const result = await emitMaterializedRuntime({
    document, outputDirectory: out, idsMode: ids, idsMap,
  });
  console.log(canonicalJson({
    schema: result.schema, ids: result.ids, files: result.files,
  }).trim());
}

if (import.meta.url === `file://${process.argv[1]}`) {
  await main(process.argv.slice(2));
}
