#include <pulp/view/design_codegen.hpp>

#include "design_cpp_binding_codegen.hpp"
#include "design_cpp_codegen_internal.hpp"
#include "design_import_native_common.hpp"

#include <memory>
#include <filesystem>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace pulp::view {

CppExportResult generate_pulp_cpp(const DesignIR& ir,
                                  const IRAssetManifest& manifest,
                                  const CppExportOptions& input_opts) {
    using namespace cpp_codegen;
    CppExportOptions opts = input_opts;
    if (opts.function_name.empty())
        opts.function_name = "build_imported_ui";
    if (opts.header_filename.empty())
        opts.header_filename = "imported_ui.hpp";
    if (opts.indent_spaces <= 0)
        opts.indent_spaces = 4;

    const IRAssetManifest& effective_manifest = manifest.assets.empty()
        ? ir.asset_manifest
        : manifest;
    const DesignIR prepared = prepare_native_design_ir(ir);
    auto resolved = resolve_design_ir_native(prepared, effective_manifest);

    const auto binding_artifacts =
        generate_cpp_binding_artifacts(prepared.root, resolved, opts);

    EmitContext ctx{
        .opts = opts,
        .manifest = effective_manifest,
    };
    ctx.used_functions.insert(opts.function_name);
    ctx.tokens = build_token_symbols(ir, ctx);
    ctx.assets = build_asset_symbols(effective_manifest, ctx);
    collect_components(prepared.root, resolved, ctx, std::nullopt, true);

    CppExportResult result;
    {
        std::ostringstream header;
        header << "#pragma once\n\n"
               << "#include <memory>\n"
               << "#include <pulp/view/design_import.hpp>\n"
               << "#include <pulp/view/view.hpp>\n\n";
        emit_namespace_open(header, opts.namespace_name);
        header << "std::unique_ptr<pulp::view::View> " << opts.function_name
               << "(const std::filesystem::path& asset_base_directory);\n"
               << "std::unique_ptr<pulp::view::View> " << opts.function_name << "();\n"
               << "pulp::view::IRAssetManifest bake_asset_manifest();\n";
        if (binding_artifacts.has_helpers) {
            header << "void " << opts.binding_function_name
                   << "(pulp::view::View& root, pulp::view::NativeImportBindingContext& ctx);\n";
        }
        emit_namespace_close(header, opts.namespace_name);
        result.header = header.str();
    }

    std::ostringstream source;
    if (opts.include_comments)
        source << "// Generated by Pulp import-design baked C++ exporter.\n";
    source << "#include " << cpp_string_literal(opts.header_filename) << "\n\n"
           << "#include <algorithm>\n"
           << "#include <memory>\n"
           << "#include <filesystem>\n"
           << "#include <string>\n"
           << "#include <string_view>\n"
           << "#include <utility>\n"
           << "#include <vector>\n"
           << "#include <pulp/view/buttons.hpp>\n"
           << "#include <pulp/view/canvas_widget.hpp>\n"
           << "#include <pulp/view/css_gradient.hpp>\n"
           << "#include <pulp/view/design_frame_view.hpp>\n"
           << "#include <pulp/view/svg_path_widget.hpp>\n"
           << "#include <pulp/view/text_editor.hpp>\n"
           << "#include <pulp/view/widgets.hpp>\n"
           << "#include <pulp/view/widgets/svg_line.hpp>\n"
           << "#include <pulp/view/widgets/svg_rect.hpp>\n"
           << "#include <pulp/runtime/base64.hpp>\n\n";

    emit_namespace_open(source, opts.namespace_name);
    emit_tokens(source, ir, ctx);
    emit_asset_constants(source, effective_manifest, ctx);
    emit_manifest(source, effective_manifest, ctx);

    for (const auto& component : ctx.components)
        source << "std::unique_ptr<pulp::view::View> " << component.function_name
               << "(const std::filesystem::path& asset_base_directory);\n";
    if (!ctx.components.empty())
        source << "\n";

    for (const auto& component : ctx.components)
        emit_function(source,
                      ctx,
                      component.function_name,
                      *component.node,
                      *component.resolved,
                      component.parent_direction,
                      component.rule_comment);

    emit_function(source, ctx, opts.function_name, prepared.root, resolved, std::nullopt);
    source << "std::unique_ptr<pulp::view::View> " << opts.function_name << "() {\n"
           << "    return " << opts.function_name
           << "(std::filesystem::path(__FILE__).parent_path());\n"
           << "}\n\n";
    if (binding_artifacts.has_helpers)
        source << binding_artifacts.helper_source;
    emit_namespace_close(source, opts.namespace_name);
    result.source = trim_trailing_blank_lines(source.str());
    result.binding_manifest = binding_artifacts.binding_manifest;
    return result;
}

}  // namespace pulp::view
