#!/usr/bin/env python3
"""Emit the real module geometry a design prototype needs, as JS.

The prototype hand-writes each module's width, knobs and jacks, and it gets
them wrong -- Fundamental's LFO is drawn at 6 HP when it is 9, its VCA at 6
when it is 5. That is not carelessness; nobody can know these numbers without
measuring a running Rack, and a designer has no way to do that.

We can. The cartographer records every module the user has placed, so this
turns that recording into a drop-in replacement for the prototype's invented
`MODS` array: true widths, the vendor's own port names, and jack positions as
fractions of the panel so the prototype's own drawing code can use them
unchanged.

    export_design_data.py            # JS, paste over the MODS array
    export_design_data.py --json     # the same data, for anything else

Anything absent from the port map is reported rather than guessed at.
"""
from __future__ import annotations

import json
import os
import sys

PORTMAP = os.path.expanduser(
    "~/Library/Application Support/Rack2/forge-portmap.json")
SHOTS = os.path.expanduser("~/Library/Application Support/Rack2/screenshots")
HP_PX = 15.0
PANEL_H = 380.0


def collect() -> list:
    if not os.path.exists(PORTMAP):
        raise SystemExit(
            f"no port map at {PORTMAP}\n"
            "Add the MAP module to a rack in VCV Rack alongside the modules "
            "you want recorded; it writes the file when the rack changes.")
    doc = json.load(open(PORTMAP))
    out = []
    for m in doc.get("modules", []):
        w = m.get("size", [0, 0])[0]
        if not w:
            continue
        slug = f"{m['plugin']}/{m['model']}"
        png = os.path.join(SHOTS, m["plugin"], m["model"] + ".png")
        ports = []
        for kind in ("inputs", "outputs"):
            for p in sorted(m.get(kind) or [], key=lambda x: x["index"]):
                ports.append({
                    "index": p["index"],
                    "dir": "in" if kind == "inputs" else "out",
                    # Fractions of the panel, so the prototype's drawing code
                    # works at whatever scale it is rendering.
                    "x": round(p["x"] / w, 4),
                    "y": round(p["y"], 1),
                    "name": p.get("name", ""),
                })
        out.append({
            "slug": slug,
            "plugin": m["plugin"],
            "model": m["model"],
            "hp": round(w / HP_PX),
            "px": [w, m["size"][1]],
            # The two degradations the design has to handle, as facts rather
            # than assumptions: whether we have a panel image, and whether we
            # know where its jacks are.
            "img": os.path.exists(png),
            "placed": bool(ports),
            "ports": ports,
        })
    return sorted(out, key=lambda d: d["slug"])


def as_js(mods: list) -> str:
    lines = ["// Real module geometry, measured from a running VCV Rack.",
             "// Generated by tools/rack/export_design_data.py — do not hand-edit.",
             "// hp and px are true; port x is a fraction of panel width, y is px",
             "// from the panel top; name is the vendor's own name for the port.",
             "const MODS = ["]
    for m in mods:
        ports = ", ".join(
            f"['{p['name']}',{p['x']},{p['y']},'{p['dir']}',{p['index']}]"
            for p in m["ports"])
        lines.append(
            f"  {{slug:'{m['slug']}', hp:{m['hp']}, px:{m['px'][0]},"
            f" img:{str(m['img']).lower()}, placed:{str(m['placed']).lower()},")
        lines.append(f"   ports:[{ports}]}},")
    lines.append("];")
    return "\n".join(lines)


def main(argv):
    mods = collect()
    if "--json" in argv:
        print(json.dumps(mods, indent=2))
        return 0
    print(as_js(mods))
    n_img = sum(1 for m in mods if m["img"])
    print(f"\n// {len(mods)} modules · {n_img} with a panel image · "
          f"{sum(len(m['ports']) for m in mods)} ports", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
