#!/usr/bin/env python3
"""Generate the acknowledgements notice from the idiom records themselves.

    python3 notice.py            # rewrite SOURCES.md
    python3 notice.py --check    # fail if SOURCES.md is stale
    python3 notice.py --stdout   # print it, write nothing

WHY GENERATED AND NEVER EDITED. A hand-written acknowledgements page is
accurate on the day it is written and drifts from then on: an idiom is added,
a citation is demoted by the anchor check, and the page still says what it said
last month. The counts are the part that drifts fastest and the part a reader
would most reasonably trust. So the page is derived, `--check` fails when it is
stale, and the file says so at the top -- if somebody can hand-edit it, the
numbers stop meaning anything.

WHY THE COUNTS ARE IN IT. "Derived from" over a library where most records were
written from general knowledge would be a stronger claim than the work
supports. Publishing 11 of 94 costs nothing and is the whole credibility of the
document: it says exactly how much of this came out of these books and how much
came out of the practice they describe.

NO SOURCE TEXT APPEARS HERE. The anchors quote the corpus so a citation can be
falsified; those quotes stay local. This is an acknowledgements page, not an
excerpt, and every work named is somebody else's copyrighted property.
"""

from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import idiom_check                                       # noqa: E402

OUT = os.path.join(HERE, "SOURCES.md")

BANNER = "<!-- generated by tools/rack/notice.py — do not edit by hand -->"

# Which work a citation is about, recognised from the `source` prose. Data, so
# adding a source is one line here rather than an edit to the prose of a
# generated page.
#
# The right-hand column is what the notice PRINTS. It is deliberately fuller
# than the match: a reader of an acknowledgements page should be able to find
# the work, and "Strange" is not enough to do that with.
WORKS = [
    (("synth secrets", "gordon reid"),
     "Gordon Reid, *Synth Secrets* (Sound On Sound, 1999–2004)"),
    (("patch & tweak", "bjørn", "bjorn & meyer"),
     "Kim Bjørn & Chris Meyer, *Patch & Tweak* (Bjooks)"),
    (("welsh",),
     "Fred Welsh, *Welsh's Synthesizer Cookbook*"),
    (("cookbook-sc", "microcosm"),
     "microcosm/cookbook-sc — Welsh's foundational chapters in SuperCollider"),
    (("strange",),
     "Allen Strange, *Electronic Music: Systems, Techniques and Controls*"),
    (("arp 2600", "2600"),
     "ARP 2600 — the instrument, and the practice that grew around it"),
    (("buchla",), "Don Buchla's instruments, and the low-pass gate"),
    (("make noise",), "Make Noise — the Maths function generator and its manual"),
    (("serge",), "Serge Tcherepnin's designs"),
    (("chowning",), "John Chowning's work on frequency modulation"),
    (("karplus",), "Karplus and Strong's plucked-string algorithm"),
    (("roads",), "Curtis Roads, *The Computer Music Tutorial*"),
    (("music thing",), "Tom Whitwell / Music Thing Modular — the Turing Machine"),
    (("hordijk",), "Rob Hordijk's Rungler and Benjolin"),
    (("todd barton", "barron"),
     "Todd Barton's Krell patch, after Louis and Bebe Barron"),
    (("toussaint",), "Godfried Toussaint's work on Euclidean rhythms"),
    (("tb-303", "acid house"), "The Roland TB-303, and the music made from it"),
    (("eno", "lanois"), "Brian Eno and Daniel Lanois — the shimmer technique"),
    (("reich",), "Steve Reich's phase music"),
    (("moog", "pearlman"), "Bob Moog and Alan R. Pearlman"),
]


def _work_for(source: str) -> str | None:
    low = source.lower()
    for keys, printed in WORKS:
        if any(k in low for k in keys):
            return printed
    return None


def render(idioms: dict | None = None) -> str:
    idioms = idioms if idioms is not None else idiom_check.load_idioms()
    tiers: dict[str, list] = {"read": [], "canon": [], "inferred": []}
    for slug, idiom in sorted(idioms.items()):
        tiers.setdefault(idiom.get("provenance", "canon"), []).append(idiom)

    derived: dict[str, list[str]] = {}
    for idiom in tiers["read"]:
        work = _work_for(idiom.get("source", "")) or idiom.get("source", "")
        derived.setdefault(work, []).append(idiom["slug"])

    tradition: dict[str, int] = {}
    unattributed = 0
    for idiom in tiers["canon"]:
        work = _work_for(idiom.get("source", ""))
        if work is None:
            unattributed += 1
        else:
            tradition[work] = tradition.get(work, 0) + 1

    total = sum(len(v) for v in tiers.values())
    out = [
        BANNER,
        "",
        "# Sources",
        "",
        "The patch idiom library describes techniques. Techniques and facts are",
        "not anybody's property, and the descriptions here are our own words --",
        "nothing is transcribed from any of the works below. This page records",
        "what informed the work, and is honest about how much.",
        "",
        f"Of **{total}** idioms: **{len(tiers['read'])}** were written from, or "
        f"checked against, a text we hold and quote; **{len(tiers['canon'])}** were "
        f"written from general knowledge of the practice; "
        f"**{len(tiers['inferred'])}** were reasoned out from adjacent technique. "
        "That first number is the only one under which a work can honestly be "
        "listed as a source, and it is the smaller number on purpose.",
        "",
        "## Derived from",
        "",
        "Each idiom below cites a passage, and a check confirms the citation",
        "quotes text that is really there. A citation that stops verifying is",
        "moved out of this section automatically.",
        "",
    ]
    if derived:
        for work in sorted(derived):
            slugs = ", ".join(f"`{s}`" for s in sorted(derived[work]))
            out.append(f"- {work}")
            out.append(f"  — {slugs}")
    else:
        out.append("- *(nothing yet)*")

    out += [
        "",
        "## In the tradition of",
        "",
        "These works describe the practice this library is built on. We have",
        "not verified a passage for the idioms below, and several of these",
        "works we could not obtain in a readable form at all; naming them is",
        "acknowledgement, not citation.",
        "",
    ]
    for work, n in sorted(tradition.items(), key=lambda kv: (-kv[1], kv[0])):
        out.append(f"- {work} — {n} idiom{'s' if n != 1 else ''}")
    if unattributed:
        out += [
            "",
            f"A further **{unattributed}** idioms record standard practice with",
            "no particular work behind them: the things every synthesist knows,",
            "which belong to nobody.",
        ]

    out += [
        "",
        "## How this page is kept honest",
        "",
        "It is generated from the records, by `tools/rack/notice.py`. The tier",
        "of each record is data; the anchor that justifies a *derived from*",
        "entry is data; the counts are counted. Editing this file by hand would",
        "let it drift from the library, so a test fails when it is stale.",
        "",
    ]
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--stdout" in argv:
        sys.stdout.write(text)
        return 0
    if "--check" in argv:
        have = open(OUT).read() if os.path.exists(OUT) else ""
        if have == text:
            print("  SOURCES.md matches the library")
            return 0
        print("  SOURCES.md is stale — regenerate with: python3 notice.py")
        return 1
    with open(OUT, "w") as f:
        f.write(text)
    print(f"  wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
