#!/usr/bin/env python3
"""Encode a single binary asset as a C++ source file for `pulp_add_binary_data`.

The CMake function vendors this script and invokes it once per source asset
through `add_custom_command(OUTPUT … COMMAND ${Python3_EXECUTABLE} … DEPENDS …)`,
so the encoder only re-runs when the input file (or this script) changes.

The generated symbols are link-compatible with the legacy in-CMake hex-loop
encoder (`size_t` and `std::size_t` are the same type after `<cstddef>`):

    namespace ${NAMESPACE} {
    extern const unsigned char ${VAR}[] = { 0x.., 0x.., ... };
    extern const std::size_t   ${VAR}_size = N;
    } // namespace ${NAMESPACE}

The `extern` is required so namespace-scope `const` definitions get
external linkage — without it the symbols would be invisible to the
companion header's `extern` declarations and the static library would
contain object files with no symbols.

Why a Python helper instead of `xxd -i`?
    * `xxd` is not part of the default Windows toolchain (it ships with Vim).
      Pulp's Windows CI runs MSVC + WinSDK; relying on `xxd` would gate this
      function on a developer setup detail.
    * Python is already a hard build dependency (find_package(Python3) is used
      elsewhere in the tree, e.g. tools/cli, bindings/python, tools/deps).
    * The encoder is small, deterministic, and easy to test.

Performance: encoding a 1 MB asset finishes in well under a second, versus
10–15 minutes for the legacy CMake `string(APPEND)` loop (issue #898).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


_BYTES_PER_ROW = 16


def _emit(src: Path, namespace: str, var_name: str, out: Path) -> None:
    data = src.read_bytes()

    lines: list[str] = []
    lines.append(f'// Auto-generated by tools/cmake/scripts/encode_binary_data.py — do not edit.')
    lines.append(f'// Source: {src.name}')
    lines.append('#include <cstddef>')
    lines.append('')
    lines.append(f'namespace {namespace} {{')
    # `extern` is required: namespace-scope `const` defaults to internal
    # linkage in C++, which would hide the symbol from the static-library
    # consumer that includes ${target}_data.hpp's `extern const …`
    # declaration.
    lines.append(f'extern const unsigned char {var_name}[] = {{')

    if not data:
        lines.append('};')
    else:
        for i in range(0, len(data), _BYTES_PER_ROW):
            chunk = data[i : i + _BYTES_PER_ROW]
            row = ', '.join(f'0x{b:02x}' for b in chunk)
            # Trailing comma on every row keeps the diff stable when the file grows.
            lines.append(f'    {row},')
        lines.append('};')

    lines.append(f'extern const std::size_t {var_name}_size = {len(data)};')
    lines.append(f'}}  // namespace {namespace}')
    lines.append('')

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines), encoding='utf-8')
    # The output's mtime must advance every time `add_custom_command` reruns
    # us, otherwise the build system sees the output as still-stale relative
    # to the (just-changed) input and immediately reruns us forever.
    # `write_text` already advances mtime, so no extra `touch()` is needed.


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--src', required=True, type=Path,
                        help='Path to the binary input file.')
    parser.add_argument('--out', required=True, type=Path,
                        help='Path to the .cpp file to write.')
    parser.add_argument('--namespace', required=True,
                        help='C++ namespace for the generated symbols.')
    parser.add_argument('--var', required=True,
                        help='Identifier for the byte array (and ${var}_size).')
    args = parser.parse_args(argv)

    if not args.src.is_file():
        print(f'encode_binary_data.py: input not found: {args.src}',
              file=sys.stderr)
        return 1

    _emit(args.src, args.namespace, args.var, args.out)
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
