#!/usr/bin/env python3
"""Coverage-matrix report renderer (roadmap P9-3).

Extracted from ``verifier.py`` as a focused validator-report module.
Turns the per-surface :class:`~tools.harness.adapters.base.Result` lists
into the two artefacts the harness publishes:

* :func:`render_markdown` — the human-readable coverage matrix mirrored to
  ``build/harness-coverage.md`` and ``docs/reports/harness-coverage.md``.
* :func:`render_json`     — the machine-readable
  ``build/harness-coverage-<sha>.json`` payload.

This is a pure mechanical move — the code is byte-identical to the
``verifier.py`` original. ``verifier.py`` re-imports both functions so
existing ``from tools.harness.verifier import render_json`` (etc.) call
sites keep working unchanged.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from tools.harness.adapters.base import Result
from tools.harness.status import STATUS_ORDER, StatusCounts


def render_markdown(
    results_by_surface: dict[str, list[Result]],
    sha: str,
    visual_counts: Optional[dict[str, dict]] = None,
    validation_counts: Optional[dict[str, dict]] = None,
) -> str:
    visual_counts = visual_counts or {}
    validation_counts = validation_counts or {}
    lines: list[str] = []
    lines.append("# Harness coverage")
    lines.append("")
    lines.append(
        f"_Auto-generated by `pulp harness coverage` — sha `{sha}` — "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}_"
    )
    lines.append("")
    lines.append("> See `tools/harness/README.md` for status taxonomy.")
    lines.append("> Drift = harness verdict disagrees with hand-edited `compat.json` status.")
    lines.append("")

    # ── Summary across all surfaces ──────────────────────────────────
    total_counts = StatusCounts.from_results(
        [r.status for results in results_by_surface.values() for r in results]
    )
    lines.append("## Summary")
    lines.append("")
    lines.append("| Surface | Total | PASS | NO-EV | DIVERGE | NO-OP | NOT-IMPL | OOS | PASS % | Progress % | Drift | Validation route | Visual covered |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for surface, results in results_by_surface.items():
        counts = StatusCounts.from_results([r.status for r in results])
        drifts = sum(1 for r in results if r.drifts)
        visual = visual_counts.get(surface, {"label": "0/0"})
        validation = validation_counts.get(surface, {"label": "0/0"})
        lines.append(
            "| `{}/` | {} | {} | {} | {} | {} | {} | {} | {:.1f}% | {:.1f}% | {} | {} | {} |".format(
                surface,
                counts.total,
                counts.pass_,
                counts.supported_no_evidence,
                counts.diverge,
                counts.no_op,
                counts.not_impl,
                counts.oos,
                counts.pass_pct,
                counts.progress_pct,
                drifts,
                validation["label"],
                visual["label"],
            )
        )
    if len(results_by_surface) > 1:
        all_drifts = sum(
            1
            for results in results_by_surface.values()
            for r in results
            if r.drifts
        )
        visual_pass = sum(int(v.get("pass", 0)) for v in visual_counts.values())
        visual_total = sum(int(v.get("total", 0)) for v in visual_counts.values())
        validation_pass = sum(int(v.get("pass", 0)) for v in validation_counts.values())
        validation_total = sum(int(v.get("total", 0)) for v in validation_counts.values())
        lines.append(
            "| **TOTAL** | {} | {} | {} | {} | {} | {} | {} | {:.1f}% | {:.1f}% | {} | {}/{} | {}/{} |".format(
                total_counts.total,
                total_counts.pass_,
                total_counts.supported_no_evidence,
                total_counts.diverge,
                total_counts.no_op,
                total_counts.not_impl,
                total_counts.oos,
                total_counts.pass_pct,
                total_counts.progress_pct,
                all_drifts,
                validation_pass,
                validation_total,
                visual_pass,
                visual_total,
            )
        )
    lines.append("")

    # ── Per-surface details ─────────────────────────────────────────
    for surface, results in results_by_surface.items():
        lines.append(f"## `{surface}/` — {len(results)} entries")
        lines.append("")
        # Bucket by status for readability.
        for st in STATUS_ORDER:
            bucket = [r for r in results if r.status is st]
            if not bucket:
                continue
            lines.append(f"### {st.value} ({len(bucket)})")
            lines.append("")
            lines.append("| Entry | Catalog | Drift | Detail |")
            lines.append("|---|---|---|---|")
            for r in bucket:
                drift_marker = "⚠" if r.drifts else ""
                detail = (r.detail or "").replace("|", "\\|")
                if len(detail) > 140:
                    detail = detail[:137] + "..."
                lines.append(
                    f"| `{r.entry.name}` | {r.entry.status or '—'} | {drift_marker} | {detail} |"
                )
            lines.append("")

        # Drift list per surface — entries where catalog disagrees.
        drifts = [r for r in results if r.drifts]
        if drifts:
            lines.append(f"### Drift list — `{surface}/` ({len(drifts)} entries)")
            lines.append("")
            lines.append("| Entry | Catalog says | Harness says | Why |")
            lines.append("|---|---|---|---|")
            for r in drifts:
                detail = (r.detail or "").replace("|", "\\|")
                if len(detail) > 120:
                    detail = detail[:117] + "..."
                lines.append(
                    f"| `{r.entry.name}` | {r.entry.status or '—'} ({r.entry.expected_status.value}) "
                    f"| {r.status.value} | {detail} |"
                )
            lines.append("")

    return "\n".join(lines)


def render_json(
    results_by_surface: dict[str, list[Result]],
    sha: str,
    visual_counts: Optional[dict[str, dict]] = None,
    validation_counts: Optional[dict[str, dict]] = None,
) -> dict:
    visual_counts = visual_counts or {}
    validation_counts = validation_counts or {}
    out_surfaces = {}
    for surface, results in results_by_surface.items():
        counts = StatusCounts.from_results([r.status for r in results])
        visual_coverage = visual_counts.get(surface, {"pass": 0, "total": 0, "label": "0/0"})
        validation_routes = validation_counts.get(surface, {"pass": 0, "total": 0, "label": "0/0"})
        out_surfaces[surface] = {
            "total": counts.total,
            "pass": counts.pass_,
            "supported_no_evidence": counts.supported_no_evidence,
            "diverge": counts.diverge,
            "no_op": counts.no_op,
            "not_impl": counts.not_impl,
            "oos": counts.oos,
            "pass_pct": round(counts.pass_pct, 2),
            "progress_pct": round(counts.progress_pct, 2),
            "drift_count": sum(1 for r in results if r.drifts),
            "validation_routes": validation_routes,
            "visual_coverage": visual_coverage,
            "visual_pass": visual_coverage,
            "results": [r.to_dict() for r in results],
        }
    total_counts = StatusCounts.from_results(
        [r.status for results in results_by_surface.values() for r in results]
    )
    visual_pass = sum(int(v.get("pass", 0)) for v in visual_counts.values())
    visual_total = sum(int(v.get("total", 0)) for v in visual_counts.values())
    validation_pass = sum(int(v.get("pass", 0)) for v in validation_counts.values())
    validation_total = sum(int(v.get("total", 0)) for v in validation_counts.values())
    validation_routes = {
        "pass": validation_pass,
        "total": validation_total,
        "label": f"{validation_pass}/{validation_total}" if validation_total else f"{validation_pass}/0",
    }
    visual_coverage = {
        "pass": visual_pass,
        "total": visual_total,
        "label": f"{visual_pass}/{visual_total}" if visual_total else f"{visual_pass}/0",
    }
    return {
        "schema_version": "0.2",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "sha": sha,
        "totals": {
            "total": total_counts.total,
            "pass": total_counts.pass_,
            "supported_no_evidence": total_counts.supported_no_evidence,
            "diverge": total_counts.diverge,
            "no_op": total_counts.no_op,
            "not_impl": total_counts.not_impl,
            "oos": total_counts.oos,
            "pass_pct": round(total_counts.pass_pct, 2),
            "progress_pct": round(total_counts.progress_pct, 2),
            "drift_count": sum(
                1
                for results in results_by_surface.values()
                for r in results
                if r.drifts
            ),
            "validation_routes": validation_routes,
            "visual_coverage": visual_coverage,
            "visual_pass": visual_coverage,
        },
        "surfaces": out_surfaces,
    }
