# Browser GPU-audio lane: the submit/collect WebGpuConvolver (native unit tests,
# real Dawn device) and the Skia-free wasm worker module (emcc build smoke +
# a symbol-level guard on the link inputs).

# ── WebGpuConvolver ────────────────────────────────────────────────────────
# Plain C++ over the GpuCompute interface, so it is tested NATIVELY against a
# real device even though its reason to exist is a browser worker. With no compute
# device the cases SKIP (Catch2's SKIP, which reports out loud) — never a bare
# early return, which Catch2 would record as a pass.
if(PULP_ENABLE_GPU AND TARGET pulp::render)
    pulp_add_test_suite(pulp-test-web-gpu-convolver
        SOURCES test_web_gpu_convolver.cpp harness/rt_allocation_probe.cpp
        LIBRARIES pulp::gpu-audio pulp::render pulp::audio
        DISCOVERY_ARGS ${PULP_GPU_TEST_DISCOVERY_ARGS})
endif()

# ── pulp-gpu-dsp (wasm) ────────────────────────────────────────────────────
# Two CTests over the emcc build of examples/web-demos/gpu-audio:
#
#   ...wasm-build  — the module compiles and links under emsdk + emdawnwebgpu.
#   ...skia-free   — NO Skia symbol reaches the link. The property is load-bearing,
#                    not cosmetic: the worker's job is an FFT, and a DSP module
#                    that drags in Skia/Graphite re-couples the audio path to the
#                    UI's GPU stack and balloons the worker download. It is
#                    checked on the OBJECT FILES (which keep symbol names at -O2,
#                    unlike the linked wasm) and on the generated compile/link
#                    lines — so neither a stray source added to PulpGpuWasm.cmake
#                    nor a stray -DSKIA_DIR can slip past it.
#
# Both SKIP (exit 77) with a stated reason when emsdk is absent — never a silent
# pass. The driver is generated rather than committed because it is pure build
# plumbing with no meaning outside this test registration.
#
# OPT-IN (default OFF), and that is not timidity: registering them unconditionally
# would drag a foreign toolchain — and, on a cold EM_CACHE, a network download of
# the emdawnwebgpu package — into the DEFAULT `ctest --test-dir build` run of every
# developer who happens to have ~/emsdk, and into the warm build dirs of the
# self-hosted runners that carry the required `macos` gate. CI builds this module
# explicitly (.github/workflows/web-plugins.yml), so nothing is lost by keeping it
# out of the native suite. Turn it on with -DPULP_BUILD_WASM_TESTS=ON; the two
# tests also carry the `wasm` label, so `ctest -LE wasm` excludes them even then.
option(PULP_BUILD_WASM_TESTS
       "Register the Emscripten (wasm) build smoke tests in CTest" OFF)

if(UNIX AND PULP_BUILD_WASM_TESTS)
    set(_gpu_dsp_work "${CMAKE_CURRENT_BINARY_DIR}/gpu-dsp-wasm")
    set(_gpu_dsp_driver "${CMAKE_CURRENT_BINARY_DIR}/gpu_dsp_wasm_check.sh")

    file(WRITE "${_gpu_dsp_driver}" [=[#!/usr/bin/env bash
# Generated by test/cmake/gpu_audio_web_tests.cmake — do not edit.
# usage: gpu_dsp_wasm_check.sh <build|skia-free> <pulp_root> <work_dir>
set -uo pipefail

MODE="$1"; PULP_ROOT="$2"; WORK="$3"
EMSDK_DIR="${EMSDK:-$HOME/emsdk}"

if [ ! -f "$EMSDK_DIR/emsdk_env.sh" ]; then
    echo "SKIP: emsdk not installed (no $EMSDK_DIR/emsdk_env.sh; set EMSDK to override)"
    exit 77
fi
# shellcheck disable=SC1091
if ! source "$EMSDK_DIR/emsdk_env.sh" >/dev/null 2>&1; then
    echo "SKIP: $EMSDK_DIR/emsdk_env.sh could not be sourced"
    exit 77
fi

case "$MODE" in
build)
    # The first build downloads the emdawnwebgpu package into EM_CACHE.
    emcmake cmake -S "$PULP_ROOT/examples/web-demos/gpu-audio" -B "$WORK" \
        -DCMAKE_BUILD_TYPE=Release || exit 1
    cmake --build "$WORK" -j "$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)" || exit 1
    [ -f "$WORK/pulp-gpu-dsp.js" ] || { echo "FAIL: no pulp-gpu-dsp.js emitted"; exit 1; }
    [ -f "$WORK/pulp-gpu-dsp.wasm" ] || { echo "FAIL: no pulp-gpu-dsp.wasm emitted"; exit 1; }
    ;;
skia-free)
    # bash 3.2 (macOS's /bin/bash) has no mapfile — read the list the portable way.
    OBJS=()
    while IFS= read -r _o; do OBJS+=("$_o"); done < <(find "$WORK" -name '*.o' 2>/dev/null)
    if [ "${#OBJS[@]}" -eq 0 ]; then
        echo "SKIP: no pulp-gpu-dsp objects (the wasm build smoke did not run)"
        exit 77
    fi
    NM="$EMSDK_DIR/upstream/bin/llvm-nm"
    [ -x "$NM" ] || NM="$(command -v llvm-nm || true)"
    [ -n "$NM" ] || { echo "SKIP: llvm-nm not found in the emsdk"; exit 77; }

    HITS="$("$NM" "${OBJS[@]}" 2>/dev/null \
        | grep -E '(^| )_?(Sk[A-Z][A-Za-z]|GrDirectContext|skgpu|SkiaSurface)' || true)"
    if [ -n "$HITS" ]; then
        echo "FAIL: Skia symbols reached the pulp-gpu-dsp link:"
        echo "$HITS" | head -20
        exit 1
    fi

    FLAGS="$(grep -rIl -e 'skia' -e 'SKIA_DIR' "$WORK/CMakeFiles" 2>/dev/null || true)"
    if [ -n "$FLAGS" ]; then
        echo "FAIL: Skia appears in the pulp-gpu-dsp build flags:"
        echo "$FLAGS" | head -10
        exit 1
    fi
    ;;
*)
    echo "usage: $0 <build|skia-free> <pulp_root> <work_dir>"; exit 2 ;;
esac
]=])

    add_test(NAME pulp-gpu-dsp-wasm-build
        COMMAND bash "${_gpu_dsp_driver}" build "${CMAKE_SOURCE_DIR}" "${_gpu_dsp_work}")
    set_tests_properties(pulp-gpu-dsp-wasm-build PROPERTIES
        SKIP_RETURN_CODE 77
        FIXTURES_SETUP gpu_dsp_wasm
        LABELS wasm
        TIMEOUT 1800)

    add_test(NAME pulp-gpu-dsp-skia-free
        COMMAND bash "${_gpu_dsp_driver}" skia-free "${CMAKE_SOURCE_DIR}" "${_gpu_dsp_work}")
    set_tests_properties(pulp-gpu-dsp-skia-free PROPERTIES
        SKIP_RETURN_CODE 77
        FIXTURES_REQUIRED gpu_dsp_wasm
        LABELS wasm
        TIMEOUT 300)
endif()
