#!/usr/bin/env python3
"""Emit the interchange concept vocabulary and per-format capability tables.

Three pure projections of the committed JSON under
`core/interchange/capabilities/`, each printed to stdout and each guarded by the
shared `tools/scripts/schema_drift_check.py` gate:

    capability_emit.py --emit concepts   # generated/concepts.hpp
    capability_emit.py --emit tables     # generated/capability_tables.hpp
    capability_emit.py --emit docs       # docs/reference/interchange-matrix.md

The tables projection materializes the closed world: every concept gets a row
for every format. A concept a format's JSON does not list is emitted as `none`
on import (refuse) and `drop` on export (a loss requiring consent). Absence in
the data is therefore not a hole in the table that C++ has to handle at runtime
-- it is a decision the generator writes down.

Exit codes: 0 emitted, 2 malformed input.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_THIS = Path(__file__).resolve()
_CAPABILITY_DIR = _THIS.parents[1] / "capabilities"

IMPORT_LEVELS = ("none", "preserve-opaque", "partial", "full")
EXPORT_LEVELS = ("drop", "roundtrip-only", "degrade", "full")
LOSS_CLASSES = ("dropped", "degraded", "flattened", "approximated")
DETECT_KINDS = ("model", "format")

GENERATED_BANNER = (
    "// Generated by core/interchange/tools/capability_emit.py -- do not edit.\n"
    "// Source of truth: core/interchange/capabilities/*.json\n"
)


class EmitError(Exception):
    """Malformed capability data."""


def enumerator_for(concept_id: str) -> str:
    """`automation.device-param` -> `AutomationDeviceParam`."""
    parts = [part for chunk in concept_id.split(".") for part in chunk.split("-")]
    if not all(parts):
        raise EmitError(f"concept id has an empty segment: {concept_id!r}")
    return "".join(part[:1].upper() + part[1:] for part in parts)


def load_concepts(capability_dir: Path) -> list[dict]:
    path = capability_dir / "concepts.json"
    data = json.loads(path.read_text())
    concepts = data.get("concepts")
    if not isinstance(concepts, list) or not concepts:
        raise EmitError(f"{path}: 'concepts' must be a non-empty list")

    seen_ids: set[str] = set()
    seen_enums: set[str] = set()
    for concept in concepts:
        cid = concept.get("id")
        if not isinstance(cid, str) or not cid:
            raise EmitError(f"{path}: every concept needs a non-empty string 'id'")
        if cid in seen_ids:
            raise EmitError(f"{path}: duplicate concept id {cid!r}")
        seen_ids.add(cid)
        enum = enumerator_for(cid)
        if enum in seen_enums:
            raise EmitError(f"{path}: concept id {cid!r} collides on enumerator {enum!r}")
        seen_enums.add(enum)
        if concept.get("detect") not in DETECT_KINDS:
            raise EmitError(
                f"{path}: concept {cid!r} needs 'detect' in {DETECT_KINDS}"
            )
        if not isinstance(concept.get("summary"), str) or not concept["summary"]:
            raise EmitError(f"{path}: concept {cid!r} needs a non-empty 'summary'")
        concept["enumerator"] = enum

    if concepts[0]["id"] != "unknown":
        raise EmitError(
            f"{path}: 'unknown' must be the first concept so it is the enum's zero value"
        )
    return concepts


def load_formats(capability_dir: Path, concept_ids: set[str]) -> list[dict]:
    formats = []
    seen_formats: set[str] = set()
    seen_enums: set[str] = set()
    seen_ordinals: set[int] = set()
    for path in sorted(capability_dir.glob("*.json")):
        if path.name == "concepts.json":
            continue
        data = json.loads(path.read_text())
        name = data.get("format")
        if not isinstance(name, str) or not name:
            raise EmitError(f"{path}: 'format' must be a non-empty string")
        if name in seen_formats:
            raise EmitError(f"{path}: duplicate format id {name!r}")
        seen_formats.add(name)
        enum = data.get("enumerator")
        if not isinstance(enum, str) or not enum.isidentifier():
            raise EmitError(f"{path}: 'enumerator' must be a C++ identifier")
        if enum in seen_enums:
            raise EmitError(f"{path}: duplicate enumerator {enum!r}")
        seen_enums.add(enum)
        ordinal = data.get("ordinal")
        if isinstance(ordinal, bool) or not isinstance(ordinal, int) or ordinal < 0:
            raise EmitError(f"{path}: 'ordinal' must be a non-negative integer")
        if ordinal in seen_ordinals:
            raise EmitError(f"{path}: duplicate format ordinal {ordinal}")
        seen_ordinals.add(ordinal)
        if not isinstance(data.get("display_name"), str) or not data["display_name"]:
            raise EmitError(f"{path}: 'display_name' must be a non-empty string")
        if not isinstance(data.get("writer"), bool):
            raise EmitError(f"{path}: 'writer' must be a bool")

        for section, levels in (("import", IMPORT_LEVELS), ("export", EXPORT_LEVELS)):
            rows = data.get(section)
            if not isinstance(rows, dict):
                raise EmitError(f"{path}: '{section}' must be an object")
            for cid, row in rows.items():
                if cid not in concept_ids:
                    raise EmitError(
                        f"{path}: {section} row {cid!r} is not in the concept vocabulary"
                    )
                if row.get("level") not in levels:
                    raise EmitError(
                        f"{path}: {section} row {cid!r} needs 'level' in {levels}"
                    )
                if section == "export":
                    if row["level"] == "degrade":
                        if row.get("to") not in concept_ids:
                            raise EmitError(
                                f"{path}: export row {cid!r} degrades to an unknown concept"
                            )
                    elif "to" in row:
                        raise EmitError(
                            f"{path}: export row {cid!r} names a degrade target "
                            f"but its level is {row['level']!r}"
                        )
                    if row["level"] in ("degrade", "drop"):
                        if row.get("loss_class") not in LOSS_CLASSES:
                            raise EmitError(
                                f"{path}: export row {cid!r} needs "
                                f"'loss_class' in {LOSS_CLASSES}"
                            )
                        if not isinstance(row.get("loss"), str) or not row["loss"]:
                            raise EmitError(
                                f"{path}: export row {cid!r} needs a non-empty 'loss'"
                            )
        data["path"] = path
        formats.append(data)
    if not formats:
        raise EmitError(f"{capability_dir}: no format capability files found")
    formats.sort(key=lambda fmt: fmt["ordinal"])
    ordinals = [fmt["ordinal"] for fmt in formats]
    if ordinals != list(range(len(formats))):
        raise EmitError(
            f"{capability_dir}: format ordinals must be contiguous from zero; got {ordinals}"
        )
    return formats


def cxx_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit_concepts(concepts: list[dict]) -> str:
    out = [GENERATED_BANNER, "#pragma once\n\n"]
    out.append("#include <cstddef>\n#include <cstdint>\n#include <string_view>\n\n")
    out.append("namespace pulp::interchange {\n\n")
    out.append(
        "/// The format-neutral interchange concept vocabulary. Append-only:\n"
        "/// committed format tables are written against these names.\n"
        "enum class Concept : std::uint16_t {\n"
    )
    for index, concept in enumerate(concepts):
        out.append(f"    {concept['enumerator']} = {index},\n")
    out.append("};\n\n")
    out.append(f"inline constexpr std::size_t kConceptCount = {len(concepts)};\n\n")

    out.append("namespace detail {\n")
    out.append("struct ConceptRecord {\n")
    out.append("    std::string_view id;\n")
    out.append("    std::string_view summary;\n")
    out.append("    bool detectable_in_model;\n")
    out.append("};\n\n")
    out.append(
        "inline constexpr ConceptRecord kConceptRecords[kConceptCount] = {\n"
    )
    for concept in concepts:
        detectable = "true" if concept["detect"] == "model" else "false"
        out.append(
            f"    {{{cxx_string(concept['id'])}, "
            f"{cxx_string(concept['summary'])}, {detectable}}},\n"
        )
    out.append("};\n} // namespace detail\n\n")

    out.append(
        "/// The concept's stable string id, as written in the capability JSON.\n"
        "constexpr std::string_view concept_id(Concept concept_value) noexcept {\n"
        "    return detail::kConceptRecords[static_cast<std::size_t>(concept_value)].id;\n"
        "}\n\n"
        "/// One-line description of what the concept covers.\n"
        "constexpr std::string_view concept_summary(Concept concept_value) noexcept {\n"
        "    return detail::kConceptRecords[static_cast<std::size_t>(concept_value)].summary;\n"
        "}\n\n"
        "/// Whether a census over a timeline Project can observe this concept.\n"
        "/// Concepts that exist only in some interchange format are never recorded.\n"
        "constexpr bool concept_detectable_in_model(Concept concept_value) noexcept {\n"
        "    return detail::kConceptRecords[static_cast<std::size_t>(concept_value)]\n"
        "        .detectable_in_model;\n"
        "}\n\n"
        "/// Resolve a string id to its concept. Unrecognized ids yield\n"
        "/// Concept::Unknown, which no format lists as importable.\n"
        "constexpr Concept concept_from_id(std::string_view id) noexcept {\n"
        "    for (std::size_t index = 0; index < kConceptCount; ++index) {\n"
        "        if (detail::kConceptRecords[index].id == id)\n"
        "            return static_cast<Concept>(index);\n"
        "    }\n"
        "    return Concept::Unknown;\n"
        "}\n\n"
    )
    out.append("} // namespace pulp::interchange\n")
    return "".join(out)


def emit_tables(concepts: list[dict], formats: list[dict]) -> str:
    out = [GENERATED_BANNER, "#pragma once\n\n"]
    out.append('#include <pulp/interchange/concept.hpp>\n\n')
    out.append("#include <cstddef>\n#include <cstdint>\n#include <string_view>\n\n")
    out.append("namespace pulp::interchange {\n\n")

    out.append("/// How much of a concept a format's reader admits.\n")
    out.append("enum class ImportLevel : std::uint8_t {\n")
    for index, level in enumerate(IMPORT_LEVELS):
        out.append(f"    {enumerator_for(level)} = {index},\n")
    out.append("};\n\n")

    out.append("/// What a format's writer does with a concept the document uses.\n")
    out.append("enum class ExportLevel : std::uint8_t {\n")
    for index, level in enumerate(EXPORT_LEVELS):
        out.append(f"    {enumerator_for(level)} = {index},\n")
    out.append("};\n\n")

    out.append("/// How a concept is lost when a format cannot carry it intact.\n")
    out.append("enum class LossClass : std::uint8_t {\n")
    for index, loss in enumerate(LOSS_CLASSES):
        out.append(f"    {enumerator_for(loss)} = {index},\n")
    out.append("};\n\n")

    out.append("/// Interchange formats with a committed capability declaration.\n")
    out.append("enum class Format : std::uint8_t {\n")
    for fmt in formats:
        out.append(f"    {fmt['enumerator']} = {fmt['ordinal']},\n")
    out.append("};\n\n")
    out.append(f"inline constexpr std::size_t kFormatCount = {len(formats)};\n\n")

    out.append("struct ImportRow {\n")
    out.append("    ImportLevel level;\n")
    out.append("    /// How the reader converts a partial or opaque concept.\n")
    out.append("    std::string_view notes;\n")
    out.append("    /// What the refusal message names. Empty unless level is None.\n")
    out.append("    std::string_view refusal;\n")
    out.append("};\n\n")

    out.append("struct ExportRow {\n")
    out.append("    ExportLevel level;\n")
    out.append("    /// The concept a degrade lands on. Meaningful only for Degrade.\n")
    out.append("    Concept degrade_to;\n")
    out.append("    LossClass loss_class;\n")
    out.append("    /// What the loss manifest reports. Empty when nothing is lost.\n")
    out.append("    std::string_view loss;\n")
    out.append("};\n\n")

    out.append("namespace detail {\n")
    out.append("struct FormatRecord {\n")
    out.append("    std::string_view id;\n")
    out.append("    std::string_view display_name;\n")
    out.append("    bool has_writer;\n")
    out.append("};\n\n")
    out.append("inline constexpr FormatRecord kFormatRecords[kFormatCount] = {\n")
    for fmt in formats:
        writer = "true" if fmt["writer"] else "false"
        out.append(
            f"    {{{cxx_string(fmt['format'])}, "
            f"{cxx_string(fmt['display_name'])}, {writer}}},\n"
        )
    out.append("};\n\n")

    # Closed world: every format gets a row for every concept. An absent import
    # row is None (refuse); an absent export row is Drop (a consented loss).
    out.append(
        "inline constexpr ImportRow kImportRows[kFormatCount][kConceptCount] = {\n"
    )
    for fmt in formats:
        out.append(f"    // {fmt['format']}\n    {{\n")
        for concept in concepts:
            row = fmt["import"].get(concept["id"])
            if row is None:
                level, notes, refusal = "None", "", ""
            else:
                level = enumerator_for(row["level"])
                notes = row.get("notes", "")
                refusal = row.get("refusal", "")
            out.append(
                f"        {{ImportLevel::{level}, {cxx_string(notes)}, "
                f"{cxx_string(refusal)}}}, // {concept['id']}\n"
            )
        out.append("    },\n")
    out.append("};\n\n")

    out.append(
        "inline constexpr ExportRow kExportRows[kFormatCount][kConceptCount] = {\n"
    )
    for fmt in formats:
        out.append(f"    // {fmt['format']}\n    {{\n")
        for concept in concepts:
            row = fmt["export"].get(concept["id"])
            if row is None:
                level, to, loss_class = "Drop", "Unknown", "Dropped"
                loss = f"{fmt['display_name']} declares no support for {concept['id']}"
            else:
                level = enumerator_for(row["level"])
                to = enumerator_for(row["to"]) if "to" in row else "Unknown"
                loss_class = enumerator_for(row.get("loss_class", "dropped"))
                loss = row.get("loss", "")
            out.append(
                f"        {{ExportLevel::{level}, Concept::{to}, "
                f"LossClass::{loss_class}, {cxx_string(loss)}}}, // {concept['id']}\n"
            )
        out.append("    },\n")
    out.append("};\n} // namespace detail\n\n")

    out.append(
        "/// The format's stable string id.\n"
        "constexpr std::string_view format_id(Format format) noexcept {\n"
        "    return detail::kFormatRecords[static_cast<std::size_t>(format)].id;\n"
        "}\n\n"
        "/// The format's human-facing name.\n"
        "constexpr std::string_view format_display_name(Format format) noexcept {\n"
        "    return detail::kFormatRecords[static_cast<std::size_t>(format)].display_name;\n"
        "}\n\n"
        "/// Whether a writer exists for this format. run_export refuses without one.\n"
        "constexpr bool format_has_writer(Format format) noexcept {\n"
        "    return detail::kFormatRecords[static_cast<std::size_t>(format)].has_writer;\n"
        "}\n\n"
        "/// Resolve a string id to its format. Returns false when unrecognized.\n"
        "constexpr bool format_from_id(std::string_view id, Format& out) noexcept {\n"
        "    for (std::size_t index = 0; index < kFormatCount; ++index) {\n"
        "        if (detail::kFormatRecords[index].id == id) {\n"
        "            out = static_cast<Format>(index);\n"
        "            return true;\n"
        "        }\n"
        "    }\n"
        "    return false;\n"
        "}\n\n"
        "/// The format's import declaration for one concept. Every concept has a\n"
        "/// row: concepts the format's JSON omits are generated as None.\n"
        "constexpr const ImportRow& import_capability(Format format,\n"
        "                                             Concept concept_value) noexcept {\n"
        "    return detail::kImportRows[static_cast<std::size_t>(format)]\n"
        "                             [static_cast<std::size_t>(concept_value)];\n"
        "}\n\n"
        "/// The format's export declaration for one concept, generated the same way\n"
        "/// (omitted concepts become Drop, so they surface as a loss needing consent).\n"
        "constexpr const ExportRow& export_capability(Format format,\n"
        "                                             Concept concept_value) noexcept {\n"
        "    return detail::kExportRows[static_cast<std::size_t>(format)]\n"
        "                             [static_cast<std::size_t>(concept_value)];\n"
        "}\n\n"
        "/// Whether the format's reader may admit the concept at all. This is the\n"
        "/// single decision every import refusal site derives from.\n"
        "constexpr bool import_supports(Format format, Concept concept_value) noexcept {\n"
        "    return import_capability(format, concept_value).level != ImportLevel::None;\n"
        "}\n\n"
        "/// Whether exporting the concept costs the document anything.\n"
        "constexpr bool export_is_lossless(Format format, Concept concept_value) noexcept {\n"
        "    const ExportLevel level = export_capability(format, concept_value).level;\n"
        "    return level == ExportLevel::Full || level == ExportLevel::RoundtripOnly;\n"
        "}\n\n"
    )
    out.append(
        "static_assert(static_cast<std::size_t>(Concept::Unknown) == 0,\n"
        "              \"Concept::Unknown must be the zero value so a reader that cannot\"\n"
        "              \" classify a construct refuses by default\");\n\n"
    )
    out.append("} // namespace pulp::interchange\n")
    return "".join(out)


def emit_docs(concepts: list[dict], formats: list[dict]) -> str:
    out = [
        "<!-- Generated by core/interchange/tools/capability_emit.py -- do not edit. -->\n",
        "<!-- Source of truth: core/interchange/capabilities/*.json -->\n\n",
        "# Interchange capability matrix\n\n",
        "What each interchange format can carry, per concept. The tables below are\n",
        "generated from the same JSON the C++ capability tables are generated from,\n",
        "so a row here is the behavior, not a description of it.\n\n",
        "The world is closed. A concept a format does not list is refused on import\n",
        "and reported as a loss on export -- support is something a format declares,\n",
        "never something it gets by default.\n\n",
        "A row changes away from `none` only through a decision made on the\n",
        "document model's own merits. Turning rows green to widen a format's reach\n",
        "is not a reason to add a model feature.\n\n",
    ]

    out.append("## Concepts\n\n")
    out.append("| Concept | Observable in a document | Meaning |\n")
    out.append("|---|---|---|\n")
    for concept in concepts:
        detect = "yes" if concept["detect"] == "model" else "format-only"
        out.append(f"| `{concept['id']}` | {detect} | {concept['summary']} |\n")
    out.append("\n")

    for fmt in formats:
        out.append(f"## {fmt['display_name']}\n\n")
        writer = "yes" if fmt["writer"] else "no -- `run_export` refuses"
        out.append(f"Format id `{fmt['format']}`. Writer registered: {writer}.\n\n")

        out.append("### Import\n\n")
        out.append("| Concept | Level | Detail |\n|---|---|---|\n")
        for concept in concepts:
            row = fmt["import"].get(concept["id"])
            if row is None:
                out.append(f"| `{concept['id']}` | none | not declared |\n")
                continue
            detail = row.get("notes") or row.get("refusal") or ""
            out.append(f"| `{concept['id']}` | {row['level']} | {detail} |\n")
        out.append("\n")

        out.append("### Export\n\n")
        out.append("| Concept | Level | Becomes | Loss class | Detail |\n")
        out.append("|---|---|---|---|---|\n")
        for concept in concepts:
            row = fmt["export"].get(concept["id"])
            if row is None:
                out.append(
                    f"| `{concept['id']}` | drop | | dropped | not declared |\n"
                )
                continue
            becomes = f"`{row['to']}`" if "to" in row else ""
            loss_class = row.get("loss_class", "")
            out.append(
                f"| `{concept['id']}` | {row['level']} | {becomes} "
                f"| {loss_class} | {row.get('loss', '')} |\n"
            )
        out.append("\n")

    out.append("## Adding a format\n\n")
    out.append(
        "1. Write `core/interchange/capabilities/<format>.json` declaring the next\n"
        "   stable contiguous `ordinal`, an `enumerator`, a `display_name`, a\n"
        "   `writer` flag, and the `import` and\n"
        "   `export` rows the format supports.\n"
        "2. Regenerate: `capability_emit.py --emit concepts|tables|docs`, or let\n"
        "   the drift gate print the diff.\n"
        "3. Write the reader and writer in their own target, deriving every\n"
        "   refusal from `import_supports` and every loss from the export rows.\n\n"
        "Nothing in `core/interchange` changes.\n"
    )
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", choices=("concepts", "tables", "docs"), required=True)
    parser.add_argument("--capabilities", type=Path, default=_CAPABILITY_DIR)
    args = parser.parse_args(argv)

    try:
        concepts = load_concepts(args.capabilities)
        formats = load_formats(args.capabilities, {c["id"] for c in concepts})
    except (EmitError, json.JSONDecodeError, OSError) as exc:
        print(f"capability-emit: {exc}", file=sys.stderr)
        return 2

    if args.emit == "concepts":
        sys.stdout.write(emit_concepts(concepts))
    elif args.emit == "tables":
        sys.stdout.write(emit_tables(concepts, formats))
    else:
        sys.stdout.write(emit_docs(concepts, formats))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
