if(NOT EXISTS "${ARTIFACT}" OR NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "inspector shipping scan requires ARTIFACT and MANIFEST")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/PulpInspectorShipping.cmake")
file(READ "${ARTIFACT}" _binary HEX)
file(READ "${MANIFEST}" _manifest)
string(FIND "${_manifest}" "\"schema\": \"dev.pulp.control/artifact-manifest@1\"" _control_schema)
string(HEX "PULP_STANDALONE_COMPONENT_V1" _standalone_hex)
string(FIND "${_binary}" "${_standalone_hex}" _standalone_pos)
if(_standalone_pos LESS 0)
    message(FATAL_ERROR "inspector capability manifest is not paired with a Pulp standalone artifact")
endif()
if(_control_schema GREATER_EQUAL 0)
    foreach(_profile IN ITEMS
            production-stripped developer-local test-deterministic
            support-diagnostics research-unsafe)
        string(FIND "${_manifest}" "\"profile\": \"${_profile}\"" _profile_declared)
        string(MAKE_C_IDENTIFIER "${_profile}" _profile_identifier)
        string(TOUPPER "${_profile_identifier}" _profile_identifier)
        string(HEX "PULP_CONTROL_PROFILE_${_profile_identifier}_V1" _profile_hex)
        string(FIND "${_binary}" "${_profile_hex}" _profile_binary)
        if(_profile_declared GREATER_EQUAL 0 AND _profile_binary LESS 0)
            message(FATAL_ERROR "declared control profile marker is absent: ${_profile}")
        elseif(_profile_declared LESS 0 AND _profile_binary GREATER_EQUAL 0)
            message(FATAL_ERROR "binary contains undeclared control profile marker: ${_profile}")
        endif()
    endforeach()

    string(SHA256 _manifest_digest "${_manifest}")
    string(HEX "PULP_CONTROL_MANIFEST_SHA256_${_manifest_digest}_V1" _digest_hex)
    string(FIND "${_binary}" "${_digest_hex}" _digest_binary)
    if(_digest_binary LESS 0)
        message(FATAL_ERROR "control manifest digest marker is absent or stale")
    endif()

    string(FIND "${_manifest}" "\"profile\": \"production-stripped\"" _stripped_profile)
    string(HEX "PULP_REMOTE_VIEW_PARAMETER_AUTHORITY_V1" _remote_view_hex)
    string(FIND "${_binary}" "${_remote_view_hex}" _remote_view_binary)
    if(_stripped_profile GREATER_EQUAL 0 AND _remote_view_binary GREATER_EQUAL 0)
        message(FATAL_ERROR
            "production-stripped artifact contains Remote View parameter authority")
    endif()
endif()

string(FIND "${_manifest}" "\"unsafe_runtime_eval_acknowledged\": true" _eval_declared)
string(HEX "PULP_INSPECT_RUNTIME_EVAL_HIGH_RISK_COMPONENT_V1" _eval_hex)
string(FIND "${_binary}" "${_eval_hex}" _eval_binary)
if(_eval_declared GREATER_EQUAL 0 AND _eval_binary LESS 0)
    message(FATAL_ERROR "runtime.eval acknowledgement is present but high-risk component marker is absent")
elseif(_eval_declared LESS 0 AND _eval_binary GREATER_EQUAL 0)
    message(FATAL_ERROR "high-risk runtime.eval component is present without its separate acknowledgement")
endif()
