if(NOT EXISTS "${ARTIFACT}" OR NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "inspector shipping scan requires ARTIFACT and MANIFEST")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/PulpInspectorShipping.cmake")
file(READ "${ARTIFACT}" _binary HEX)
file(READ "${MANIFEST}" _manifest)
string(FIND "${_manifest}" "\"schema\": \"dev.pulp.control/artifact-manifest@1\"" _control_schema)
string(HEX "PULP_STANDALONE_COMPONENT_V1" _standalone_hex)
string(FIND "${_binary}" "${_standalone_hex}" _standalone_pos)
if(_standalone_pos LESS 0)
    message(FATAL_ERROR "inspector capability manifest is not paired with a Pulp standalone artifact")
endif()
string(HEX "PULP_INSPECT_SHIPPING_MANIFEST_V1" _shipping_hex)
string(FIND "${_binary}" "${_shipping_hex}" _shipping_pos)
string(FIND "${_manifest}" "\"endpoint_included\": true" _declared_pos)
if(_declared_pos LESS 0 AND _control_schema LESS 0)
    string(FIND "${_manifest}" "\"shipping_override\": true" _declared_pos)
endif()
if(_declared_pos GREATER_EQUAL 0 AND _shipping_pos LESS 0)
    message(FATAL_ERROR "manifest declares an inspector endpoint but binary marker is absent")
elseif(_declared_pos LESS 0 AND _shipping_pos GREATER_EQUAL 0)
    message(FATAL_ERROR "binary contains an inspector endpoint marker but manifest does not declare it")
endif()

foreach(_cap IN LISTS _PULP_INSPECTOR_SHIPPING_CAPABILITIES)
    _pulp_control_capability_projection(_legacy_cap _contract_cap "${_cap}")
    if(_control_schema GREATER_EQUAL 0)
        string(FIND "${_manifest}" "\"${_contract_cap}\"" _cap_declared)
    else()
        string(FIND "${_manifest}" "\"${_legacy_cap}\"" _cap_declared)
    endif()
    string(MAKE_C_IDENTIFIER "${_cap}" _cap_identifier)
    string(TOUPPER "${_cap_identifier}" _cap_identifier)
    string(HEX "PULP_INSPECT_CAPABILITY_${_cap_identifier}_V1" _cap_hex)
    string(FIND "${_binary}" "${_cap_hex}" _cap_binary)
    if(_cap_declared GREATER_EQUAL 0 AND _cap_binary LESS 0)
        message(FATAL_ERROR "declared capability marker is absent: ${_cap}")
    elseif(_cap_declared LESS 0 AND _cap_binary GREATER_EQUAL 0)
        message(FATAL_ERROR "binary contains undeclared capability marker: ${_cap}")
    endif()
endforeach()

if(_control_schema GREATER_EQUAL 0)
    foreach(_profile IN ITEMS
            production-stripped developer-local test-deterministic
            support-diagnostics research-unsafe)
        string(FIND "${_manifest}" "\"profile\": \"${_profile}\"" _profile_declared)
        string(MAKE_C_IDENTIFIER "${_profile}" _profile_identifier)
        string(TOUPPER "${_profile_identifier}" _profile_identifier)
        string(HEX "PULP_CONTROL_PROFILE_${_profile_identifier}_V1" _profile_hex)
        string(FIND "${_binary}" "${_profile_hex}" _profile_binary)
        if(_profile_declared GREATER_EQUAL 0 AND _profile_binary LESS 0)
            message(FATAL_ERROR "declared control profile marker is absent: ${_profile}")
        elseif(_profile_declared LESS 0 AND _profile_binary GREATER_EQUAL 0)
            message(FATAL_ERROR "binary contains undeclared control profile marker: ${_profile}")
        endif()
    endforeach()

    string(SHA256 _manifest_digest "${_manifest}")
    string(HEX "PULP_CONTROL_MANIFEST_SHA256_${_manifest_digest}_V1" _digest_hex)
    string(FIND "${_binary}" "${_digest_hex}" _digest_binary)
    if(_digest_binary LESS 0)
        message(FATAL_ERROR "control manifest digest marker is absent or stale")
    endif()

    string(FIND "${_manifest}" "\"profile\": \"production-stripped\"" _stripped_profile)
    string(HEX "PULP_REMOTE_VIEW_PARAMETER_AUTHORITY_V1" _remote_view_hex)
    string(FIND "${_binary}" "${_remote_view_hex}" _remote_view_binary)
    if(_stripped_profile GREATER_EQUAL 0 AND _remote_view_binary GREATER_EQUAL 0)
        message(FATAL_ERROR
            "production-stripped artifact contains Remote View parameter authority")
    endif()
endif()

string(FIND "${_manifest}" "\"unsafe_runtime_eval_acknowledged\": true" _eval_declared)
string(HEX "PULP_INSPECT_RUNTIME_EVAL_HIGH_RISK_COMPONENT_V1" _eval_hex)
string(FIND "${_binary}" "${_eval_hex}" _eval_binary)
if(_eval_declared GREATER_EQUAL 0 AND _eval_binary LESS 0)
    message(FATAL_ERROR "runtime.eval acknowledgement is present but high-risk component marker is absent")
elseif(_eval_declared LESS 0 AND _eval_binary GREATER_EQUAL 0)
    message(FATAL_ERROR "high-risk runtime.eval component is present without its separate acknowledgement")
endif()
