cmake_minimum_required(VERSION 3.24)

foreach(_required IN ITEMS PULP_CONTROL_HOST_ID PULP_CONTROL_HOST_SOURCE
                           PULP_CONTROL_HOST_MANIFEST PULP_CONTROL_HOST_ROOT)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "install_control_host.cmake requires ${_required}")
    endif()
endforeach()
string(LENGTH "${PULP_CONTROL_HOST_ID}" _host_id_length)
if(NOT PULP_CONTROL_HOST_ID MATCHES "^[a-z0-9][a-z0-9_-]*$" OR
   _host_id_length GREATER 128 OR NOT IS_ABSOLUTE "${PULP_CONTROL_HOST_ROOT}")
    message(FATAL_ERROR "invalid control host catalog id or root")
endif()
if(NOT EXISTS "${PULP_CONTROL_HOST_SOURCE}" OR
   NOT EXISTS "${PULP_CONTROL_HOST_MANIFEST}" OR
   IS_SYMLINK "${PULP_CONTROL_HOST_SOURCE}" OR
   IS_SYMLINK "${PULP_CONTROL_HOST_MANIFEST}")
    message(FATAL_ERROR "control host executable and manifest must be regular source files")
endif()
if(NOT DEFINED PULP_CONTROL_HOST_RUNTIME_DIR)
    get_filename_component(PULP_CONTROL_HOST_RUNTIME_DIR
        "${PULP_CONTROL_HOST_SOURCE}" DIRECTORY)
endif()

if(EXISTS "${PULP_CONTROL_HOST_ROOT}" AND IS_SYMLINK "${PULP_CONTROL_HOST_ROOT}")
    message(FATAL_ERROR "control host catalog root must not be a symlink")
endif()
function(_pulp_make_private_directory path)
    if(UNIX AND NOT EXISTS "${path}")
        execute_process(COMMAND /bin/mkdir -p -m 700 "${path}"
            RESULT_VARIABLE _mkdir_result ERROR_VARIABLE _mkdir_error)
        if(NOT _mkdir_result EQUAL 0)
            message(FATAL_ERROR "could not create private directory: ${_mkdir_error}")
        endif()
    else()
        file(MAKE_DIRECTORY "${path}")
        file(CHMOD "${path}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    endif()
endfunction()
_pulp_make_private_directory("${PULP_CONTROL_HOST_ROOT}")

file(SHA256 "${PULP_CONTROL_HOST_SOURCE}" _host_digest)
file(SHA256 "${PULP_CONTROL_HOST_MANIFEST}" _manifest_digest)
set(_closure "host:${_host_digest}\nmanifest:${_manifest_digest}\n")
if(APPLE)
    file(GLOB _staged_runtime_dependencies LIST_DIRECTORIES FALSE
        "${PULP_CONTROL_HOST_RUNTIME_DIR}/*.dylib"
        "${PULP_CONTROL_HOST_RUNTIME_DIR}/*.so")
elseif(WIN32)
    file(GLOB _staged_runtime_dependencies LIST_DIRECTORIES FALSE
        "${PULP_CONTROL_HOST_RUNTIME_DIR}/*.dll")
else()
    file(GLOB _staged_runtime_dependencies LIST_DIRECTORIES FALSE
        "${PULP_CONTROL_HOST_RUNTIME_DIR}/*.so")
endif()
set(_runtime_dependencies ${_staged_runtime_dependencies})
if(APPLE)
    file(GET_RUNTIME_DEPENDENCIES
        EXECUTABLES "${PULP_CONTROL_HOST_SOURCE}"
        DIRECTORIES "${PULP_CONTROL_HOST_RUNTIME_DIR}"
        RESOLVED_DEPENDENCIES_VAR _resolved_runtime_dependencies
        UNRESOLVED_DEPENDENCIES_VAR _unresolved_runtime_dependencies
        CONFLICTING_DEPENDENCIES_PREFIX _conflicting_runtime_dependencies)
    if(_unresolved_runtime_dependencies OR
       _conflicting_runtime_dependencies_FILENAMES)
        message(FATAL_ERROR
            "control host has unresolved or conflicting runtime dependencies: "
            "${_unresolved_runtime_dependencies};${_conflicting_runtime_dependencies_FILENAMES}")
    endif()
    foreach(_dependency IN LISTS _resolved_runtime_dependencies)
        if(_dependency MATCHES "^/System/" OR _dependency MATCHES "^/usr/lib/")
            continue()
        endif()
        if(_dependency MATCHES "\\.framework/")
            message(FATAL_ERROR
                "control host has a non-system framework dependency that cannot be "
                "flattened into the signed host closure: ${_dependency}")
        endif()
        list(APPEND _runtime_dependencies "${_dependency}")
    endforeach()
endif()
list(REMOVE_DUPLICATES _runtime_dependencies)
list(SORT _runtime_dependencies)
list(LENGTH _runtime_dependencies _runtime_dependency_count)
if(_runtime_dependency_count GREATER 16)
    message(FATAL_ERROR "control host runtime closure exceeds 16 files")
endif()
foreach(_dependency IN LISTS _runtime_dependencies)
    get_filename_component(_dependency_name "${_dependency}" NAME)
    if(IS_SYMLINK "${_dependency}" OR
       NOT _dependency_name MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$")
        message(FATAL_ERROR "invalid control host runtime dependency: ${_dependency}")
    endif()
    file(SHA256 "${_dependency}" _dependency_digest)
    string(APPEND _closure "${_dependency_name}:${_dependency_digest}\n")
endforeach()
string(SHA256 _version_digest "${_closure}")

set(_entry "${PULP_CONTROL_HOST_ROOT}/${PULP_CONTROL_HOST_ID}")
if(EXISTS "${_entry}" AND IS_SYMLINK "${_entry}")
    message(FATAL_ERROR "control host catalog entry must not be a symlink")
endif()
_pulp_make_private_directory("${_entry}")
set(_version_name "version-${_version_digest}")
set(_version "${_entry}/${_version_name}")
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef _nonce)
set(_temporary "${_entry}/.${_version_name}.new-${_nonce}")
set(_active_temporary "${_entry}/.active.new-${_nonce}")
_pulp_make_private_directory("${_temporary}")

function(_pulp_copy_control_host_file source destination executable)
    file(COPY_FILE "${source}" "${destination}" RESULT _copy_result)
    if(NOT _copy_result STREQUAL "0")
        file(REMOVE_RECURSE "${_temporary}")
        message(FATAL_ERROR "could not stage control host file: ${_copy_result}")
    endif()
    if(executable)
        file(CHMOD "${destination}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    else()
        file(CHMOD "${destination}" PERMISSIONS OWNER_READ OWNER_WRITE)
    endif()
endfunction()

_pulp_copy_control_host_file("${PULP_CONTROL_HOST_SOURCE}" "${_temporary}/host" TRUE)
_pulp_copy_control_host_file("${PULP_CONTROL_HOST_MANIFEST}"
    "${_temporary}/host.inspector-capabilities.json" FALSE)
foreach(_dependency IN LISTS _runtime_dependencies)
    get_filename_component(_dependency_name "${_dependency}" NAME)
    _pulp_copy_control_host_file("${_dependency}"
        "${_temporary}/${_dependency_name}" TRUE)
endforeach()
file(WRITE "${_temporary}/runtime-closure.sha256" "${_closure}")
file(CHMOD "${_temporary}/runtime-closure.sha256" PERMISSIONS OWNER_READ OWNER_WRITE)
if(APPLE)
    find_program(_python NAMES python3 REQUIRED)
    execute_process(COMMAND "${_python}"
        "${CMAKE_CURRENT_LIST_DIR}/scripts/check_bundle_relocatable.py"
        "${_temporary}" --strict --label "${PULP_CONTROL_HOST_ID} control host"
        RESULT_VARIABLE _relocatable_result
        OUTPUT_VARIABLE _relocatable_output
        ERROR_VARIABLE _relocatable_error)
    if(NOT _relocatable_result EQUAL 0)
        file(REMOVE_RECURSE "${_temporary}")
        message(FATAL_ERROR
            "control host runtime closure is not relocatable\n"
            "${_relocatable_output}${_relocatable_error}")
    endif()
endif()

set(_version_created FALSE)
if(EXISTS "${_version}")
    if(IS_SYMLINK "${_version}")
        file(REMOVE_RECURSE "${_temporary}")
        message(FATAL_ERROR "control host version must not be a symlink")
    endif()
    set(_expected_version_files
        "host" "host.inspector-capabilities.json" "runtime-closure.sha256")
    foreach(_dependency IN LISTS _runtime_dependencies)
        get_filename_component(_dependency_name "${_dependency}" NAME)
        list(APPEND _expected_version_files "${_dependency_name}")
    endforeach()
    list(SORT _expected_version_files)
    file(GLOB _existing_version_paths LIST_DIRECTORIES FALSE "${_version}/*")
    set(_existing_version_files "")
    foreach(_existing_path IN LISTS _existing_version_paths)
        get_filename_component(_existing_name "${_existing_path}" NAME)
        list(APPEND _existing_version_files "${_existing_name}")
    endforeach()
    list(SORT _existing_version_files)
    if(NOT _existing_version_files STREQUAL _expected_version_files)
        file(REMOVE_RECURSE "${_temporary}")
        message(FATAL_ERROR "existing control host version has an unexpected file set")
    endif()
    foreach(_expected_file IN LISTS _expected_version_files)
        if(IS_SYMLINK "${_version}/${_expected_file}")
            file(REMOVE_RECURSE "${_temporary}")
            message(FATAL_ERROR "existing control host version contains a symlink")
        endif()
        file(SHA256 "${_version}/${_expected_file}" _existing_digest)
        file(SHA256 "${_temporary}/${_expected_file}" _staged_digest)
        if(NOT _existing_digest STREQUAL _staged_digest)
            file(REMOVE_RECURSE "${_temporary}")
            message(FATAL_ERROR "existing control host version failed content validation")
        endif()
    endforeach()
    file(REMOVE_RECURSE "${_temporary}")
else()
    file(RENAME "${_temporary}" "${_version}" RESULT _version_result)
    if(NOT _version_result STREQUAL "0")
        file(REMOVE_RECURSE "${_temporary}")
        message(FATAL_ERROR "could not publish immutable control host version: ${_version_result}")
    endif()
    set(_version_created TRUE)
endif()

file(WRITE "${_active_temporary}" "${_version_name}\n")
file(CHMOD "${_active_temporary}" PERMISSIONS OWNER_READ OWNER_WRITE)
if(PULP_CONTROL_HOST_TEST_FAIL_BEFORE_PUBLISH)
    set(_active_result "synthetic publish failure")
else()
    file(RENAME "${_active_temporary}" "${_entry}/active" RESULT _active_result)
endif()
if(NOT _active_result STREQUAL "0")
    file(REMOVE "${_active_temporary}")
    if(_version_created)
        file(REMOVE_RECURSE "${_version}")
    endif()
    message(FATAL_ERROR "could not atomically publish control host selection: ${_active_result}")
endif()
