// pulp-annotated-capture-import — the no-metadata design-import lane.
// Turns a bare captured SVG + a sidecar manifest into the same
// artifacts the faithful-vector Figma path emits: a DesignFrameView subclass
// (populated typed element table), the embedded-SVG accessor, and the wiring
// lines to paste into CMake / the catalog. See annotated_capture.hpp for the
// manifest schema (a generic contract any external UI extractor can emit).
//
// Usage:
//   pulp-annotated-capture-import --svg capture.svg --manifest ui_manifest.json \
//       [--out-dir core/view] [--class ReverbPanelView]

#include "tools/import-design/annotated_capture.hpp"

#include <pulp/runtime/base64.hpp>

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

namespace {

std::string read_file(const std::string& path, bool& ok) {
    std::ifstream f(path, std::ios::binary);
    if (!f) { ok = false; return {}; }
    std::ostringstream ss;
    ss << f.rdbuf();
    ok = true;
    return ss.str();
}

bool write_file(const std::string& path, const std::string& contents) {
    std::ofstream f(path, std::ios::binary);
    if (!f) return false;
    f << contents;
    return static_cast<bool>(f);
}

std::string arg_value(int argc, char** argv, const std::string& flag) {
    for (int i = 1; i + 1 < argc; ++i)
        if (flag == argv[i]) return argv[i + 1];
    return {};
}

// Chunked base64 accessor source, mirroring make_catalog_component.py's
// <snake>_svg.cpp so a >64K SVG literal never trips the compiler.
std::string emit_svg_accessor(const std::string& snake, const std::string& svg) {
    const std::string b64 = pulp::runtime::base64_encode(svg);
    std::ostringstream o;
    o << "// Generated by pulp-annotated-capture-import — do not edit.\n"
      << "#include <string>\n\nnamespace pulp::view::detail {\n\n"
      << "const char* " << snake << "_svg_b64() {\n"
      << "  static const char* const kParts[] = {\n";
    for (size_t i = 0; i < b64.size(); i += 8000)
        o << "    \"" << b64.substr(i, 8000) << "\",\n";
    o << "  };\n"
      << "  static const std::string kJoined = [] { std::string s; "
      << "for (const char* p : kParts) s += p; return s; }();\n"
      << "  return kJoined.c_str();\n}\n\n}  // namespace pulp::view::detail\n";
    return o.str();
}

}  // namespace

int main(int argc, char** argv) {
    using namespace pulp::import_design;

    const std::string svg_path = arg_value(argc, argv, "--svg");
    const std::string manifest_path = arg_value(argc, argv, "--manifest");
    std::string out_dir = arg_value(argc, argv, "--out-dir");
    const std::string class_override = arg_value(argc, argv, "--class");
    if (svg_path.empty() || manifest_path.empty()) {
        std::fprintf(stderr,
                     "usage: pulp-annotated-capture-import --svg FILE --manifest FILE "
                     "[--out-dir DIR] [--class Name]\n");
        return 2;
    }
    if (out_dir.empty()) out_dir = "core/view";

    bool ok = false;
    const std::string svg = read_file(svg_path, ok);
    if (!ok) { std::fprintf(stderr, "cannot read SVG: %s\n", svg_path.c_str()); return 1; }
    const std::string manifest_json = read_file(manifest_path, ok);
    if (!ok) { std::fprintf(stderr, "cannot read manifest: %s\n", manifest_path.c_str()); return 1; }

    AnnotatedCaptureManifest m;
    std::string error;
    if (!parse_annotated_manifest(manifest_json, m, error)) {
        std::fprintf(stderr, "manifest error: %s\n", error.c_str());
        return 1;
    }
    if (!class_override.empty()) m.class_name = class_override;
    if (m.class_name.empty()) m.class_name = "AnnotatedCaptureView";

    const std::string snake = snake_case(m.class_name);
    const std::string sym = "pulp::view::detail::" + snake + "_svg_b64";

    const std::string hpp = generate_view_header(m);
    const std::string cpp = generate_view_source(m, sym);
    const std::string svg_cpp = emit_svg_accessor(snake, svg);

    const std::string hpp_path = out_dir + "/include/pulp/view/" + snake + ".hpp";
    const std::string cpp_path = out_dir + "/src/" + snake + ".cpp";
    const std::string svg_path_out = out_dir + "/src/" + snake + "_svg.cpp";

    if (!write_file(hpp_path, hpp) || !write_file(cpp_path, cpp) ||
        !write_file(svg_path_out, svg_cpp)) {
        std::fprintf(stderr, "failed to write generated sources under %s\n", out_dir.c_str());
        return 1;
    }

    std::printf("wrote:\n  %s\n  %s\n  %s\n", hpp_path.c_str(), cpp_path.c_str(),
                svg_path_out.c_str());
    std::printf("\n# core/view/CMakeLists.txt (with the other src/ entries):\n");
    std::printf("    src/%s.cpp\n    src/%s_svg.cpp\n", snake.c_str(), snake.c_str());
    std::printf("\n# %zu interactive element(s); host-param routing %s\n",
                m.elements.size(), m.has_param_bindings() ? "ENABLED" : "off");
    return 0;
}
