#include "import_design_cli_help.hpp"

#include <iostream>

namespace pulp::import_design {

void print_usage() {
    std::cout << "pulp import-design — Import designs from external tools into Pulp\n\n";
    std::cout << "Usage:\n";
    std::cout << "  pulp import-design --file <design> [options]\n";
    std::cout << "  pulp import-design --from <source> --file <design> [options]\n\n";
    std::cout << "Sources:\n";
    std::cout << "  figma, figma-plugin  Figma JSON/normalized IR, or Pulp plugin envelope\n";
    std::cout << "  fig      Local Figma .fig save file, decoded offline (no account/network)\n";
    std::cout << "  stitch   Google Stitch screen HTML or normalized IR file\n";
    std::cout << "  v0       v0.dev TSX/Tailwind output\n";
    std::cout << "  pencil   Pencil/OpenPencil node JSON or .pen export\n";
    std::cout << "  claude   Anthropic Claude Design — manually-exported standalone HTML\n";
    std::cout << "  html     Generic runnable HTML evaluated in isolated Chromium\n";
    std::cout << "  designmd Google DESIGN.md design-system spec (tokens only)\n";
    std::cout << "  jsx      Precompiled React JSX runtime bundle for live pass-through or baked snapshots\n\n";
    std::cout << "Options:\n";
    std::cout << "  --from <source>   Design source override. Runnable HTML is detected automatically.\n";
    std::cout << "  --file <path>     Input file path. Repeatable with --from figma-plugin:\n";
    std::cout << "                    one already-exported envelope per state captures a\n";
    std::cout << "                    multi-state design into one view. Order sets the frame\n";
    std::cout << "                    index a \"swap <n>\" button targets (the first --file is\n";
    std::cout << "                    frame 0).\n";
    std::cout << "  --url <url>       URL that serves design JSON/HTML directly (e.g. a v0 share\n";
    std::cout << "                    link). Fetched unauthenticated; a figma.com file URL does\n";
    std::cout << "                    NOT work — see 'Importing from Figma' below.\n";
    std::cout << "  --frame <name>    Frame/artboard to import (Figma; guid or name for --from fig).\n";
    std::cout << "                    Repeatable: give it once per state to capture a multi-state\n";
    std::cout << "                    design into one view. Order sets the frame index a \"swap <n>\"\n";
    std::cout << "                    button targets (the first --frame is frame 0).\n";
    std::cout << "  --page <name>     Restrict frame lookup to one page (--from fig)\n";
    std::cout << "  --outline         List pages/frames of a .fig file and exit (--from fig)\n";
    std::cout << "  --json            With --outline, emit the inventory as JSON\n";
    std::cout << "  --screen <name>   Screen to import (Stitch)\n";
    std::cout << "  --output <path>   Destination file for the primary artifact (default: ui.js)\n";
    std::cout << "  --emit {js|ir-json|cpp|swiftui}\n";
    std::cout << "                    Primary artifact kind (built-in default: js). cpp and\n";
    std::cout << "                    swiftui are baked-only; swiftui emits native SwiftUI\n";
    std::cout << "                    (a View + PulpTheme.swift + binding manifest)\n";
    std::cout << "  --mode {live|baked}\n";
    std::cout << "                    Runtime model (built-in default: live; baked emits IR or C++ artifacts)\n";
    std::cout << "  --snapshot-semantics {fail|warn|accept}\n";
    std::cout << "                    JSX baked snapshot policy (default: fail)\n";
    std::cout << "  --allow-network-fetch\n";
    std::cout << "                    Allow DesignIR asset-manifest HTTP fetches at import time\n";
    std::cout << "  --allow-browser-network\n";
    std::cout << "                    Permit source-declared public HTTPS origins while Chromium\n";
    std::cout << "                    evaluates HTML; private/local and WebSocket access stays blocked\n";
    std::cout << "  --browser <path>  Chromium/Chrome executable for browser-solved HTML import\n";
    std::cout << "  --offline         Explicitly use the legacy lower-fidelity HTML parser instead\n";
    std::cout << "                    of executing HTML in Chromium\n";
    std::cout << "  --asset-cache <path>\n";
    std::cout << "                    Asset cache directory (default: PULP_IMPORT_ASSET_CACHE or user cache)\n";
    std::cout << "  --asset-timeout-ms <ms>\n";
    std::cout << "                    Per-request asset fetch timeout (default: 30000)\n";
    std::cout << "  --asset-hash <uri=sha256>\n";
    std::cout << "                    Expected asset content hash; may be repeated\n";
    std::cout << "  --tokens <path>   Output token file (default: tokens.json; theme.css for css-variables)\n";
    std::cout << "  --emit-w3c-tokens <path>\n";
    std::cout << "                    Additionally write the imported tokens as a W3C Design\n";
    std::cout << "                    Tokens (DTCG) document (\"-\" = stdout). Nested groups from\n";
    std::cout << "                    \"/\" in token names; source provenance under $extensions.\n";
    std::cout << "                    Additive — no other output changes.\n";
    std::cout << "  --format {w3c|css-variables|tailwind|json-tailwind|css-tailwind}\n";
    std::cout << "                    Token export format (default: w3c). css-variables emits CSS\n";
    std::cout << "                    custom properties (.dark modes → @media prefers-color-scheme);\n";
    std::cout << "                    tailwind variants currently require --from designmd\n";
    std::cout << "  --dry-run         Show generated code without writing files\n";
    std::cout << "  --no-tokens       Skip token extraction\n";
    std::cout << "  --no-comments     Omit comments from generated code\n";
    std::cout << "  --web-compat      Use DOM API instead of native Pulp API\n";
    std::cout << "  --validate        Render generated JS and validate layout. Browser-backed\n";
    std::cout << "                    HTML always runs its required A/B validation; this flag\n";
    std::cout << "                    also publishes convenience render/diff files beside output.\n";
    std::cout << "  --screenshot-backend {skia|coregraphics}\n";
    std::cout << "                    Validation render backend (default: skia); browser-backed\n";
    std::cout << "                    HTML uses it for its automatic A/B gate. Only Skia\n";
    std::cout << "                    composites file-backed images; coregraphics\n";
    std::cout << "                    draws an image's filename placeholder (not faithful).\n";
    std::cout << "  --knob-style {silver|sprite|auto|standard|default}\n";
    std::cout << "  --fader-style {skin|skinned|default|plain}\n";
    std::cout << "  --meter-style {skin|skinned|default|plain}\n";
    std::cout << "  --strict-fidelity Fail (exit 4) if the import-time fidelity self-check\n";
    std::cout << "                    finds a skewed / unverifiable sprite (always warns)\n";
    std::cout << "  --fidelity-report <file>  Write the run's fidelity findings as a JSON ledger\n";
    std::cout << "                    (named taxonomy + per-kind counts) — a diffable contract\n";
    std::cout << "  --dump-layout <file>  Write the laid-out view tree as JSON (implies\n";
    std::cout << "                    --validate): per view its anchor, source node id, and\n";
    std::cout << "                    absolute bounds in design px. Feed it to\n";
    std::cout << "                    tools/import-design/layout_parity.py alongside the\n";
    std::cout << "                    source's own solved rects (--from fig writes those to\n";
    std::cout << "                    geometry.json) to diff placement per node.\n";
    std::cout << "  --reference <png> Compare render against a reference screenshot\n";
    std::cout << "  --diff <png>      Save visual diff image\n";
    std::cout << "  --import-report <path>  Write the per-control resolution report (JSON) — rung,\n";
    std::cout << "                    confidence, conflicts, verification — for review or a CI gate\n";
    std::cout << "  --fail-on-unresolved    Exit nonzero (2) when a control is conflicted or inert\n";
    std::cout << "  --fail-below <pct>      Exit nonzero (5) when --reference similarity is below\n";
    std::cout << "                    <pct>, given as a percentage 0-100 (e.g. 85, not 0.85).\n";
    std::cout << "                    Without this flag the similarity is advisory and the exit\n";
    std::cout << "                    code is unchanged, at any similarity.\n";
    std::cout << "  --recognition-manifest <path>\n";
    std::cout << "                    User recognition manifest (flat library-manifest shape) mapping\n";
    std::cout << "                    your OWN Figma component-set keys / name prefixes to Pulp control\n";
    std::cout << "                    kinds; merged OVER the built-in Pulp Figma Library so the importer\n";
    std::cout << "                    wires controls on third-party designs. figma / figma-plugin only.\n";
    std::cout << "  --param-binding-manifest <path>\n";
    std::cout << "                    JSON object mapping a Figma node id to a host-param key\n";
    std::cout << "                    (e.g. {\"10:42\": \"filter.cutoff\"}). Binds DESCRIPTIVELY-named\n";
    std::cout << "                    geometry controls (a knob layer named \"Cutoff\", not a\n";
    std::cout << "                    param: sigil) by their stamped source_node_id. A layer-name\n";
    std::cout << "                    sigil still wins; the manifest never overwrites one.\n";
    std::cout << "  --render-size WxH Render dimensions (default: the design's canvas size)\n";
    std::cout << "  --bridge-output <path>  Path to write bridge handler scaffold (default: bridge_handlers.cpp,\n";
    std::cout << "                          only emitted for --from claude)\n";
    std::cout << "  --no-bridge-scaffold    Skip bridge handler scaffold (claude only)\n";
    std::cout << "  --classnames <path>     Output classname → style map (default: classnames.json,\n";
    std::cout << "                          only emitted for Claude static classname extraction)\n";
    std::cout << "  --emit classnames       Legacy sidecar: force-emit classnames.json (claude)\n";
    std::cout << "  --no-emit-classnames    Skip classname emission (claude only)\n";
    std::cout << "  --shortcuts <path>      Output keyboard-shortcut manifest (default: shortcuts.json)\n";
    std::cout << "  --no-import-shortcuts   Skip keyboard shortcut auto-import (default: import)\n";
    std::cout << "  --no-default-shortcuts  Skip platform-convention defaults (Settings=Cmd+,, etc.) (default: enabled)\n";
    std::cout << "  --execute-bundle  Run the bundled React app in a headless JS engine and\n";
    std::cout << "                    walk the materialized DOM (--from claude only).\n";
    std::cout << "                    Falls back to the static parser on any harness failure.\n";
    std::cout << "  --export-tokens   Export a Pulp theme (from --file theme JSON, or the built-in\n";
    std::cout << "                    dark theme when no input) in the --format token format.\n";
    std::cout << "  --detect-only     Detect (source, format-version, parser-version) for\n";
    std::cout << "                    --file or --directory <path> against compat.json without\n";
    std::cout << "                    parsing. Prints match counts and confidence.\n";
    std::cout << "  --directory <p>   Path to a directory export (alternative to --file).\n";
    std::cout << "  --compat <path>   compat.json override (default: discover from cwd / repo root).\n";
    std::cout << "  --report-new-format\n";
    std::cout << "                    Emit a fingerprint-diff JSON suitable for hand-editing\n";
    std::cout << "                    into a new compat.json[imports/<source>/detected-formats]\n";
    std::cout << "                    entry. Implies --detect-only.\n";
    std::cout << "  --help            Show this help\n\n";
    std::cout << "Preferences:\n";
    std::cout << "  Built-in default is --mode live --emit js (live runtime import).\n";
    std::cout << "  Persistent defaults: pulp config set import_design.default_mode live|baked\n";
    std::cout << "                       pulp config set import_design.default_emit js|ir-json|cpp\n";
    std::cout << "  Environment overrides: PULP_IMPORT_DESIGN_DEFAULT_MODE, PULP_IMPORT_DESIGN_DEFAULT_EMIT\n";
    std::cout << "  Each CLI flag overrides its matching preference. If only default_mode=baked is set, default_emit\n";
    std::cout << "  becomes ir-json unless explicitly configured.\n\n";
    std::cout << "Importing from Figma:\n";
    std::cout << "  There is no authenticated Figma fetch in this CLI, so a figma.com file URL\n";
    std::cout << "  cannot be imported with --url. Use one of these lanes instead (local first):\n";
    std::cout << "    1. Figma desktop MCP — get_design_context/get_metadata for inspection.\n";
    std::cout << "    2. 'Design for Pulp' Figma desktop plugin — exports a .pulp.zip envelope;\n";
    std::cout << "       import it with --from figma-plugin --file <export>.pulp.zip\n";
    std::cout << "    3. --from fig --file design.fig — decodes a local .fig save file offline.\n";
    std::cout << "    4. tools/import-design/figma_rest_export.py --token <pat> — headless/CI\n";
    std::cout << "       fallback; hits the Figma REST API and emits the same envelope.\n\n";
    std::cout << "Examples:\n";
    std::cout << "  pulp import-design --from figma --file design.json\n";
    std::cout << "  pulp import-design --from figma-plugin --file design.pulp.zip --frame 'Plugin UI'\n";
    std::cout << "  pulp import-design --from stitch --file screen.html --screen 'Main'\n";
    std::cout << "  pulp import-design --from v0 --url 'https://v0.dev/t/abc123' --output my-ui.js\n";
    std::cout << "  pulp import-design --from pencil --file design.json --dry-run\n";
    std::cout << "  pulp import-design --from pencil --file design.json --validate --reference source.png\n";
    std::cout << "  pulp import-design --from claude --file design.html\n";
    std::cout << "  pulp import-design --from fig --file design.fig --outline\n";
    std::cout << "  pulp import-design --from fig --file design.fig --frame 'Main' --output ui.js\n";
    std::cout << "  pulp import-design --from figma-plugin --file typing.pulp.json --file piano.pulp.json --emit cpp --output kbd.cpp\n";
    std::cout << "  pulp import-design --from figma --file design.json --format css-variables --tokens theme.css\n";
    std::cout << "  pulp import-design --export-tokens --format css-variables   # built-in dark theme → theme.css\n";
    std::cout << "  pulp import-design --from jsx --file bundle.js --mode live --emit js --output live-ui.js\n";
    std::cout << "  pulp import-design --from jsx --file bundle.js --mode baked --emit cpp --output imported_ui.cpp\n";
    std::cout << "  pulp import-design --from figma --file design.json --mode baked --emit swiftui --output ImportedPulpView.swift\n";
}

}  // namespace pulp::import_design
