# Native view sources.
target_sources(pulp-view-core PRIVATE
    src/accessibility.cpp
    src/query_service.cpp
    src/import_validation_bridge.cpp
    src/lottie_view.cpp
    ${PULP_TEXT_ACCESSIBILITY_SOURCE}
    src/threejs_resources_stub.cpp
    src/table_model.cpp
    src/modulation_matrix.cpp
    src/modulation_matrix_widget.cpp
    src/accessibility_tree.cpp
    src/image_cache.cpp
    src/resizable_shell.cpp
    src/theme.cpp
    src/theme_contrast.cpp
    src/theme_presets.cpp
    src/appearance_tracker.cpp
    src/motion_preferences.cpp
    src/asset_manager.cpp
    src/script_event_dispatch.cpp
    src/gesture.cpp
    src/value_channel_json.cpp
    src/value_channel_set.cpp
    src/value_channel_telemetry.cpp
    src/value_source.cpp
    src/value_source_binding.cpp
    src/view.cpp
    src/view_paint.cpp
    src/repaint_damage.cpp
    src/pointer_dispatch.cpp
    src/caret.cpp
    src/continuous_frames.cpp
    src/custom_shader_host.cpp
    src/host_param_surface.cpp
    src/yoga_measurement_internal.cpp
    src/yoga_layout.cpp
    src/grid_layout.cpp
    src/layout_snapshot.cpp
    src/widgets.cpp
    src/widget_schema.cpp
    src/knob_sprite_paint.cpp
    src/slider_core.cpp
    src/widgets/label.cpp
    src/widgets/visualizers.cpp
    src/editor_bridge.cpp
    src/inspector.cpp
    src/sdl_window_host.cpp
    src/auto_ui.cpp
    src/text_edit_model.cpp
    src/text_editor.cpp
    src/text_editor_clipboard.cpp
    src/text_editor_ime.cpp
    src/text_editor_paint.cpp
    src/ui_components.cpp
    src/context_menu.cpp
    src/scroll_bar.cpp
    src/view_pool.cpp
    src/virtual_list.cpp
    src/virtual_grid.cpp
    src/relative_point.cpp
    src/css_gradient.cpp
    src/css_effect_parse.cpp
    src/w3c_tokens.cpp
    src/widget_skin_derive.cpp
    src/screenshot_compare.cpp
    src/screenshot_png_validation.cpp
    src/screenshot_gpu.cpp
    src/app_framework.cpp
    src/canvas_widget.cpp
    src/native_view_host.cpp
    src/gpu_surface_observer.cpp
    src/plugin_frame_renderer.cpp
    src/design_frame_view.cpp
    src/design_fit_view.cpp
    src/design_param_binding.cpp
    src/svg_fragment.cpp
    src/callout_box.cpp
    src/reorder_list.cpp
    src/control_painters.cpp
    src/designed_control_painter.cpp
    src/svg_path_widget.cpp
    src/widgets/svg_rect.cpp
    src/widgets/svg_line.cpp
    src/visualization_bridge.cpp
    src/waveform_editor_primitives.cpp
    src/waveform_gpu_primitives.cpp
    src/waveform_gpu_render_controller.cpp
    src/waveform_headless_render_backend.cpp
    src/frame_clock.cpp
    src/host_frame_pump.cpp
    src/motion.cpp
    src/motion_geometry.cpp
    src/motion_cost.cpp
    src/window_manager.cpp
    src/eq_curve_view.cpp
    src/graph_scale.cpp
    src/step_grid_view.cpp
    src/midi_keyboard.cpp
    src/musical_typing_keyboard.cpp
    src/musical_typing_keyboard_svg.cpp
    src/channel_strip_view.cpp
    src/channel_strip_view_svg.cpp
    src/range_slider_view.cpp
    src/range_slider_view_svg.cpp
    src/inline_value_editor_view.cpp
    src/inline_value_editor_view_svg.cpp
    src/property_panel_view.cpp
    src/property_panel_view_svg.cpp
    src/group_box_view.cpp
    src/group_box_view_svg.cpp
    src/number_box_states_view.cpp
    src/number_box_states_view_svg.cpp
    src/knob_modulation_view.cpp
    src/knob_modulation_view_svg.cpp
    src/waveform_recorder_view.cpp
    src/waveform_recorder_view_svg.cpp
    src/color_picker.cpp
    src/theme_editor.cpp
    src/file_drop_zone.cpp
    src/sample_asset_drop_target.cpp
    src/drag_drop.cpp
    src/split_view.cpp
    src/property_list.cpp
    src/breadcrumb.cpp
    src/buttons.cpp
    src/gap_widgets.cpp
    src/widget_gallery.cpp
    src/design_system.cpp
    src/sampler_starter.cpp
    src/file_browser.cpp
    src/file_chooser.cpp
    src/code_editor.cpp
    src/code_editor_tokenizer.cpp
    src/table.cpp
    src/toolbar.cpp
    src/concertina_panel.cpp
    src/splash_screen.cpp
    src/live_constant_editor.cpp
    src/inspector_window.cpp
    src/audio_inspector_panel.cpp
    src/audio_inspector_window.cpp
    src/command_registry.cpp
    src/key_mapping_editor.cpp
    src/window_classes.cpp
    src/bubble_message.cpp
)

# Scripted view and widget-bridge sources.
target_sources(pulp-view-script PRIVATE
    ${PULP_JS_ENGINE_SOURCES}
    src/script_engine.cpp
    src/script_inspector_bridge.cpp
    src/js_engine_recommend.cpp
    src/widget_bridge.cpp
    src/widget_bridge/value_channel_access.cpp
    src/widget_bridge/bridge_dispatch.cpp
    src/widget_bridge/css_color.cpp
    src/widget_bridge/accessibility_api.cpp
    src/widget_bridge/animation_api.cpp
    src/widget_bridge/dom_api.cpp
    src/widget_bridge/event_api.cpp
    src/widget_bridge/gpu_api.cpp
    src/widget_bridge/gpu_common.cpp
    src/widget_bridge/style_cursor_api.cpp
    src/widget_bridge/style_effects_api.cpp
    src/widget_bridge/style_rn_compat_api.cpp
    src/widget_bridge/style_state_api.cpp
    src/widget_bridge/style_storage_api.cpp
    src/widget_bridge/style_visual_api.cpp
    src/widget_bridge/style_visibility_api.cpp
    src/widget_bridge/subtree_cleanup.cpp
    src/widget_bridge/layout_api.cpp
    src/widget_bridge/list_style_api.cpp
    src/widget_bridge/metadata_api.cpp
    src/widget_bridge/platform_services_api.cpp
    src/widget_bridge/realm_lifecycle.cpp
    src/widget_bridge/runtime_api.cpp
    src/widget_bridge/state_binding_api.cpp
    src/widget_bridge/value_channel_binding_service.cpp
    src/widget_bridge/storage_assets_api.cpp
    src/widget_bridge/shader_api.cpp
    src/widget_bridge/svg_api.cpp
    src/widget_bridge/theme_api.cpp
    src/widget_bridge/tokens_api.cpp
    src/widget_bridge/widget_assets_api.cpp
    src/widget_bridge/widget_callbacks.cpp
    src/widget_bridge/widget_schema_api.cpp
    src/widget_bridge/factory_api.cpp
    src/widget_bridge/widget_value_controls_api.cpp
    src/widget_bridge/widget_value_basic_api.cpp
    src/widget_bridge/typography_api.cpp
    src/widget_bridge/text_runs_api.cpp
    src/widget_bridge/border_box_api.cpp
    src/widget_bridge/outline_api.cpp
    src/widget_bridge/border_radius_api.cpp
    src/widget_bridge/border_side_api.cpp
    src/widget_bridge/canvas2d_api.cpp
    src/widget_bridge/widget_value_list_api.cpp
    src/widget_bridge/widget_value_content_api.cpp
    src/widget_bridge/query_service_api.cpp
    src/widget_bridge_input.cpp
    src/hot_reload.cpp
    src/scripted_ui.cpp
)

# Design-import authoring cluster (PULP_ENABLE_DESIGN_IMPORT).
# Importers, codegen, lock-to-source, JSX-lock, and the runtime design-import
# opt-in. Gated out of shipped plugins; the runtime W3C token pair
# (src/w3c_tokens.cpp) and the runtime widgets (canvas/svg/design_frame_view/
# css_gradient/visualization/app_framework/widget_skin_derive) stay
# always-compiled above.
if(PULP_ENABLE_DESIGN_IMPORT)
    target_sources(pulp-view-core PRIVATE
        src/anchor_strategy.cpp
        src/design_export.cpp
        src/design_import.cpp
        src/design_import_png.cpp
        src/design_binding_metadata.cpp
        src/design_ir_json.cpp
        src/design_ir_normalize.cpp
        src/recognition_resolver.cpp
        src/design_ir_analysis.cpp
        src/design_import_v0_tsx.cpp
        src/design_import_native_common.cpp
        src/design_cpp_codegen.cpp
        src/design_cpp_binding_codegen.cpp
        src/design_cpp_codegen_support.cpp
        src/design_cpp_style_codegen.cpp
        src/design_cpp_tree_codegen.cpp
        src/design_swift_codegen.cpp
        src/design_tokens.cpp
        src/design_tokens_w3c.cpp
        src/design_manifest.cpp
        src/design_adherence.cpp
        src/design_ledger.cpp
        src/design_codegen.cpp
        src/design_fidelity.cpp
        src/design_fidelity_ledger.cpp
        src/design_variants.cpp
        src/design_gallery.cpp
        src/design_handoff.cpp
        src/design_tweaks.cpp
        src/design_knobs.cpp
        src/lock_to_source.cpp
        src/jsx_lock.cpp
        src/design_import_shortcuts.cpp
        src/design_import_designmd.cpp
        src/design_import_designmd_schema.cpp
        src/token_lock.cpp
    )
    target_sources(pulp-view-script PRIVATE
        src/widget_bridge/runtime_import_api.cpp
        src/claude_bundle.cpp
        src/claude_bundle_sources.cpp
    )
    target_compile_definitions(pulp-view-core PUBLIC PULP_HAS_DESIGN_IMPORT=1)
    target_compile_definitions(pulp-view-script PUBLIC PULP_HAS_DESIGN_IMPORT=1)
else()
    # No-op WidgetBridge::install_runtime_import_handlers() so callers still link.
    target_sources(pulp-view-script PRIVATE
        src/widget_bridge/runtime_import_api_stub.cpp
    )
    target_compile_definitions(pulp-view-core PUBLIC PULP_HAS_DESIGN_IMPORT=0)
    target_compile_definitions(pulp-view-script PUBLIC PULP_HAS_DESIGN_IMPORT=0)
endif()
