#pragma once

// GENERATED by tools/rack/forge_modular.py -- do not edit.
// Panel coordinates here are the SAME numbers the panel SVG was drawn
// from, which is what keeps a widget and its label from disagreeing.

#include <rack.hpp>

namespace forge_modular {

// ── VCO (8HP) ─────────────────────────────────────────
struct VCOLayout {
    static constexpr int kHp = 8;
    enum ParamId { FREQ_PARAM, FINE_PARAM, PW_PARAM, FM_PARAM, PARAMS_LEN };
    enum InputId { VOCT_INPUT, FM_INPUT, INPUTS_LEN };
    enum OutputId { SAW_OUTPUT, PULSE_OUTPUT, TRI_OUTPUT, SINE_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_VCO(rack::engine::Module* m) {
    m->config(VCOLayout::PARAMS_LEN, VCOLayout::INPUTS_LEN, VCOLayout::OUTPUTS_LEN, VCOLayout::LIGHTS_LEN);
    m->configParam(VCOLayout::FREQ_PARAM, -4.0f, 4.0f, 0.0f, "Frequency", " Hz", 2.0f, 261.6256f);
    m->configParam(VCOLayout::FINE_PARAM, -1.0f, 1.0f, 0.0f, "Fine tune", " cents", 0.0f, 100.0f);
    m->configParam(VCOLayout::PW_PARAM, 0.05f, 0.95f, 0.5f, "Pulse width", "%", 0.0f, 100.0f);
    m->configParam(VCOLayout::FM_PARAM, -1.0f, 1.0f, 0.0f, "FM amount", "%", 0.0f, 100.0f);
    m->configInput(VCOLayout::VOCT_INPUT, "1V/oct pitch");
    m->configInput(VCOLayout::FM_INPUT, "Frequency modulation");
    m->configOutput(VCOLayout::SAW_OUTPUT, "Sawtooth");
    m->configOutput(VCOLayout::PULSE_OUTPUT, "Pulse");
    m->configOutput(VCOLayout::TRI_OUTPUT, "Triangle");
    m->configOutput(VCOLayout::SINE_OUTPUT, "Sine");
}

inline void place_VCO(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<ScrewSilver>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<ScrewSilver>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<ScrewSilver>(mm2px(Vec(33.020f, 2.54f))));
    w->addChild(createWidgetCentered<ScrewSilver>(mm2px(Vec(33.020f, 126.153f))));
    w->addParam(createParamCentered<RoundBigBlackKnob>(mm2px(Vec(20.320f, 30.000f)), m, VCOLayout::FREQ_PARAM));
    w->addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(11.800f, 52.000f)), m, VCOLayout::FINE_PARAM));
    w->addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(28.840f, 52.000f)), m, VCOLayout::PW_PARAM));
    w->addParam(createParamCentered<Trimpot>(mm2px(Vec(28.840f, 68.000f)), m, VCOLayout::FM_PARAM));
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(11.800f, 84.000f)), m, VCOLayout::VOCT_INPUT));
    w->addInput(createInputCentered<PJ301MPort>(mm2px(Vec(28.840f, 84.000f)), m, VCOLayout::FM_INPUT));
    w->addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(11.800f, 102.000f)), m, VCOLayout::SAW_OUTPUT));
    w->addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(28.840f, 102.000f)), m, VCOLayout::PULSE_OUTPUT));
    w->addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(11.800f, 118.000f)), m, VCOLayout::TRI_OUTPUT));
    w->addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(28.840f, 118.000f)), m, VCOLayout::SINE_OUTPUT));
}

}  // namespace forge_modular
