#pragma once

// GENERATED by tools/rack/forge_modular.py -- do not edit.
// Panel coordinates here are the SAME numbers the panel SVG was drawn
// from, which is what keeps a widget and its label from disagreeing.

#include <rack.hpp>

#include "forge_components.hpp"

#include <algorithm>

namespace forge_modular {

// ── VCO (8HP) ─────────────────────────────────────────
struct VCOLayout {
    static constexpr int kHp = 8;
    enum ParamId { FREQ_PARAM, FINE_PARAM, PW_PARAM, FM_PARAM, PARAMS_LEN };
    enum InputId { VOCT_INPUT, FM_INPUT, INPUTS_LEN };
    enum OutputId { SAW_OUTPUT, PULSE_OUTPUT, TRI_OUTPUT, SINE_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_VCO(rack::engine::Module* m) {
    m->config(VCOLayout::PARAMS_LEN, VCOLayout::INPUTS_LEN, VCOLayout::OUTPUTS_LEN, VCOLayout::LIGHTS_LEN);
    m->configParam(VCOLayout::FREQ_PARAM, -4.0f, 4.0f, 0.0f, "Frequency", " Hz", 2.0f, 261.626f);
    m->configParam(VCOLayout::FINE_PARAM, -1.0f, 1.0f, 0.0f, "Fine tune", " cents", 0.0f, 100.0f);
    m->configParam(VCOLayout::PW_PARAM, 0.05f, 0.95f, 0.5f, "Pulse width", "%", 0.0f, 100.0f);
    m->configParam(VCOLayout::FM_PARAM, -1.0f, 1.0f, 0.0f, "FM amount", "%", 0.0f, 100.0f);
    m->configInput(VCOLayout::VOCT_INPUT, "1V/oct pitch");
    m->configInput(VCOLayout::FM_INPUT, "Frequency modulation");
    m->configOutput(VCOLayout::SAW_OUTPUT, "Sawtooth");
    m->configOutput(VCOLayout::PULSE_OUTPUT, "Pulse");
    m->configOutput(VCOLayout::TRI_OUTPUT, "Triangle");
    m->configOutput(VCOLayout::SINE_OUTPUT, "Sine");
}

/// Channel count for VCO, from the manifest's declared source.
inline int channels_VCO(const rack::engine::Module* m) {
    return std::max(1, const_cast<rack::engine::Module*>(m)
        ->inputs[VCOLayout::VOCT_INPUT].getChannels());
}

inline void place_VCO(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobLarge>(mm2px(Vec(20.320f, 30.000f)), m, VCOLayout::FREQ_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(11.800f, 52.000f)), m, VCOLayout::FINE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(28.840f, 52.000f)), m, VCOLayout::PW_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(28.840f, 68.000f)), m, VCOLayout::FM_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(11.800f, 84.000f)), m, VCOLayout::VOCT_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(28.840f, 84.000f)), m, VCOLayout::FM_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(11.800f, 102.000f)), m, VCOLayout::SAW_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(28.840f, 102.000f)), m, VCOLayout::PULSE_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(11.800f, 118.000f)), m, VCOLayout::TRI_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(28.840f, 118.000f)), m, VCOLayout::SINE_OUTPUT));
}

// ── VCF (8HP) ─────────────────────────────────────────
struct VCFLayout {
    static constexpr int kHp = 8;
    enum ParamId { CUTOFF_PARAM, RES_PARAM, CVAMT_PARAM, PARAMS_LEN };
    enum InputId { CV_INPUT, IN_INPUT, INPUTS_LEN };
    enum OutputId { LP_OUTPUT, HP_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_VCF(rack::engine::Module* m) {
    m->config(VCFLayout::PARAMS_LEN, VCFLayout::INPUTS_LEN, VCFLayout::OUTPUTS_LEN, VCFLayout::LIGHTS_LEN);
    m->configParam(VCFLayout::CUTOFF_PARAM, -4.0f, 4.0f, 0.0f, "Cutoff", " Hz", 2.0f, 261.626f);
    m->configParam(VCFLayout::RES_PARAM, 0.0f, 0.95f, 0.1f, "Resonance", "%", 0.0f, 100.0f);
    m->configParam(VCFLayout::CVAMT_PARAM, -1.0f, 1.0f, 0.0f, "Cutoff CV amount", "%", 0.0f, 100.0f);
    m->configInput(VCFLayout::CV_INPUT, "Cutoff CV (1V/oct)");
    m->configInput(VCFLayout::IN_INPUT, "Audio");
    m->configOutput(VCFLayout::LP_OUTPUT, "Low-pass");
    m->configOutput(VCFLayout::HP_OUTPUT, "High-pass");
}

/// Channel count for VCF, from the manifest's declared source.
inline int channels_VCF(const rack::engine::Module* m) {
    return std::max(1, const_cast<rack::engine::Module*>(m)
        ->inputs[VCFLayout::IN_INPUT].getChannels());
}

inline void place_VCF(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobLarge>(mm2px(Vec(20.320f, 30.000f)), m, VCFLayout::CUTOFF_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(11.786f, 56.000f)), m, VCFLayout::RES_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(28.854f, 56.000f)), m, VCFLayout::CVAMT_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(28.854f, 76.000f)), m, VCFLayout::CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(11.786f, 98.000f)), m, VCFLayout::IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(28.854f, 98.000f)), m, VCFLayout::LP_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(28.854f, 116.000f)), m, VCFLayout::HP_OUTPUT));
}

// ── VCA (3HP) ─────────────────────────────────────────
struct VCALayout {
    static constexpr int kHp = 3;
    enum ParamId { LEVEL_PARAM, PARAMS_LEN };
    enum InputId { CV_INPUT, IN_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_VCA(rack::engine::Module* m) {
    m->config(VCALayout::PARAMS_LEN, VCALayout::INPUTS_LEN, VCALayout::OUTPUTS_LEN, VCALayout::LIGHTS_LEN);
    m->configParam(VCALayout::LEVEL_PARAM, 0.0f, 1.0f, 0.5f, "Level", "%", 0.0f, 100.0f);
    m->configInput(VCALayout::CV_INPUT, "Level CV");
    m->configInput(VCALayout::IN_INPUT, "Audio");
    m->configOutput(VCALayout::OUT_OUTPUT, "Audio");
}

/// Channel count for VCA, from the manifest's declared source.
inline int channels_VCA(const rack::engine::Module* m) {
    return std::max(1, const_cast<rack::engine::Module*>(m)
        ->inputs[VCALayout::IN_INPUT].getChannels());
}

inline void place_VCA(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(7.620f, 28.000f)), m, VCALayout::LEVEL_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 55.000f)), m, VCALayout::CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 80.000f)), m, VCALayout::IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 108.000f)), m, VCALayout::OUT_OUTPUT));
}

// ── ENV (6HP) ─────────────────────────────────────────
struct ENVLayout {
    static constexpr int kHp = 6;
    enum ParamId { ATTACK_PARAM, DECAY_PARAM, SUSTAIN_PARAM, RELEASE_PARAM, PARAMS_LEN };
    enum InputId { GATE_INPUT, INPUTS_LEN };
    enum OutputId { ENV_OUTPUT, INV_OUTPUT, OUTPUTS_LEN };
    enum LightId { ENV_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_ENV(rack::engine::Module* m) {
    m->config(ENVLayout::PARAMS_LEN, ENVLayout::INPUTS_LEN, ENVLayout::OUTPUTS_LEN, ENVLayout::LIGHTS_LEN);
    m->configParam(ENVLayout::ATTACK_PARAM, 0.001f, 4.0f, 0.01f, "Attack", " s", 0.0f, 1.0f);
    m->configParam(ENVLayout::DECAY_PARAM, 0.001f, 4.0f, 0.2f, "Decay", " s", 0.0f, 1.0f);
    m->configParam(ENVLayout::SUSTAIN_PARAM, 0.0f, 1.0f, 0.7f, "Sustain", "%", 0.0f, 100.0f);
    m->configParam(ENVLayout::RELEASE_PARAM, 0.001f, 4.0f, 0.4f, "Release", " s", 0.0f, 1.0f);
    m->configInput(ENVLayout::GATE_INPUT, "Gate");
    m->configOutput(ENVLayout::ENV_OUTPUT, "Envelope");
    m->configOutput(ENVLayout::INV_OUTPUT, "Inverted envelope");
    m->configLight(ENVLayout::ENV_LIGHT, "Envelope active");
}

inline void place_ENV(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(15.240f, 26.000f)), m, ENVLayout::ATTACK_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(15.240f, 45.000f)), m, ENVLayout::DECAY_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(15.240f, 64.000f)), m, ENVLayout::SUSTAIN_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(15.240f, 83.000f)), m, ENVLayout::RELEASE_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.144f, 102.000f)), m, ENVLayout::GATE_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(21.336f, 102.000f)), m, ENVLayout::ENV_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(21.336f, 118.000f)), m, ENVLayout::INV_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeMediumLight<GreenLight>>(mm2px(Vec(9.144f, 118.000f)), m, ENVLayout::ENV_LIGHT));
}

// ── LFO (6HP) ─────────────────────────────────────────
struct LFOLayout {
    static constexpr int kHp = 6;
    enum ParamId { RATE_PARAM, PARAMS_LEN };
    enum InputId { RESET_INPUT, INPUTS_LEN };
    enum OutputId { TRI_OUTPUT, SQR_OUTPUT, SIN_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_LFO(rack::engine::Module* m) {
    m->config(LFOLayout::PARAMS_LEN, LFOLayout::INPUTS_LEN, LFOLayout::OUTPUTS_LEN, LFOLayout::LIGHTS_LEN);
    m->configParam(LFOLayout::RATE_PARAM, -8.0f, 8.0f, 0.0f, "Rate", " Hz", 2.0f, 2.0f);
    m->configInput(LFOLayout::RESET_INPUT, "Reset");
    m->configOutput(LFOLayout::TRI_OUTPUT, "Triangle");
    m->configOutput(LFOLayout::SQR_OUTPUT, "Square");
    m->configOutput(LFOLayout::SIN_OUTPUT, "Sine");
}

inline void place_LFO(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(15.240f, 30.000f)), m, LFOLayout::RATE_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(15.240f, 66.000f)), m, LFOLayout::RESET_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(9.144f, 95.000f)), m, LFOLayout::TRI_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(21.336f, 95.000f)), m, LFOLayout::SQR_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(15.240f, 117.000f)), m, LFOLayout::SIN_OUTPUT));
}

// ── EUCLID (6HP) ──────────────────────────────────────
struct EUCLIDLayout {
    static constexpr int kHp = 6;
    enum ParamId { LENGTH_PARAM, FILL_PARAM, ROTATE_PARAM, PARAMS_LEN };
    enum InputId { CLOCK_INPUT, RESET_INPUT, INPUTS_LEN };
    enum OutputId { GATE_OUTPUT, OUTPUTS_LEN };
    enum LightId { STEP_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_EUCLID(rack::engine::Module* m) {
    m->config(EUCLIDLayout::PARAMS_LEN, EUCLIDLayout::INPUTS_LEN, EUCLIDLayout::OUTPUTS_LEN, EUCLIDLayout::LIGHTS_LEN);
    m->configParam(EUCLIDLayout::LENGTH_PARAM, 1.0f, 32.0f, 16.0f, "Steps", "", 0.0f, 1.0f);
    m->getParamQuantity(EUCLIDLayout::LENGTH_PARAM)->snapEnabled = true;
    m->configParam(EUCLIDLayout::FILL_PARAM, 0.0f, 32.0f, 4.0f, "Pulses", "", 0.0f, 1.0f);
    m->getParamQuantity(EUCLIDLayout::FILL_PARAM)->snapEnabled = true;
    m->configParam(EUCLIDLayout::ROTATE_PARAM, 0.0f, 31.0f, 0.0f, "Rotation", "", 0.0f, 1.0f);
    m->getParamQuantity(EUCLIDLayout::ROTATE_PARAM)->snapEnabled = true;
    m->configInput(EUCLIDLayout::CLOCK_INPUT, "Clock");
    m->configInput(EUCLIDLayout::RESET_INPUT, "Reset");
    m->configOutput(EUCLIDLayout::GATE_OUTPUT, "Gate");
    m->configLight(EUCLIDLayout::STEP_LIGHT, "Step");
}

inline void place_EUCLID(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(9.144f, 28.000f)), m, EUCLIDLayout::LENGTH_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(21.336f, 28.000f)), m, EUCLIDLayout::FILL_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(15.240f, 52.000f)), m, EUCLIDLayout::ROTATE_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.144f, 78.000f)), m, EUCLIDLayout::CLOCK_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(21.336f, 78.000f)), m, EUCLIDLayout::RESET_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(15.240f, 110.000f)), m, EUCLIDLayout::GATE_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeMediumLight<GreenLight>>(mm2px(Vec(15.240f, 93.000f)), m, EUCLIDLayout::STEP_LIGHT));
}

// ── SEQ (12HP) ─────────────────────────────────────────
struct SEQLayout {
    static constexpr int kHp = 12;
    enum ParamId { STEP1_PARAM, STEP2_PARAM, STEP3_PARAM, STEP4_PARAM, STEP5_PARAM, STEP6_PARAM, STEP7_PARAM, STEP8_PARAM, PARAMS_LEN };
    enum InputId { CLOCK_INPUT, RESET_INPUT, INPUTS_LEN };
    enum OutputId { CV_OUTPUT, GATE_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_SEQ(rack::engine::Module* m) {
    m->config(SEQLayout::PARAMS_LEN, SEQLayout::INPUTS_LEN, SEQLayout::OUTPUTS_LEN, SEQLayout::LIGHTS_LEN);
    m->configParam(SEQLayout::STEP1_PARAM, -2.0f, 2.0f, 0.0f, "Step 1", " V", 0.0f, 1.0f);
    m->configParam(SEQLayout::STEP2_PARAM, -2.0f, 2.0f, 0.0f, "Step 2", " V", 0.0f, 1.0f);
    m->configParam(SEQLayout::STEP3_PARAM, -2.0f, 2.0f, 0.0f, "Step 3", " V", 0.0f, 1.0f);
    m->configParam(SEQLayout::STEP4_PARAM, -2.0f, 2.0f, 0.0f, "Step 4", " V", 0.0f, 1.0f);
    m->configParam(SEQLayout::STEP5_PARAM, -2.0f, 2.0f, 0.0f, "Step 5", " V", 0.0f, 1.0f);
    m->configParam(SEQLayout::STEP6_PARAM, -2.0f, 2.0f, 0.0f, "Step 6", " V", 0.0f, 1.0f);
    m->configParam(SEQLayout::STEP7_PARAM, -2.0f, 2.0f, 0.0f, "Step 7", " V", 0.0f, 1.0f);
    m->configParam(SEQLayout::STEP8_PARAM, -2.0f, 2.0f, 0.0f, "Step 8", " V", 0.0f, 1.0f);
    m->configInput(SEQLayout::CLOCK_INPUT, "Clock");
    m->configInput(SEQLayout::RESET_INPUT, "Reset");
    m->configOutput(SEQLayout::CV_OUTPUT, "Pitch CV (1V/oct)");
    m->configOutput(SEQLayout::GATE_OUTPUT, "Gate");
}

inline void place_SEQ(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(17.069f, 28.000f)), m, SEQLayout::STEP1_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(17.069f, 46.000f)), m, SEQLayout::STEP2_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(17.069f, 64.000f)), m, SEQLayout::STEP3_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(17.069f, 82.000f)), m, SEQLayout::STEP4_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(43.891f, 28.000f)), m, SEQLayout::STEP5_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(43.891f, 46.000f)), m, SEQLayout::STEP6_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(43.891f, 64.000f)), m, SEQLayout::STEP7_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(43.891f, 82.000f)), m, SEQLayout::STEP8_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(10.973f, 108.000f)), m, SEQLayout::CLOCK_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(23.774f, 108.000f)), m, SEQLayout::RESET_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(37.186f, 108.000f)), m, SEQLayout::CV_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(49.987f, 108.000f)), m, SEQLayout::GATE_OUTPUT));
}

// ── MIX (12HP) ─────────────────────────────────────────
struct MIXLayout {
    static constexpr int kHp = 12;
    enum ParamId { LVL1_PARAM, LVL2_PARAM, LVL3_PARAM, LVL4_PARAM, MASTER_PARAM, MODE_PARAM, PARAMS_LEN };
    enum InputId { IN1_INPUT, IN2_INPUT, IN3_INPUT, IN4_INPUT, CV1_INPUT, CV2_INPUT, CV3_INPUT, CV4_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { LVL1_LIGHT = 0, LVL2_LIGHT = 2, LVL3_LIGHT = 4, LVL4_LIGHT = 6, LIGHTS_LEN = 8 };
};

inline void config_MIX(rack::engine::Module* m) {
    m->config(MIXLayout::PARAMS_LEN, MIXLayout::INPUTS_LEN, MIXLayout::OUTPUTS_LEN, MIXLayout::LIGHTS_LEN);
    m->configParam(MIXLayout::LVL1_PARAM, 0.0f, 1.0f, 0.6f, "Channel 1 level", "%", 0.0f, 100.0f);
    m->configParam(MIXLayout::LVL2_PARAM, 0.0f, 1.0f, 0.6f, "Channel 2 level", "%", 0.0f, 100.0f);
    m->configParam(MIXLayout::LVL3_PARAM, 0.0f, 1.0f, 0.6f, "Channel 3 level", "%", 0.0f, 100.0f);
    m->configParam(MIXLayout::LVL4_PARAM, 0.0f, 1.0f, 0.6f, "Channel 4 level", "%", 0.0f, 100.0f);
    m->configParam(MIXLayout::MASTER_PARAM, 0.0f, 1.0f, 0.8f, "Master level", "%", 0.0f, 100.0f);
    m->configSwitch(MIXLayout::MODE_PARAM, 0.0f, 2.0f, 1.0f, "Response", {"Linear", "Exponential", "Soft clip"});
    m->configInput(MIXLayout::IN1_INPUT, "Channel 1 audio");
    m->configInput(MIXLayout::IN2_INPUT, "Channel 2 audio");
    m->configInput(MIXLayout::IN3_INPUT, "Channel 3 audio");
    m->configInput(MIXLayout::IN4_INPUT, "Channel 4 audio");
    m->configInput(MIXLayout::CV1_INPUT, "Channel 1 level CV (normalled to 10.0V)");
    m->configInput(MIXLayout::CV2_INPUT, "Channel 2 level CV (normalled to 10.0V)");
    m->configInput(MIXLayout::CV3_INPUT, "Channel 3 level CV (normalled to 10.0V)");
    m->configInput(MIXLayout::CV4_INPUT, "Channel 4 level CV (normalled to 10.0V)");
    m->configOutput(MIXLayout::OUT_OUTPUT, "Mix");
    m->configLight(MIXLayout::LVL1_LIGHT, "Channel 1 activity");
    m->configLight(MIXLayout::LVL2_LIGHT, "Channel 2 activity");
    m->configLight(MIXLayout::LVL3_LIGHT, "Channel 3 activity");
    m->configLight(MIXLayout::LVL4_LIGHT, "Channel 4 activity");
}

/// Channel count for MIX, from the manifest's declared source.
inline int channels_MIX(const rack::engine::Module* m) {
    return std::max(1, const_cast<rack::engine::Module*>(m)
        ->inputs[MIXLayout::IN1_INPUT].getChannels());
}

/// CV1_INPUT with its declared normal applied.
inline float read_MIX_CV1_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[MIXLayout::CV1_INPUT].getNormalPolyVoltage(10.0f, c);
}

/// CV2_INPUT with its declared normal applied.
inline float read_MIX_CV2_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[MIXLayout::CV2_INPUT].getNormalPolyVoltage(10.0f, c);
}

/// CV3_INPUT with its declared normal applied.
inline float read_MIX_CV3_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[MIXLayout::CV3_INPUT].getNormalPolyVoltage(10.0f, c);
}

/// CV4_INPUT with its declared normal applied.
inline float read_MIX_CV4_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[MIXLayout::CV4_INPUT].getNormalPolyVoltage(10.0f, c);
}

inline void place_MIX(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeSlider>(mm2px(Vec(9.600f, 42.000f)), m, MIXLayout::LVL1_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeSlider>(mm2px(Vec(23.200f, 42.000f)), m, MIXLayout::LVL2_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeSlider>(mm2px(Vec(36.800f, 42.000f)), m, MIXLayout::LVL3_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeSlider>(mm2px(Vec(50.400f, 42.000f)), m, MIXLayout::LVL4_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(13.000f, 108.000f)), m, MIXLayout::MASTER_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeSwitchThree>(mm2px(Vec(30.500f, 108.000f)), m, MIXLayout::MODE_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.600f, 72.000f)), m, MIXLayout::IN1_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(23.200f, 72.000f)), m, MIXLayout::IN2_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(36.800f, 72.000f)), m, MIXLayout::IN3_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(50.400f, 72.000f)), m, MIXLayout::IN4_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.600f, 84.000f)), m, MIXLayout::CV1_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(23.200f, 84.000f)), m, MIXLayout::CV2_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(36.800f, 84.000f)), m, MIXLayout::CV3_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(50.400f, 84.000f)), m, MIXLayout::CV4_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(48.000f, 108.000f)), m, MIXLayout::OUT_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenRedLight>>(mm2px(Vec(9.600f, 60.000f)), m, MIXLayout::LVL1_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenRedLight>>(mm2px(Vec(23.200f, 60.000f)), m, MIXLayout::LVL2_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenRedLight>>(mm2px(Vec(36.800f, 60.000f)), m, MIXLayout::LVL3_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenRedLight>>(mm2px(Vec(50.400f, 60.000f)), m, MIXLayout::LVL4_LIGHT));
}

// ── ATT (3HP) ─────────────────────────────────────────
struct ATTLayout {
    static constexpr int kHp = 3;
    enum ParamId { AMT_PARAM, OFFSET_PARAM, PARAMS_LEN };
    enum InputId { IN_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_ATT(rack::engine::Module* m) {
    m->config(ATTLayout::PARAMS_LEN, ATTLayout::INPUTS_LEN, ATTLayout::OUTPUTS_LEN, ATTLayout::LIGHTS_LEN);
    m->configParam(ATTLayout::AMT_PARAM, -1.0f, 1.0f, 1.0f, "Amount", "%", 0.0f, 100.0f);
    m->configParam(ATTLayout::OFFSET_PARAM, -5.0f, 5.0f, 0.0f, "Offset", " V", 0.0f, 1.0f);
    m->configInput(ATTLayout::IN_INPUT, "Signal");
    m->configOutput(ATTLayout::OUT_OUTPUT, "Signal");
}

inline void place_ATT(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(7.620f, 28.000f)), m, ATTLayout::AMT_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(7.620f, 55.000f)), m, ATTLayout::OFFSET_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 84.000f)), m, ATTLayout::IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 110.000f)), m, ATTLayout::OUT_OUTPUT));
}

// ── MULT (3HP) ────────────────────────────────────────
struct MULTLayout {
    static constexpr int kHp = 3;
    enum ParamId { PARAMS_LEN };
    enum InputId { IN_INPUT, INPUTS_LEN };
    enum OutputId { OUT1_OUTPUT, OUT2_OUTPUT, OUT3_OUTPUT, OUTPUTS_LEN };
    enum LightId { LIGHTS_LEN };
};

inline void config_MULT(rack::engine::Module* m) {
    m->config(MULTLayout::PARAMS_LEN, MULTLayout::INPUTS_LEN, MULTLayout::OUTPUTS_LEN, MULTLayout::LIGHTS_LEN);
    m->configInput(MULTLayout::IN_INPUT, "Signal");
    m->configOutput(MULTLayout::OUT1_OUTPUT, "Copy 1");
    m->configOutput(MULTLayout::OUT2_OUTPUT, "Copy 2");
    m->configOutput(MULTLayout::OUT3_OUTPUT, "Copy 3");
}

inline void place_MULT(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 34.000f)), m, MULTLayout::IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 62.000f)), m, MULTLayout::OUT1_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 84.000f)), m, MULTLayout::OUT2_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(7.620f, 106.000f)), m, MULTLayout::OUT3_OUTPUT));
}

// ── ATTEN (2HP) ───────────────────────────────────────
struct ATTENLayout {
    static constexpr int kHp = 2;
    enum ParamId { ATT_PARAM, PARAMS_LEN };
    enum InputId { IN_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { LVL_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_ATTEN(rack::engine::Module* m) {
    m->config(ATTENLayout::PARAMS_LEN, ATTENLayout::INPUTS_LEN, ATTENLayout::OUTPUTS_LEN, ATTENLayout::LIGHTS_LEN);
    m->configParam(ATTENLayout::ATT_PARAM, 0.0f, 1.0f, 0.5f, "Amount", " %", 0.0f, 100.0f);
    m->configInput(ATTENLayout::IN_INPUT, "Signal in (normalled to 10.0V)");
    m->configOutput(ATTENLayout::OUT_OUTPUT, "Attenuated out");
    m->configLight(ATTENLayout::LVL_LIGHT, "Level");
}

/// Channel count for ATTEN, from the manifest's declared source.
inline int channels_ATTEN(const rack::engine::Module* m) {
    return std::max(1, const_cast<rack::engine::Module*>(m)
        ->inputs[ATTENLayout::IN_INPUT].getChannels());
}

/// IN_INPUT with its declared normal applied.
inline float read_ATTEN_IN_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[ATTENLayout::IN_INPUT].getNormalPolyVoltage(10.0f, c);
}

inline void place_ATTEN(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(5.080f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(5.080f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(5.080f, 30.000f)), m, ATTENLayout::ATT_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(5.080f, 60.000f)), m, ATTENLayout::IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(5.080f, 90.000f)), m, ATTENLayout::OUT_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(5.080f, 108.000f)), m, ATTENLayout::LVL_LIGHT));
}

// ── CARTOG (4HP) ──────────────────────────────────────
struct CARTOGLayout {
    static constexpr int kHp = 4;
    enum ParamId { SCAN_PARAM, PARAMS_LEN };
    enum InputId { INPUTS_LEN };
    enum OutputId { OUTPUTS_LEN };
    enum LightId { DONE_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_CARTOG(rack::engine::Module* m) {
    m->config(CARTOGLayout::PARAMS_LEN, CARTOGLayout::INPUTS_LEN, CARTOGLayout::OUTPUTS_LEN, CARTOGLayout::LIGHTS_LEN);
    m->configParam(CARTOGLayout::SCAN_PARAM, 0.0f, 1.0f, 0.0f, "Scan the rack", "", 0.0f, 1.0f);
    m->configLight(CARTOGLayout::DONE_LIGHT, "Scanned");
}

inline void place_CARTOG(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(12.700f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(12.700f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeButton>(mm2px(Vec(10.160f, 40.000f)), m, CARTOGLayout::SCAN_PARAM));
    w->addChild(createLightCentered<forge_modular::ForgeMediumLight<GreenLight>>(mm2px(Vec(10.160f, 60.000f)), m, CARTOGLayout::DONE_LIGHT));
}

// ── DUALAD (10HP) ──────────────────────────────────────
struct DUALADLayout {
    static constexpr int kHp = 10;
    enum ParamId { A_ATK_PARAM, A_DEC_PARAM, A_CURVE_PARAM, A_LOOP_PARAM, B_ATK_PARAM, B_DEC_PARAM, B_CURVE_PARAM, B_LOOP_PARAM, PARAMS_LEN };
    enum InputId { A_TRIG_INPUT, A_TIME_CV_INPUT, B_TRIG_INPUT, B_TIME_CV_INPUT, INPUTS_LEN };
    enum OutputId { A_EOC_OUTPUT, A_ENV_OUTPUT, B_EOC_OUTPUT, B_ENV_OUTPUT, OUTPUTS_LEN };
    enum LightId { A_LIGHT = 0, B_LIGHT = 1, LIGHTS_LEN = 2 };
};

inline void config_DUALAD(rack::engine::Module* m) {
    m->config(DUALADLayout::PARAMS_LEN, DUALADLayout::INPUTS_LEN, DUALADLayout::OUTPUTS_LEN, DUALADLayout::LIGHTS_LEN);
    m->configParam(DUALADLayout::A_ATK_PARAM, -10.0f, 1.0f, -6.0f, "Channel A attack time", " s", 2.0f, 1.0f);
    m->configParam(DUALADLayout::A_DEC_PARAM, -9.0f, 3.0f, -3.0f, "Channel A decay time", " s", 2.0f, 1.0f);
    m->configParam(DUALADLayout::A_CURVE_PARAM, 0.0f, 1.0f, 0.5f, "Channel A curve", "", 0.0f, 1.0f);
    m->configSwitch(DUALADLayout::A_LOOP_PARAM, 0.0f, 1.0f, 0.0f, "Channel A loop", {"One-shot", "Loop"});
    m->configParam(DUALADLayout::B_ATK_PARAM, -10.0f, 1.0f, -6.0f, "Channel B attack time", " s", 2.0f, 1.0f);
    m->configParam(DUALADLayout::B_DEC_PARAM, -9.0f, 3.0f, -1.0f, "Channel B decay time", " s", 2.0f, 1.0f);
    m->configParam(DUALADLayout::B_CURVE_PARAM, 0.0f, 1.0f, 0.5f, "Channel B curve", "", 0.0f, 1.0f);
    m->configSwitch(DUALADLayout::B_LOOP_PARAM, 0.0f, 1.0f, 0.0f, "Channel B loop", {"One-shot", "Loop"});
    m->configInput(DUALADLayout::A_TRIG_INPUT, "Channel A trigger");
    m->configInput(DUALADLayout::A_TIME_CV_INPUT, "Channel A time CV (1V/oct)");
    m->configInput(DUALADLayout::B_TRIG_INPUT, "Channel B trigger (normalled from A_TRIG_INPUT)");
    m->configInput(DUALADLayout::B_TIME_CV_INPUT, "Channel B time CV (1V/oct) (normalled from A_TIME_CV_INPUT)");
    m->configOutput(DUALADLayout::A_EOC_OUTPUT, "Channel A end of cycle");
    m->configOutput(DUALADLayout::A_ENV_OUTPUT, "Channel A envelope");
    m->configOutput(DUALADLayout::B_EOC_OUTPUT, "Channel B end of cycle");
    m->configOutput(DUALADLayout::B_ENV_OUTPUT, "Channel B envelope");
    m->configLight(DUALADLayout::A_LIGHT, "Channel A level");
    m->configLight(DUALADLayout::B_LIGHT, "Channel B level");
}

/// B_TRIG_INPUT with its declared normal applied.
inline float read_DUALAD_B_TRIG_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[DUALADLayout::B_TRIG_INPUT].isConnected()
        ? m->inputs[DUALADLayout::B_TRIG_INPUT].getPolyVoltage(c)
        : m->inputs[DUALADLayout::A_TRIG_INPUT].getPolyVoltage(c);
}

/// B_TIME_CV_INPUT with its declared normal applied.
inline float read_DUALAD_B_TIME_CV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[DUALADLayout::B_TIME_CV_INPUT].isConnected()
        ? m->inputs[DUALADLayout::B_TIME_CV_INPUT].getPolyVoltage(c)
        : m->inputs[DUALADLayout::A_TIME_CV_INPUT].getPolyVoltage(c);
}

inline void place_DUALAD(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(43.180f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(43.180f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(12.900f, 30.000f)), m, DUALADLayout::A_ATK_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(12.900f, 50.000f)), m, DUALADLayout::A_DEC_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(12.900f, 68.000f)), m, DUALADLayout::A_CURVE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeToggle>(mm2px(Vec(12.900f, 83.000f)), m, DUALADLayout::A_LOOP_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(37.900f, 30.000f)), m, DUALADLayout::B_ATK_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(37.900f, 50.000f)), m, DUALADLayout::B_DEC_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(37.900f, 68.000f)), m, DUALADLayout::B_CURVE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeToggle>(mm2px(Vec(37.900f, 83.000f)), m, DUALADLayout::B_LOOP_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(6.900f, 102.000f)), m, DUALADLayout::A_TRIG_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(18.900f, 102.000f)), m, DUALADLayout::A_TIME_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(31.900f, 102.000f)), m, DUALADLayout::B_TRIG_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(43.900f, 102.000f)), m, DUALADLayout::B_TIME_CV_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(6.900f, 116.000f)), m, DUALADLayout::A_EOC_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(18.900f, 116.000f)), m, DUALADLayout::A_ENV_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(31.900f, 116.000f)), m, DUALADLayout::B_EOC_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(43.900f, 116.000f)), m, DUALADLayout::B_ENV_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(12.900f, 91.000f)), m, DUALADLayout::A_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(37.900f, 91.000f)), m, DUALADLayout::B_LIGHT));
}

// ── DUALATN (6HP) ─────────────────────────────────────
struct DUALATNLayout {
    static constexpr int kHp = 6;
    enum ParamId { A_ATT_PARAM, A_OFF_PARAM, B_ATT_PARAM, B_OFF_PARAM, PARAMS_LEN };
    enum InputId { A_IN_INPUT, B_IN_INPUT, INPUTS_LEN };
    enum OutputId { A_OUT_OUTPUT, B_OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { A_LIGHT = 0, B_LIGHT = 1, LIGHTS_LEN = 2 };
};

inline void config_DUALATN(rack::engine::Module* m) {
    m->config(DUALATNLayout::PARAMS_LEN, DUALATNLayout::INPUTS_LEN, DUALATNLayout::OUTPUTS_LEN, DUALATNLayout::LIGHTS_LEN);
    m->configParam(DUALATNLayout::A_ATT_PARAM, -1.0f, 1.0f, 0.0f, "Channel A attenuversion", "", 0.0f, 1.0f);
    m->configParam(DUALATNLayout::A_OFF_PARAM, -5.0f, 5.0f, 0.0f, "Channel A offset", " V", 0.0f, 1.0f);
    m->configParam(DUALATNLayout::B_ATT_PARAM, -1.0f, 1.0f, 0.0f, "Channel B attenuversion", "", 0.0f, 1.0f);
    m->configParam(DUALATNLayout::B_OFF_PARAM, -5.0f, 5.0f, 0.0f, "Channel B offset", " V", 0.0f, 1.0f);
    m->configInput(DUALATNLayout::A_IN_INPUT, "Channel A input (normalled to 0.0V)");
    m->configInput(DUALATNLayout::B_IN_INPUT, "Channel B input (normalled to 0.0V)");
    m->configOutput(DUALATNLayout::A_OUT_OUTPUT, "Channel A output");
    m->configOutput(DUALATNLayout::B_OUT_OUTPUT, "Channel B output");
    m->configLight(DUALATNLayout::A_LIGHT, "Channel A activity");
    m->configLight(DUALATNLayout::B_LIGHT, "Channel B activity");
}

/// A_IN_INPUT with its declared normal applied.
inline float read_DUALATN_A_IN_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[DUALATNLayout::A_IN_INPUT].getNormalPolyVoltage(0.0f, c);
}

/// B_IN_INPUT with its declared normal applied.
inline float read_DUALATN_B_IN_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[DUALATNLayout::B_IN_INPUT].getNormalPolyVoltage(0.0f, c);
}

inline void place_DUALATN(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(9.000f, 30.000f)), m, DUALATNLayout::A_ATT_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(21.500f, 30.000f)), m, DUALATNLayout::A_OFF_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(9.000f, 74.000f)), m, DUALATNLayout::B_ATT_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(21.500f, 74.000f)), m, DUALATNLayout::B_OFF_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 46.000f)), m, DUALATNLayout::A_IN_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 90.000f)), m, DUALATNLayout::B_IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(21.500f, 46.000f)), m, DUALATNLayout::A_OUT_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(21.500f, 90.000f)), m, DUALATNLayout::B_OUT_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(15.240f, 58.000f)), m, DUALATNLayout::A_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(15.240f, 102.000f)), m, DUALATNLayout::B_LIGHT));
}

// ── FOLD (8HP) ────────────────────────────────────────
struct FOLDLayout {
    static constexpr int kHp = 8;
    enum ParamId { DRIVE_PARAM, SYM_PARAM, DRIVE_CV_PARAM, SYM_CV_PARAM, SHAPE_PARAM, LEVEL_PARAM, PARAMS_LEN };
    enum InputId { DRIVE_CV_INPUT, SYM_CV_INPUT, IN_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { FOLD_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_FOLD(rack::engine::Module* m) {
    m->config(FOLDLayout::PARAMS_LEN, FOLDLayout::INPUTS_LEN, FOLDLayout::OUTPUTS_LEN, FOLDLayout::LIGHTS_LEN);
    m->configParam(FOLDLayout::DRIVE_PARAM, 0.0f, 1.0f, 0.25f, "Drive", " %", 0.0f, 100.0f);
    m->configParam(FOLDLayout::SYM_PARAM, -1.0f, 1.0f, 0.0f, "Symmetry", " %", 0.0f, 100.0f);
    m->configParam(FOLDLayout::DRIVE_CV_PARAM, -1.0f, 1.0f, 0.0f, "Drive CV amount", " %", 0.0f, 100.0f);
    m->configParam(FOLDLayout::SYM_CV_PARAM, -1.0f, 1.0f, 0.0f, "Symmetry CV amount", " %", 0.0f, 100.0f);
    m->configSwitch(FOLDLayout::SHAPE_PARAM, 0.0f, 2.0f, 0.0f, "Fold shape", {"Sine", "Triangle", "Wrap"});
    m->configParam(FOLDLayout::LEVEL_PARAM, 0.0f, 1.0f, 0.8f, "Output level", " %", 0.0f, 100.0f);
    m->configInput(FOLDLayout::DRIVE_CV_INPUT, "Drive CV");
    m->configInput(FOLDLayout::SYM_CV_INPUT, "Symmetry CV (normalled from DRIVE_CV_INPUT)");
    m->configInput(FOLDLayout::IN_INPUT, "Audio in");
    m->configOutput(FOLDLayout::OUT_OUTPUT, "Folded out");
    m->configLight(FOLDLayout::FOLD_LIGHT, "Fold depth");
}

/// Channel count for FOLD, from the manifest's declared source.
inline int channels_FOLD(const rack::engine::Module* m) {
    return std::max(1, const_cast<rack::engine::Module*>(m)
        ->inputs[FOLDLayout::IN_INPUT].getChannels());
}

/// SYM_CV_INPUT with its declared normal applied.
inline float read_FOLD_SYM_CV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[FOLDLayout::SYM_CV_INPUT].isConnected()
        ? m->inputs[FOLDLayout::SYM_CV_INPUT].getPolyVoltage(c)
        : m->inputs[FOLDLayout::DRIVE_CV_INPUT].getPolyVoltage(c);
}

inline void place_FOLD(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(11.800f, 30.000f)), m, FOLDLayout::DRIVE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(28.800f, 30.000f)), m, FOLDLayout::SYM_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(11.800f, 52.000f)), m, FOLDLayout::DRIVE_CV_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(28.800f, 52.000f)), m, FOLDLayout::SYM_CV_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeSwitchThree>(mm2px(Vec(11.800f, 86.000f)), m, FOLDLayout::SHAPE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobSmall>(mm2px(Vec(28.800f, 86.000f)), m, FOLDLayout::LEVEL_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(11.800f, 68.000f)), m, FOLDLayout::DRIVE_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(28.800f, 68.000f)), m, FOLDLayout::SYM_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(11.800f, 104.000f)), m, FOLDLayout::IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(28.800f, 104.000f)), m, FOLDLayout::OUT_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<RedLight>>(mm2px(Vec(20.320f, 104.000f)), m, FOLDLayout::FOLD_LIGHT));
}

// ── FOURPOLE (8HP) ────────────────────────────────────
struct FOURPOLELayout {
    static constexpr int kHp = 8;
    enum ParamId { CUTOFF_PARAM, RES_PARAM, DRIVE_PARAM, FM_PARAM, VOICE_PARAM, PARAMS_LEN };
    enum InputId { VOCT_INPUT, FM_INPUT, IN_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { LVL_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_FOURPOLE(rack::engine::Module* m) {
    m->config(FOURPOLELayout::PARAMS_LEN, FOURPOLELayout::INPUTS_LEN, FOURPOLELayout::OUTPUTS_LEN, FOURPOLELayout::LIGHTS_LEN);
    m->configParam(FOURPOLELayout::CUTOFF_PARAM, 0.0f, 1.0f, 0.5f, "Cutoff", "", 0.0f, 10.0f);
    m->configParam(FOURPOLELayout::RES_PARAM, 0.0f, 1.0f, 0.0f, "Resonance", " %", 0.0f, 100.0f);
    m->configParam(FOURPOLELayout::DRIVE_PARAM, -6.0f, 24.0f, 0.0f, "Input drive", " dB", 0.0f, 1.0f);
    m->configParam(FOURPOLELayout::FM_PARAM, -1.0f, 1.0f, 0.0f, "Cutoff FM amount", " %", 0.0f, 100.0f);
    m->configSwitch(FOURPOLELayout::VOICE_PARAM, 0.0f, 2.0f, 0.0f, "Voicing", {"Juno", "Prophet", "Ladder"});
    m->configInput(FOURPOLELayout::VOCT_INPUT, "Cutoff 1V/oct");
    m->configInput(FOURPOLELayout::FM_INPUT, "Cutoff FM");
    m->configInput(FOURPOLELayout::IN_INPUT, "Audio in");
    m->configOutput(FOURPOLELayout::OUT_OUTPUT, "Low-pass out");
    m->configLight(FOURPOLELayout::LVL_LIGHT, "Output level");
}

/// Channel count for FOURPOLE, from the manifest's declared source.
inline int channels_FOURPOLE(const rack::engine::Module* m) {
    return std::max(1, const_cast<rack::engine::Module*>(m)
        ->inputs[FOURPOLELayout::IN_INPUT].getChannels());
}

inline void place_FOURPOLE(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(33.020f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobLarge>(mm2px(Vec(20.320f, 32.000f)), m, FOURPOLELayout::CUTOFF_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(11.800f, 58.000f)), m, FOURPOLELayout::RES_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(28.800f, 58.000f)), m, FOURPOLELayout::DRIVE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(11.800f, 77.000f)), m, FOURPOLELayout::FM_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeSwitchThree>(mm2px(Vec(28.800f, 77.000f)), m, FOURPOLELayout::VOICE_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(11.800f, 93.000f)), m, FOURPOLELayout::VOCT_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(28.800f, 93.000f)), m, FOURPOLELayout::FM_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(11.800f, 112.000f)), m, FOURPOLELayout::IN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(28.800f, 112.000f)), m, FOURPOLELayout::OUT_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(28.800f, 120.500f)), m, FOURPOLELayout::LVL_LIGHT));
}

// ── KICK (6HP) ────────────────────────────────────────
struct KICKLayout {
    static constexpr int kHp = 6;
    enum ParamId { TUNE_PARAM, DECAY_PARAM, CLICK_PARAM, SWEEP_PARAM, TUNECV_PARAM, PARAMS_LEN };
    enum InputId { TRIG_INPUT, TUNECV_INPUT, ACCENT_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { HIT_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_KICK(rack::engine::Module* m) {
    m->config(KICKLayout::PARAMS_LEN, KICKLayout::INPUTS_LEN, KICKLayout::OUTPUTS_LEN, KICKLayout::LIGHTS_LEN);
    m->configParam(KICKLayout::TUNE_PARAM, 30.0f, 120.0f, 52.0f, "Tune", " Hz", 0.0f, 1.0f);
    m->configParam(KICKLayout::DECAY_PARAM, 30.0f, 1200.0f, 320.0f, "Decay", " ms", 0.0f, 1.0f);
    m->configParam(KICKLayout::CLICK_PARAM, 0.0f, 1.0f, 0.35f, "Click", " %", 0.0f, 100.0f);
    m->configParam(KICKLayout::SWEEP_PARAM, 0.0f, 4.0f, 2.0f, "Pitch sweep", " oct", 0.0f, 1.0f);
    m->configParam(KICKLayout::TUNECV_PARAM, -1.0f, 1.0f, 0.0f, "Tune CV amount", " %", 0.0f, 100.0f);
    m->configInput(KICKLayout::TRIG_INPUT, "Trigger");
    m->configInput(KICKLayout::TUNECV_INPUT, "Tune CV");
    m->configInput(KICKLayout::ACCENT_INPUT, "Accent (normalled to 10.0V)");
    m->configOutput(KICKLayout::OUT_OUTPUT, "Kick out");
    m->configLight(KICKLayout::HIT_LIGHT, "Hit");
}

/// ACCENT_INPUT with its declared normal applied.
inline float read_KICK_ACCENT_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[KICKLayout::ACCENT_INPUT].getNormalPolyVoltage(10.0f, c);
}

inline void place_KICK(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(15.240f, 27.000f)), m, KICKLayout::TUNE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(8.500f, 47.000f)), m, KICKLayout::DECAY_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(22.000f, 47.000f)), m, KICKLayout::CLICK_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(8.500f, 65.000f)), m, KICKLayout::SWEEP_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(22.000f, 65.000f)), m, KICKLayout::TUNECV_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(8.500f, 83.000f)), m, KICKLayout::TRIG_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(22.000f, 83.000f)), m, KICKLayout::TUNECV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(8.500f, 101.000f)), m, KICKLayout::ACCENT_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(22.000f, 101.000f)), m, KICKLayout::OUT_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<RedLight>>(mm2px(Vec(15.240f, 113.000f)), m, KICKLayout::HIT_LIGHT));
}

// ── MORPHLFO (6HP) ────────────────────────────────────
struct MORPHLFOLayout {
    static constexpr int kHp = 6;
    enum ParamId { RATE_PARAM, SHAPE_PARAM, RATE_CV_PARAM, SHAPE_CV_PARAM, PARAMS_LEN };
    enum InputId { RATE_CV_INPUT, SHAPE_CV_INPUT, RST_INPUT, INPUTS_LEN };
    enum OutputId { UNI_OUTPUT, OUT_OUTPUT, OUTPUTS_LEN };
    enum LightId { LFO_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_MORPHLFO(rack::engine::Module* m) {
    m->config(MORPHLFOLayout::PARAMS_LEN, MORPHLFOLayout::INPUTS_LEN, MORPHLFOLayout::OUTPUTS_LEN, MORPHLFOLayout::LIGHTS_LEN);
    m->configParam(MORPHLFOLayout::RATE_PARAM, -4.0f, 4.0f, 1.0f, "Rate", " Hz", 2.0f, 2.0f);
    m->configParam(MORPHLFOLayout::SHAPE_PARAM, 0.0f, 1.0f, 0.5f, "Shape morph", "", 0.0f, 1.0f);
    m->configParam(MORPHLFOLayout::RATE_CV_PARAM, -1.0f, 1.0f, 0.0f, "Rate CV amount", "", 0.0f, 1.0f);
    m->configParam(MORPHLFOLayout::SHAPE_CV_PARAM, -1.0f, 1.0f, 0.0f, "Shape CV amount", "", 0.0f, 1.0f);
    m->configInput(MORPHLFOLayout::RATE_CV_INPUT, "Rate CV (normalled to 5.0V)");
    m->configInput(MORPHLFOLayout::SHAPE_CV_INPUT, "Shape CV (normalled to 5.0V)");
    m->configInput(MORPHLFOLayout::RST_INPUT, "Reset");
    m->configOutput(MORPHLFOLayout::UNI_OUTPUT, "Unipolar out");
    m->configOutput(MORPHLFOLayout::OUT_OUTPUT, "Bipolar out");
    m->configLight(MORPHLFOLayout::LFO_LIGHT, "Level");
}

/// RATE_CV_INPUT with its declared normal applied.
inline float read_MORPHLFO_RATE_CV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[MORPHLFOLayout::RATE_CV_INPUT].getNormalPolyVoltage(5.0f, c);
}

/// SHAPE_CV_INPUT with its declared normal applied.
inline float read_MORPHLFO_SHAPE_CV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[MORPHLFOLayout::SHAPE_CV_INPUT].getNormalPolyVoltage(5.0f, c);
}

inline void place_MORPHLFO(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(22.860f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(15.240f, 30.000f)), m, MORPHLFOLayout::RATE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(15.240f, 50.000f)), m, MORPHLFOLayout::SHAPE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(9.000f, 68.000f)), m, MORPHLFOLayout::RATE_CV_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(21.500f, 68.000f)), m, MORPHLFOLayout::SHAPE_CV_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 84.000f)), m, MORPHLFOLayout::RATE_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(21.500f, 84.000f)), m, MORPHLFOLayout::SHAPE_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 100.000f)), m, MORPHLFOLayout::RST_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(21.500f, 100.000f)), m, MORPHLFOLayout::UNI_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(21.500f, 116.000f)), m, MORPHLFOLayout::OUT_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(9.000f, 116.000f)), m, MORPHLFOLayout::LFO_LIGHT));
}

// ── SANDH (4HP) ───────────────────────────────────────
struct SANDHLayout {
    static constexpr int kHp = 4;
    enum ParamId { SLEW_PARAM, SLEWCV_PARAM, CURVE_PARAM, PARAMS_LEN };
    enum InputId { CLK_INPUT, IN_INPUT, SCV_INPUT, INPUTS_LEN };
    enum OutputId { OUT_OUTPUT, NOISE_OUTPUT, OUTPUTS_LEN };
    enum LightId { HOLD_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_SANDH(rack::engine::Module* m) {
    m->config(SANDHLayout::PARAMS_LEN, SANDHLayout::INPUTS_LEN, SANDHLayout::OUTPUTS_LEN, SANDHLayout::LIGHTS_LEN);
    m->configParam(SANDHLayout::SLEW_PARAM, 0.0f, 1.0f, 0.15f, "Slew", " %", 0.0f, 100.0f);
    m->configParam(SANDHLayout::SLEWCV_PARAM, -1.0f, 1.0f, 0.0f, "Slew CV amount", " %", 0.0f, 100.0f);
    m->configSwitch(SANDHLayout::CURVE_PARAM, 0.0f, 1.0f, 0.0f, "Slew curve", {"Linear", "Expo"});
    m->configInput(SANDHLayout::CLK_INPUT, "Clock");
    m->configInput(SANDHLayout::IN_INPUT, "Signal in (normalled to internal noise)");
    m->configInput(SANDHLayout::SCV_INPUT, "Slew CV");
    m->configOutput(SANDHLayout::OUT_OUTPUT, "Held out");
    m->configOutput(SANDHLayout::NOISE_OUTPUT, "Noise out");
    m->configLight(SANDHLayout::HOLD_LIGHT, "Held level");
}

inline void place_SANDH(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(12.700f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(12.700f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(10.160f, 30.000f)), m, SANDHLayout::SLEW_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(5.600f, 50.000f)), m, SANDHLayout::SLEWCV_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeToggle>(mm2px(Vec(14.720f, 50.000f)), m, SANDHLayout::CURVE_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(5.600f, 70.000f)), m, SANDHLayout::CLK_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(14.720f, 70.000f)), m, SANDHLayout::IN_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(10.160f, 88.000f)), m, SANDHLayout::SCV_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(5.600f, 106.000f)), m, SANDHLayout::OUT_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(14.720f, 106.000f)), m, SANDHLayout::NOISE_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(10.160f, 118.000f)), m, SANDHLayout::HOLD_LIGHT));
}

// ── SIXMIX (12HP) ──────────────────────────────────────
struct SIXMIXLayout {
    static constexpr int kHp = 12;
    enum ParamId { CH1_PARAM, CH2_PARAM, CH3_PARAM, CH4_PARAM, CH5_PARAM, CH6_PARAM, MASTER_PARAM, PARAMS_LEN };
    enum InputId { IN1_INPUT, IN2_INPUT, IN3_INPUT, IN4_INPUT, IN5_INPUT, IN6_INPUT, MCV_INPUT, INPUTS_LEN };
    enum OutputId { MIX_OUTPUT, OUTPUTS_LEN };
    enum LightId { LVL_LIGHT = 0, LIGHTS_LEN = 1 };
};

inline void config_SIXMIX(rack::engine::Module* m) {
    m->config(SIXMIXLayout::PARAMS_LEN, SIXMIXLayout::INPUTS_LEN, SIXMIXLayout::OUTPUTS_LEN, SIXMIXLayout::LIGHTS_LEN);
    m->configParam(SIXMIXLayout::CH1_PARAM, 0.0f, 2.0f, 1.0f, "Channel 1 level", "x", 0.0f, 1.0f);
    m->configParam(SIXMIXLayout::CH2_PARAM, 0.0f, 2.0f, 1.0f, "Channel 2 level", "x", 0.0f, 1.0f);
    m->configParam(SIXMIXLayout::CH3_PARAM, 0.0f, 2.0f, 1.0f, "Channel 3 level", "x", 0.0f, 1.0f);
    m->configParam(SIXMIXLayout::CH4_PARAM, 0.0f, 2.0f, 1.0f, "Channel 4 level", "x", 0.0f, 1.0f);
    m->configParam(SIXMIXLayout::CH5_PARAM, 0.0f, 2.0f, 1.0f, "Channel 5 level", "x", 0.0f, 1.0f);
    m->configParam(SIXMIXLayout::CH6_PARAM, 0.0f, 2.0f, 1.0f, "Channel 6 level", "x", 0.0f, 1.0f);
    m->configParam(SIXMIXLayout::MASTER_PARAM, 0.0f, 2.0f, 1.0f, "Master level", "x", 0.0f, 1.0f);
    m->configInput(SIXMIXLayout::IN1_INPUT, "Channel 1 in");
    m->configInput(SIXMIXLayout::IN2_INPUT, "Channel 2 in");
    m->configInput(SIXMIXLayout::IN3_INPUT, "Channel 3 in");
    m->configInput(SIXMIXLayout::IN4_INPUT, "Channel 4 in");
    m->configInput(SIXMIXLayout::IN5_INPUT, "Channel 5 in");
    m->configInput(SIXMIXLayout::IN6_INPUT, "Channel 6 in");
    m->configInput(SIXMIXLayout::MCV_INPUT, "Master level CV (normalled to 10.0V)");
    m->configOutput(SIXMIXLayout::MIX_OUTPUT, "Mix out");
    m->configLight(SIXMIXLayout::LVL_LIGHT, "Output level");
}

/// MCV_INPUT with its declared normal applied.
inline float read_SIXMIX_MCV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[SIXMIXLayout::MCV_INPUT].getNormalPolyVoltage(10.0f, c);
}

inline void place_SIXMIX(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(22.000f, 32.000f)), m, SIXMIXLayout::CH1_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(51.000f, 32.000f)), m, SIXMIXLayout::CH2_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(22.000f, 50.000f)), m, SIXMIXLayout::CH3_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(51.000f, 50.000f)), m, SIXMIXLayout::CH4_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(22.000f, 68.000f)), m, SIXMIXLayout::CH5_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(51.000f, 68.000f)), m, SIXMIXLayout::CH6_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobLarge>(mm2px(Vec(30.480f, 94.000f)), m, SIXMIXLayout::MASTER_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 32.000f)), m, SIXMIXLayout::IN1_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(38.000f, 32.000f)), m, SIXMIXLayout::IN2_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 50.000f)), m, SIXMIXLayout::IN3_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(38.000f, 50.000f)), m, SIXMIXLayout::IN4_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 68.000f)), m, SIXMIXLayout::IN5_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(38.000f, 68.000f)), m, SIXMIXLayout::IN6_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(9.000f, 110.000f)), m, SIXMIXLayout::MCV_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(51.000f, 110.000f)), m, SIXMIXLayout::MIX_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(30.480f, 110.000f)), m, SIXMIXLayout::LVL_LIGHT));
}

// ── STEPS (12HP) ───────────────────────────────────────
struct STEPSLayout {
    static constexpr int kHp = 12;
    enum ParamId { STEP1_PARAM, STEP2_PARAM, STEP3_PARAM, STEP4_PARAM, STEP5_PARAM, STEP6_PARAM, STEP7_PARAM, STEP8_PARAM, LENGTH_PARAM, GATE_PARAM, DIR_PARAM, PARAMS_LEN };
    enum InputId { CLK_INPUT, RST_INPUT, LEN_INPUT, INPUTS_LEN };
    enum OutputId { CV_OUTPUT, GATE_OUTPUT, EOC_OUTPUT, OUTPUTS_LEN };
    enum LightId { STEP1_LIGHT = 0, STEP2_LIGHT = 1, STEP3_LIGHT = 2, STEP4_LIGHT = 3, STEP5_LIGHT = 4, STEP6_LIGHT = 5, STEP7_LIGHT = 6, STEP8_LIGHT = 7, LIGHTS_LEN = 8 };
};

inline void config_STEPS(rack::engine::Module* m) {
    m->config(STEPSLayout::PARAMS_LEN, STEPSLayout::INPUTS_LEN, STEPSLayout::OUTPUTS_LEN, STEPSLayout::LIGHTS_LEN);
    m->configParam(STEPSLayout::STEP1_PARAM, -5.0f, 5.0f, 0.0f, "Step 1", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::STEP2_PARAM, -5.0f, 5.0f, 0.0f, "Step 2", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::STEP3_PARAM, -5.0f, 5.0f, 0.0f, "Step 3", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::STEP4_PARAM, -5.0f, 5.0f, 0.0f, "Step 4", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::STEP5_PARAM, -5.0f, 5.0f, 0.0f, "Step 5", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::STEP6_PARAM, -5.0f, 5.0f, 0.0f, "Step 6", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::STEP7_PARAM, -5.0f, 5.0f, 0.0f, "Step 7", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::STEP8_PARAM, -5.0f, 5.0f, 0.0f, "Step 8", " V", 0.0f, 1.0f);
    m->configParam(STEPSLayout::LENGTH_PARAM, 1.0f, 8.0f, 8.0f, "Pattern length", " steps", 0.0f, 1.0f);
    m->getParamQuantity(STEPSLayout::LENGTH_PARAM)->snapEnabled = true;
    m->configParam(STEPSLayout::GATE_PARAM, 0.05f, 0.95f, 0.5f, "Gate width", "%", 0.0f, 100.0f);
    m->configSwitch(STEPSLayout::DIR_PARAM, 0.0f, 2.0f, 0.0f, "Direction", {"Forward", "Reverse", "Pendulum"});
    m->configInput(STEPSLayout::CLK_INPUT, "Clock");
    m->configInput(STEPSLayout::RST_INPUT, "Reset");
    m->configInput(STEPSLayout::LEN_INPUT, "Length CV (1V per step) (normalled to 0.0V)");
    m->configOutput(STEPSLayout::CV_OUTPUT, "Step CV");
    m->configOutput(STEPSLayout::GATE_OUTPUT, "Gate");
    m->configOutput(STEPSLayout::EOC_OUTPUT, "End of cycle");
    m->configLight(STEPSLayout::STEP1_LIGHT, "Step 1 active");
    m->configLight(STEPSLayout::STEP2_LIGHT, "Step 2 active");
    m->configLight(STEPSLayout::STEP3_LIGHT, "Step 3 active");
    m->configLight(STEPSLayout::STEP4_LIGHT, "Step 4 active");
    m->configLight(STEPSLayout::STEP5_LIGHT, "Step 5 active");
    m->configLight(STEPSLayout::STEP6_LIGHT, "Step 6 active");
    m->configLight(STEPSLayout::STEP7_LIGHT, "Step 7 active");
    m->configLight(STEPSLayout::STEP8_LIGHT, "Step 8 active");
}

/// LEN_INPUT with its declared normal applied.
inline float read_STEPS_LEN_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[STEPSLayout::LEN_INPUT].getNormalPolyVoltage(0.0f, c);
}

inline void place_STEPS(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(53.340f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(9.600f, 34.000f)), m, STEPSLayout::STEP1_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(23.200f, 34.000f)), m, STEPSLayout::STEP2_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(36.800f, 34.000f)), m, STEPSLayout::STEP3_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(50.400f, 34.000f)), m, STEPSLayout::STEP4_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(9.600f, 56.000f)), m, STEPSLayout::STEP5_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(23.200f, 56.000f)), m, STEPSLayout::STEP6_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(36.800f, 56.000f)), m, STEPSLayout::STEP7_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(50.400f, 56.000f)), m, STEPSLayout::STEP8_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(12.000f, 84.000f)), m, STEPSLayout::LENGTH_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(30.480f, 84.000f)), m, STEPSLayout::GATE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeSwitchThree>(mm2px(Vec(48.500f, 84.000f)), m, STEPSLayout::DIR_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(5.600f, 110.000f)), m, STEPSLayout::CLK_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(15.400f, 110.000f)), m, STEPSLayout::RST_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(25.200f, 110.000f)), m, STEPSLayout::LEN_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(35.000f, 110.000f)), m, STEPSLayout::CV_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(44.800f, 110.000f)), m, STEPSLayout::GATE_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(54.600f, 110.000f)), m, STEPSLayout::EOC_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(9.600f, 42.000f)), m, STEPSLayout::STEP1_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(23.200f, 42.000f)), m, STEPSLayout::STEP2_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(36.800f, 42.000f)), m, STEPSLayout::STEP3_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(50.400f, 42.000f)), m, STEPSLayout::STEP4_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(9.600f, 64.000f)), m, STEPSLayout::STEP5_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(23.200f, 64.000f)), m, STEPSLayout::STEP6_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(36.800f, 64.000f)), m, STEPSLayout::STEP7_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(50.400f, 64.000f)), m, STEPSLayout::STEP8_LIGHT));
}

// ── TANGLE (10HP) ──────────────────────────────────────
struct TANGLELayout {
    static constexpr int kHp = 10;
    enum ParamId { RATE_PARAM, CHAOS_PARAM, SPREAD_PARAM, RATE_CV_PARAM, CHAOS_CV_PARAM, SPREAD_CV_PARAM, SLEW_PARAM, PARAMS_LEN };
    enum InputId { RATE_CV_INPUT, CHAOS_CV_INPUT, SPREAD_CV_INPUT, CLK_INPUT, RST_INPUT, INPUTS_LEN };
    enum OutputId { X_OUTPUT, Y_OUTPUT, Z_OUTPUT, OUTPUTS_LEN };
    enum LightId { X_LIGHT = 0, Y_LIGHT = 1, Z_LIGHT = 2, LIGHTS_LEN = 3 };
};

inline void config_TANGLE(rack::engine::Module* m) {
    m->config(TANGLELayout::PARAMS_LEN, TANGLELayout::INPUTS_LEN, TANGLELayout::OUTPUTS_LEN, TANGLELayout::LIGHTS_LEN);
    m->configParam(TANGLELayout::RATE_PARAM, -4.0f, 4.0f, 1.0f, "Rate", " Hz", 2.0f, 2.0f);
    m->configParam(TANGLELayout::CHAOS_PARAM, 0.0f, 1.0f, 0.85f, "Chaos", "", 0.0f, 1.0f);
    m->configParam(TANGLELayout::SPREAD_PARAM, 0.0f, 1.0f, 0.5f, "Spread", "", 0.0f, 1.0f);
    m->configParam(TANGLELayout::RATE_CV_PARAM, -1.0f, 1.0f, 0.0f, "Rate CV amount", "", 0.0f, 1.0f);
    m->configParam(TANGLELayout::CHAOS_CV_PARAM, -1.0f, 1.0f, 0.0f, "Chaos CV amount", "", 0.0f, 1.0f);
    m->configParam(TANGLELayout::SPREAD_CV_PARAM, -1.0f, 1.0f, 0.0f, "Spread CV amount", "", 0.0f, 1.0f);
    m->configParam(TANGLELayout::SLEW_PARAM, 0.0f, 500.0f, 60.0f, "Glide", " ms", 0.0f, 1.0f);
    m->configInput(TANGLELayout::RATE_CV_INPUT, "Rate CV (normalled to 5.0V)");
    m->configInput(TANGLELayout::CHAOS_CV_INPUT, "Chaos CV (normalled from RATE_CV_INPUT)");
    m->configInput(TANGLELayout::SPREAD_CV_INPUT, "Spread CV (normalled from CHAOS_CV_INPUT)");
    m->configInput(TANGLELayout::CLK_INPUT, "Clock");
    m->configInput(TANGLELayout::RST_INPUT, "Reset");
    m->configOutput(TANGLELayout::X_OUTPUT, "X — stepped chaos");
    m->configOutput(TANGLELayout::Y_OUTPUT, "Y — coupled orbit");
    m->configOutput(TANGLELayout::Z_OUTPUT, "Z — smooth drift");
    m->configLight(TANGLELayout::X_LIGHT, "X level");
    m->configLight(TANGLELayout::Y_LIGHT, "Y level");
    m->configLight(TANGLELayout::Z_LIGHT, "Z level");
}

/// RATE_CV_INPUT with its declared normal applied.
inline float read_TANGLE_RATE_CV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[TANGLELayout::RATE_CV_INPUT].getNormalPolyVoltage(5.0f, c);
}

/// CHAOS_CV_INPUT with its declared normal applied.
inline float read_TANGLE_CHAOS_CV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[TANGLELayout::CHAOS_CV_INPUT].isConnected()
        ? m->inputs[TANGLELayout::CHAOS_CV_INPUT].getPolyVoltage(c)
        : m->inputs[TANGLELayout::RATE_CV_INPUT].getPolyVoltage(c);
}

/// SPREAD_CV_INPUT with its declared normal applied.
inline float read_TANGLE_SPREAD_CV_INPUT(rack::engine::Module* m, int c) {
    return m->inputs[TANGLELayout::SPREAD_CV_INPUT].isConnected()
        ? m->inputs[TANGLELayout::SPREAD_CV_INPUT].getPolyVoltage(c)
        : m->inputs[TANGLELayout::CHAOS_CV_INPUT].getPolyVoltage(c);
}

inline void place_TANGLE(rack::app::ModuleWidget* w, rack::engine::Module* m) {
    using namespace rack;
    using namespace rack::componentlibrary;
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(7.620f, 126.153f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(43.180f, 2.54f))));
    w->addChild(createWidgetCentered<forge_modular::ForgeScrew>(mm2px(Vec(43.180f, 126.153f))));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(10.200f, 30.000f)), m, TANGLELayout::RATE_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(25.400f, 30.000f)), m, TANGLELayout::CHAOS_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(40.600f, 30.000f)), m, TANGLELayout::SPREAD_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(10.200f, 52.000f)), m, TANGLELayout::RATE_CV_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(25.400f, 52.000f)), m, TANGLELayout::CHAOS_CV_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeTrimpot>(mm2px(Vec(40.600f, 52.000f)), m, TANGLELayout::SPREAD_CV_PARAM));
    w->addParam(createParamCentered<forge_modular::ForgeKnobMedium>(mm2px(Vec(25.400f, 72.000f)), m, TANGLELayout::SLEW_PARAM));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(10.200f, 94.000f)), m, TANGLELayout::RATE_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(25.400f, 94.000f)), m, TANGLELayout::CHAOS_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(40.600f, 94.000f)), m, TANGLELayout::SPREAD_CV_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(4.600f, 113.000f)), m, TANGLELayout::CLK_INPUT));
    w->addInput(createInputCentered<forge_modular::ForgePort>(mm2px(Vec(15.000f, 113.000f)), m, TANGLELayout::RST_INPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(25.400f, 113.000f)), m, TANGLELayout::X_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(35.800f, 113.000f)), m, TANGLELayout::Y_OUTPUT));
    w->addOutput(createOutputCentered<forge_modular::ForgePort>(mm2px(Vec(46.200f, 113.000f)), m, TANGLELayout::Z_OUTPUT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(25.400f, 120.500f)), m, TANGLELayout::X_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(35.800f, 120.500f)), m, TANGLELayout::Y_LIGHT));
    w->addChild(createLightCentered<forge_modular::ForgeSmallLight<GreenLight>>(mm2px(Vec(46.200f, 120.500f)), m, TANGLELayout::Z_LIGHT));
}

}  // namespace forge_modular
