"""Compatibility facade for validation runner dependency bindings."""

from __future__ import annotations

from execution_runner_local_bindings import run_local_validation
from execution_runner_ssh_bindings import run_posix_ssh_validation
from execution_runner_windows_bindings import run_windows_ssh_validation, windows_validation_script
