"""Compatibility installer for local_ci queue facade bindings."""

from __future__ import annotations

from typing import Any

from binding_utils import install_local_helpers
from queue_display_bindings import (
    bump_queue_command_result_line,
    cancel_queue_command_result_line,
    drain_runner_active_line,
    empty_log_line,
    enqueue_command_result_line,
    job_logs_header_line,
    log_section_header_line,
    missing_job_logs_line,
    missing_log_files_line,
    recent_completed_missing_result_line,
    recent_completed_status_line,
    result_execution_line,
    result_overall_line,
    result_target_lines,
    result_validation_line,
    status_active_targets,
    status_runner_line,
    status_submission_lines,
    status_target_detail_lines,
    status_target_states,
    summarize_active_targets,
    summarize_job,
    target_result_line,
    target_state_detail_parts,
)
from queue_policy_bindings import (
    cancellation_result,
    default_priority_for,
    find_job_unlocked,
    job_has_narrower_same_identity_scope,
    job_sort_key,
    jobs_share_supersedence_scope,
    make_fingerprint,
    make_job,
    queue_status_groups,
    recent_completed_jobs_for_status,
    supersedence_identity_key,
    supersedence_key,
    supersedence_reason,
    supersedence_result,
    trim_completed_jobs,
    trim_completed_jobs_with_removed_ids,
    validate_ci_branch_name,
)
from queue_runner_bindings import (
    clear_runner_info,
    current_runner_info,
    pid_alive,
    read_runner_info,
    stale_running_jobs_unlocked,
    update_runner_active_targets,
    write_runner_info,
)
from queue_lifecycle_bindings import (
    bump_queue_command_job,
    cancel_job_unlocked,
    cancel_queue_command_job,
    claim_next_job,
    drain_pending_jobs,
    enqueue_job,
    finalize_job,
    load_job,
    load_queue,
    reclaim_stale_remote_validators,
    reconcile_running_jobs_unlocked,
    supersede_job_unlocked,
    update_job_active_targets,
    update_job_target_state,
    wait_for_job,
)
from queue_target_state_bindings import (
    completed_target_state,
    initial_target_state,
    target_state_snapshot,
    updated_target_state,
    upsert_job_active_targets_unlocked,
)


QUEUE_EXPORTS = (
    "supersede_job_unlocked",
    "cancel_job_unlocked",
    "load_queue",
    "update_job_active_targets",
    "enqueue_job",
    "bump_queue_command_job",
    "cancel_queue_command_job",
    "default_priority_for",
    "make_fingerprint",
    "make_job",
    "supersedence_result",
    "cancellation_result",
    "supersedence_key",
    "supersedence_identity_key",
    "jobs_share_supersedence_scope",
    "job_has_narrower_same_identity_scope",
    "supersedence_reason",
    "summarize_job",
    "bump_queue_command_result_line",
    "cancel_queue_command_result_line",
    "enqueue_command_result_line",
    "drain_runner_active_line",
    "summarize_active_targets",
    "status_active_targets",
    "status_target_states",
    "status_submission_lines",
    "target_state_detail_parts",
    "status_target_detail_lines",
    "initial_target_state",
    "completed_target_state",
    "upsert_job_active_targets_unlocked",
    "updated_target_state",
    "target_state_snapshot",
    "status_runner_line",
    "recent_completed_status_line",
    "recent_completed_missing_result_line",
    "result_validation_line",
    "result_execution_line",
    "target_result_line",
    "result_target_lines",
    "result_overall_line",
    "missing_job_logs_line",
    "missing_log_files_line",
    "job_logs_header_line",
    "log_section_header_line",
    "empty_log_line",
    "trim_completed_jobs_with_removed_ids",
    "trim_completed_jobs",
    "job_sort_key",
    "queue_status_groups",
    "recent_completed_jobs_for_status",
    "find_job_unlocked",
    "reconcile_running_jobs_unlocked",
    "read_runner_info",
    "pid_alive",
    "current_runner_info",
    "stale_running_jobs_unlocked",
    "update_job_target_state",
    "reclaim_stale_remote_validators",
    "write_runner_info",
    "update_runner_active_targets",
    "clear_runner_info",
    "validate_ci_branch_name",
    "load_job",
    "claim_next_job",
    "finalize_job",
    "wait_for_job",
    "drain_pending_jobs",
)


def install_queue_helpers(bindings: dict[str, Any], names: tuple[str, ...] = QUEUE_EXPORTS) -> None:
    install_local_helpers(bindings, globals(), names)
