// Dumps every plug-in's live parameter store as markdown.
//
// The control-parity tables are only worth having if they describe the plug-in
// a host actually loads. Grepping `.name = "…"` out of the sources describes the
// plug-in a reader imagines. So this walks the same `StateStore` the format
// adapters walk, after the same `define_parameters()` call, and prints what it
// finds — id, name, unit, range, default, step, and the strings the plug-in
// would show a host for each end of the range.
//
// Regenerate the parity tables from this, never from memory:
//     ./build/examples/bitches-brew/ui/brew-params > /tmp/brew-params.md

#include "cv_osc_processor.hpp"
#include "dc_processor.hpp"
#include "function_processor.hpp"
#include "lfo_processor.hpp"
#include "quantizer_processor.hpp"
#include "step_processor.hpp"
#include "sync_processor.hpp"
#include "trigger_processor.hpp"

#include <pulp/format/headless.hpp>

#include <cstdio>
#include <memory>
#include <string>

using namespace pulp;
using namespace pulp::examples::brew;

namespace {

std::string trim_number(float v) {
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%.6g", v);
    return std::string(buf);
}

/// What a host would show for this value. Empty when the plug-in declares no
/// formatter, which is itself worth seeing in the table.
std::string shown(const state::ParamInfo& p, float v) {
    return p.to_string ? p.to_string(v) : std::string();
}

void dump(format::ProcessorFactory f, const char* title) {
    format::HeadlessHost host(f);
    host.prepare(48000.0, 512, 2, 2);
    const auto desc = host.processor()->descriptor();
    const auto [w, h] = host.processor()->editor_size();

    std::printf("\n## %s\n\n", title);
    std::printf("- name: `%s`  bundle: `%s`\n", desc.name.c_str(), desc.bundle_id.c_str());
    std::printf("- editor: %d x %d\n", w, h);
    std::printf("- accepts MIDI: %s   produces MIDI: %s\n",
                desc.accepts_midi ? "yes" : "no",
                desc.produces_midi ? "yes" : "no");
    for (const auto& b : desc.input_buses)
        std::printf("- in bus: `%s` x%d\n", b.name.c_str(), b.default_channels);
    for (const auto& b : desc.output_buses)
        std::printf("- out bus: `%s` x%d\n", b.name.c_str(), b.default_channels);

    const auto params = host.state().all_params();
    std::printf("\n%zu parameters\n\n", params.size());
    std::printf("| id | name | unit | min | max | default | step | shows min | shows max |\n");
    std::printf("|---|---|---|---|---|---|---|---|---|\n");
    for (const auto& p : params) {
        std::printf("| %u | %s | %s | %s | %s | %s | %s | %s | %s |\n",
                    static_cast<unsigned>(p.id), p.name.c_str(), p.unit.c_str(),
                    trim_number(p.range.min).c_str(),
                    trim_number(p.range.max).c_str(),
                    trim_number(p.range.default_value).c_str(),
                    trim_number(p.range.step).c_str(),
                    shown(p, p.range.min).c_str(),
                    shown(p, p.range.max).c_str());
    }
}

template <typename T>
std::unique_ptr<format::Processor> make() {
    return std::make_unique<T>();
}

}  // namespace

int main() {
    std::printf("# Bitches Brew — live parameter dump\n");
    std::printf("\nGenerated by `brew-params` from each plug-in's own "
                "`define_parameters()`.\n");
    dump(make<DcProcessor>, "DC");
    dump(make<SyncProcessor>, "Sync");
    dump(make<LfoProcessor>, "LFO");
    dump(make<FunctionProcessor>, "Function");
    dump(make<QuantizerProcessor>, "Quantizer");
    dump(make<StepProcessor>, "Step LFO");
    dump(make<CvOscProcessor>, "CV To OSC");
    dump(make<TriggerProcessor>, "Trigger");
    return 0;
}
