#include "cv_osc_processor.hpp"
#include "dc_processor.hpp"
#include "function_processor.hpp"
#include "lfo_processor.hpp"
#include "quantizer_processor.hpp"
#include "step_processor.hpp"
#include "sync_processor.hpp"
#include "trigger_processor.hpp"
#include <pulp/format/headless.hpp>
#include <pulp/view/screenshot.hpp>
#include <cstdio>
#include <filesystem>
#include <string>
using namespace pulp;
using namespace pulp::examples::brew;

/// Run one block so the editors that display real DSP state (Sync's lamps, LFO's
/// phase marker, Function's operating point) have something to show. `input` seeds
/// the input bus for the plug-ins that read it, and `midi` the note-driven ones.
static void run_block(format::HeadlessHost& h,
                      const format::ProcessContext& base,
                      float input = 0.0f,
                      midi::MidiBuffer* midi = nullptr) {
    constexpr std::size_t kFrames = 512;
    audio::Buffer<float> in(2, kFrames), out(2, kFrames);
    in.clear();
    out.clear();
    for (std::size_t c = 0; c < 2; ++c)
        for (std::size_t n = 0; n < kFrames; ++n) in.channel(c)[n] = input;
    const float* ip[2] = {in.channel(0).data(), in.channel(1).data()};
    audio::BufferView<const float> iv(ip, 2, kFrames);
    auto ov = out.view();
    format::ProcessContext c = base;
    c.sample_rate = 48000;
    c.num_samples = kFrames;
    midi::MidiBuffer in_midi, out_midi;
    if (midi) in_midi = *midi;
    h.processor()->process(ov, iv, in_midi, out_midi, c);
}

static format::ProcessContext playing(double beats) {
    format::ProcessContext c;
    c.is_playing = true;
    c.tempo_bpm = 120;
    c.position_beats = beats;
    return c;
}

/// Where the PNGs land. Defaults to a scratch directory; the docs images are
/// regenerated by pointing this at `docs/images`, so a screenshot in the README
/// is never hand-placed and can never drift from the editor it claims to show.
static std::string g_out_dir = "/tmp/brewshots";
static bool g_ok = true;

static void shoot(format::ProcessorFactory f, const char* name,
                  void (*setup)(format::HeadlessHost&)) {
    const std::string path = g_out_dir + "/" + name;
    format::HeadlessHost host(f);
    host.prepare(48000.0, 512, 2, 2);
    if (setup) setup(host);
    // Render at the size the plug-in tells a host to open it at, so a
    // screenshot cannot flatter a layout that a DAW would never show.
    const auto [w, h] = host.processor()->editor_size();
    auto v = host.processor()->create_view();
    v->set_bounds({0, 0, static_cast<float>(w), static_cast<float>(h)});
    const bool ok = view::render_to_file(*v, w, h, path, 2.0f);
    if (!ok) g_ok = false;
    std::printf("%s %s\n", ok ? "OK  " : "FAIL", path.c_str());
}

int main(int argc, char** argv) {
    if (argc > 1) g_out_dir = argv[1];
    std::error_code ec;
    std::filesystem::create_directories(g_out_dir, ec);
    // The rail reads the emitted sample, so DC needs a block run before its
    // editor has anything to show.
    shoot(create_dc, "dc.png", [](format::HeadlessHost& h) {
        h.state().set_value(DcProcessor::kValue, 0.42f);
        h.state().set_value(DcProcessor::kUnipolar, 0.2f);
        run_block(h, playing(0.0));
    });
    shoot(create_dc, "dc-negative.png", [](format::HeadlessHost& h) {
        h.state().set_value(DcProcessor::kValue, -0.45f);
        run_block(h, playing(0.0));
    });
    shoot(create_lfo, "lfo.png", [](format::HeadlessHost& h) {
        // A mix, not a shape: mostly sine with a triangle folded in and a little
        // asymmetry, which is the thing a selector could never do.
        h.state().set_value(LfoProcessor::kTriangle, 0.35f);
        h.state().set_value(LfoProcessor::kAsymmetry, 0.35f);
        run_block(h, playing(0.3));
    });
    shoot(create_function, "function.png",
          [](format::HeadlessHost& h) {
              h.state().set_value(FunctionProcessor::kCurve,
                                  static_cast<float>(Curve::exponential));
              h.state().set_value(FunctionProcessor::kAmount, 3.0f);
              run_block(h, playing(0.0), 0.7f);
          });
    shoot(create_quantizer, "quantizer.png",
          [](format::HeadlessHost& h) {
              // Few enough steps that the treads are legible, offset off the
              // lattice, and an input parked between two of them.
              h.state().set_value(QuantizerProcessor::kSteps, 6.0f);
              h.state().set_value(QuantizerProcessor::kOffset, 0.3f);
              run_block(h, playing(0.0), 0.42f);
          });
    shoot(create_step, "step.png", [](format::HeadlessHost& h) {
        const float shape[8] = {-0.2f, 0.55f, -0.75f, 0.35f,
                                0.9f,  -0.4f, 0.15f,  -0.9f};
        for (int i = 0; i < 8; ++i)
            h.state().set_value(StepProcessor::step_param(i), shape[i]);
        h.state().set_value(StepProcessor::kLength, 6.0f);
        h.state().set_value(StepProcessor::kSpeedMode, 1.0f);
        h.state().set_value(StepProcessor::kBeats, 1.0f);
        h.state().set_value(StepProcessor::kSyncMode,
                            static_cast<float>(static_cast<int>(SyncMode::transport2)));
        run_block(h, playing(2.3));  // lights step 2
    });
    // A note is down, so the rail shows the gate high on the left and the envelope
    // resting on its sustain on the right. A Trigger editor with nothing playing is
    // a picture of two flat lines.
    shoot(create_trigger, "trigger.png", [](format::HeadlessHost& h) {
        h.state().set_value(
            static_cast<state::ParamID>(param_for(TriggerProcessor::kAnyNote, 0)), 1.0f);
        h.state().set_value(
            static_cast<state::ParamID>(param_for(TriggerProcessor::kAnyNote, 1)), 1.0f);
        h.state().set_value(
            static_cast<state::ParamID>(param_for(TriggerProcessor::kMode, 1)),
            static_cast<float>(static_cast<int>(TriggerSignal::envelope)));
        h.state().set_value(
            static_cast<state::ParamID>(param_for(TriggerProcessor::kCurveA2, 1)), 0.5f);
        h.state().set_value(
            static_cast<state::ParamID>(param_for(TriggerProcessor::kCurveA3, 1)), -0.4f);
        midi::MidiBuffer notes;
        notes.add(midi::MidiEvent::note_on(0, 60, 100));
        run_block(h, playing(0.0), 0.0f, &notes);
        for (int i = 0; i < 8; ++i) run_block(h, playing(0.0));   // reach the sustain
    });
    shoot(create_cv_osc, "cv-osc.png", [](format::HeadlessHost& h) {
        // Both channels stay off in the shot: the lamps are dark, which is what a
        // fresh instance looks like, and no packet leaves a screenshot run.
        run_block(h, playing(0.0), -0.35f);
    });
    shoot(create_sync, "sync-stopped.png", nullptr);
    shoot(create_sync, "sync-running.png",
          [](format::HeadlessHost& h) {
              auto c = playing(0.0);
              c.transport_started = true;
              run_block(h, c);
          });

    // A missing raster backend must not quietly produce an empty docs directory.
    return g_ok ? 0 : 1;
}
