#!/usr/bin/env python3
"""Lower experiment DesignIR to the same Pulp widget-bridge/Skia render lane."""

import argparse
import json
from pathlib import Path


def q(value):
    return json.dumps(value)


def emit_node(node, parent, lines):
    node_id, kind = node["stable_anchor_id"], node["type"]
    style, layout = node.get("style", {}), node.get("layout", {})
    widget = node.get("audioWidget")
    if widget:
        lines.append(f"create{widget.capitalize()}({q(node_id)}, {q(parent)});")
        lines.append(f"setLabel({q(node_id)}, {q(node.get('label', ' '))});")
    elif kind == "text":
        lines.append(f"createLabel({q(node_id)}, {q(node.get('content', ''))}, {q(parent)});")
    else:
        make = "createRow" if layout.get("direction") == "row" else "createCol"
        lines.append(f"{make}({q(node_id)}, {q(parent)});")
    flex = {
        "width": "width", "height": "height", "gap": "gap",
        "paddingTop": "padding_top", "paddingRight": "padding_right",
        "paddingBottom": "padding_bottom", "paddingLeft": "padding_left",
        "flexGrow": "flex_grow", "justify": "justify_content", "align": "align_items",
    }
    for source, target in flex.items():
        value = style.get(source) if source in ("width", "height") else layout.get(source)
        if value is not None:
            lines.append(f"setFlex({q(node_id)}, {q(target)}, {q(value) if isinstance(value, str) else value});")
    if style.get("backgroundColor"):
        lines.append(f"setBackground({q(node_id)}, {q(style['backgroundColor'])});")
    if style.get("backgroundGradient"):
        lines.append(f"setBackgroundGradient({q(node_id)}, {q(style['backgroundGradient'])});")
    if style.get("borderRadius") is not None:
        lines.append(f"setCornerRadius({q(node_id)}, {style['borderRadius']});")
    if style.get("borderWidth") is not None:
        lines.append(f"setBorder({q(node_id)}, {style['borderWidth']}, {q(style.get('borderColor', '#00000000'))});")
    if style.get("boxShadow"):
        # Translator emits exactly: 0px Ypx BLURpx COLOR.
        parts = style["boxShadow"].split()
        if len(parts) == 4:
            lines.append(f"setBoxShadow({q(node_id)}, 0, {parts[1][:-2]}, {parts[2][:-2]}, 0, {q(parts[3])});")
    if kind == "text":
        for field, fn in (("color", "setTextColor"), ("fontFamily", "setFontFamily"),
                          ("fontSize", "setFontSize"), ("fontWeight", "setFontWeight"),
                          ("letterSpacing", "setLetterSpacing")):
            if field in style:
                lines.append(f"{fn}({q(node_id)}, {q(style[field]) if isinstance(style[field], str) else style[field]});")
    lines.append(f"setAnchor({q(node_id)}, {q(node_id)});")
    for child in node.get("children", []):
        emit_node(child, node_id, lines)


def lower(ir):
    lines = ["// Generated by Project C profile translator; Pulp bridge render lane",
             "setTheme('dark');", "if (typeof setSubpixelLayout === 'function') setSubpixelLayout('', true);"]
    for key, value in ir.get("tokens", {}).get("colors", {}).items():
        lines.append(f"setColorToken({q(key)}, {q(value)});")
    root = ir["root"]
    # Screenshot host already owns root; lower the emitted root as its child.
    emit_node(root, "", lines)
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("design_ir", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    args.output.write_text(lower(json.loads(args.design_ir.read_text())))


if __name__ == "__main__":
    main()
