// Generated by tools/bridge/bridge_gen.py; do not edit.
#pragma once

#include <array>
#include <string>
#include <string_view>

namespace pulp::view::editor_bridge_contract {

inline constexpr int kVersion = 1;
inline constexpr std::string_view kName = "editor";

enum class Direction { Command, Publication };
struct HandlerSpec {
    std::string_view name;
    Direction direction;
    std::string_view payload_type;
    std::string_view response_type;
};

struct BeginGestureRequest {
    std::string key;
};

struct BeginGestureResponse {
    // empty payload
};

struct EndGestureRequest {
    std::string key;
};

struct EndGestureResponse {
    // empty payload
};

struct SetParameterRequest {
    std::string key;
    double value;
};

struct SetParameterResponse {
    bool accepted;
};

struct ParameterChangedFrame {
    std::string key;
    double value;
};

inline constexpr std::array<HandlerSpec, 4> kHandlers{{
    {"begin_gesture", Direction::Command, "BeginGestureRequest", "BeginGestureResponse"},
    {"end_gesture", Direction::Command, "EndGestureRequest", "EndGestureResponse"},
    {"parameter_changed", Direction::Publication, "ParameterChangedFrame", ""},
    {"set_parameter", Direction::Command, "SetParameterRequest", "SetParameterResponse"},
}};

// Canonical wrapped initializer keeps generated diffs readable.
inline constexpr std::array<std::string_view, 3> kCommandNames{
    {"begin_gesture", "end_gesture", "set_parameter"}};
inline constexpr std::array<std::string_view, 1> kPublicationNames{{"parameter_changed"}};

} // namespace pulp::view::editor_bridge_contract
