// Generated by tools/bridge/bridge_gen.py; do not edit.

export interface BeginGestureRequest {
  key: string
}

export interface BeginGestureResponse {
  // empty payload
}

export interface EndGestureRequest {
  key: string
}

export interface EndGestureResponse {
  // empty payload
}

export interface SetParameterRequest {
  key: string
  value: number
}

export interface SetParameterResponse {
  accepted: boolean
}

export interface ParameterChangedFrame {
  key: string
  value: number
}

export type EditorBridgeCommand = "begin_gesture" | "end_gesture" | "set_parameter";

export type EditorBridgePublication = "parameter_changed";

export type EditorBridgeRequest = { type: "begin_gesture"; payload: BeginGestureRequest } | { type: "end_gesture"; payload: EndGestureRequest } | { type: "set_parameter"; payload: SetParameterRequest };

export type EditorBridgeResponse<T extends object> = { ok: boolean } & Partial<T>;

export type EditorBridgeResult<T extends object> = EditorBridgeResponse<T> | Promise<EditorBridgeResponse<T>>;

export type EditorBridgeTransport = (request: EditorBridgeRequest) => unknown | Promise<unknown>;

export type EditorBridgeJsonTransport = (requestJson: string) => string | Promise<string>;

export function jsonTransport(transport: EditorBridgeJsonTransport): EditorBridgeTransport {
  return request => {
    const response = transport(JSON.stringify(request));
    if (response instanceof Promise)
      return response.then(value => JSON.parse(value) as unknown);
    return JSON.parse(response) as unknown;
  };
}

export function beginGesture(transport: EditorBridgeTransport, key: string): EditorBridgeResult<BeginGestureResponse> {
  return transport({ type: "begin_gesture", payload: { key: key } }) as EditorBridgeResult<BeginGestureResponse>;
}

export function endGesture(transport: EditorBridgeTransport, key: string): EditorBridgeResult<EndGestureResponse> {
  return transport({ type: "end_gesture", payload: { key: key } }) as EditorBridgeResult<EndGestureResponse>;
}

export function setParameter(transport: EditorBridgeTransport, key: string, value: number): EditorBridgeResult<SetParameterResponse> {
  return transport({ type: "set_parameter", payload: { key: key, value: value } }) as EditorBridgeResult<SetParameterResponse>;
}
