// Generated by tools/bridge/bridge_gen.py; do not edit.
#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <initializer_list>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <string_view>
#include <utility>

#include <choc/containers/choc_Value.h>
#include <pulp/runtime/alive_token.hpp>
#include <pulp/state/store.hpp>
#include <pulp/view/editor_bridge.hpp>

namespace pulp::view::editor_bridge_contract {

inline constexpr int kVersion = 1;
inline constexpr std::string_view kName = "editor";

enum class Direction { Command, Publication };
struct HandlerSpec {
    std::string_view name;
    Direction direction;
    std::string_view payload_type;
    std::string_view response_type;
};

struct BeginGestureRequest {
    std::string key;
};

struct BeginGestureResponse {
    // empty payload
};

struct EndGestureRequest {
    std::string key;
};

struct EndGestureResponse {
    // empty payload
};

struct SetParameterRequest {
    std::string key;
    double value;
};

struct SetParameterResponse {
    bool accepted;
};

struct ParameterChangedFrame {
    std::string key;
    double value;
};

inline constexpr std::array<HandlerSpec, 4> kHandlers{{
    {"begin_gesture", Direction::Command, "BeginGestureRequest", "BeginGestureResponse"},
    {"end_gesture", Direction::Command, "EndGestureRequest", "EndGestureResponse"},
    {"parameter_changed", Direction::Publication, "ParameterChangedFrame", ""},
    {"set_parameter", Direction::Command, "SetParameterRequest", "SetParameterResponse"},
}};

// Canonical wrapped initializer keeps generated diffs readable.
inline constexpr std::array<std::string_view, 3> kCommandNames{
    {"begin_gesture", "end_gesture", "set_parameter"}};
inline constexpr std::array<std::string_view, 1> kPublicationNames{{"parameter_changed"}};

// The canonical parameter command has a real typed production seam. The
// callback owns parameter identity (for example, a StateStore name→ParamID
// lookup); this generated layer owns envelope validation and response shape.
using SetParameterHandler = std::function<bool(const SetParameterRequest&)>;

inline bool decode_set_parameter_request(const choc::value::ValueView& payload,
                                         SetParameterRequest& request, std::string& error) {
    try {
        if (!payload.isObject()) {
            error = "set_parameter payload must be an object";
            return false;
        }
        if (!payload.hasObjectMember("key") || !payload["key"].isString()) {
            error = "set_parameter payload missing 'key' string";
            return false;
        }
        request.key = std::string(payload["key"].getString());
        if (request.key.empty()) {
            error = "set_parameter payload 'key' must not be empty";
            return false;
        }
        if (!payload.hasObjectMember("value")) {
            error = "set_parameter payload missing 'value' number";
            return false;
        }
        const auto value = payload["value"];
        if (value.isFloat64())
            request.value = value.getFloat64();
        else if (value.isFloat32())
            request.value = static_cast<double>(value.getFloat32());
        else if (value.isInt64())
            request.value = static_cast<double>(value.getInt64());
        else if (value.isInt32())
            request.value = static_cast<double>(value.getInt32());
        else {
            error = "set_parameter payload 'value' must be a number";
            return false;
        }
        if (!std::isfinite(request.value)) {
            error = "set_parameter payload 'value' must be finite";
            return false;
        }
        return true;
    } catch (...) {
        error = "set_parameter payload is invalid";
        return false;
    }
}

inline std::string set_parameter_response(bool accepted) noexcept {
    try {
        auto extras = choc::value::createObject("");
        extras.addMember("accepted", accepted);
        return EditorBridge::ok_response(extras);
    } catch (...) {
        return accepted ? std::string{R"({"ok":true,"accepted":true})"}
                        : std::string{R"({"ok":true,"accepted":false})"};
    }
}

inline void register_set_parameter(EditorBridge& bridge, SetParameterHandler handler) {
    bridge.add_handler("set_parameter",
                       [handler = std::move(handler)](const choc::value::ValueView& payload) {
                           SetParameterRequest request;
                           std::string error;
                           if (!decode_set_parameter_request(payload, request, error))
                               return EditorBridge::err_response(error);
                           return set_parameter_response(handler(request));
                       });
}

// A stable key map is the explicit identity boundary for imported controls.
// The generated bridge never guesses a ParamID from a display name. Callers
// provide the immutable one-to-one wire key→ParamID table once during plugin
// setup; the helper validates every target before registering any handler, then routes
// set through StateStore. Gesture commands stay explicit contract declarations
// until a host-owned lifecycle adapter is supplied.
struct StateStoreParameterBinding {
    std::string key;
    state::ParamID id = 0;
};

inline bool register_state_store_set_parameter_handler(
    EditorBridge& bridge, state::StateStore& store, runtime::AliveToken::Handle owner_alive,
    std::initializer_list<StateStoreParameterBinding> bindings) {
    if (!runtime::AliveToken::is_alive(owner_alive))
        return false;
    auto key_to_id = std::make_shared<std::map<std::string, state::ParamID>>();
    std::set<state::ParamID> ids;
    for (const auto& binding : bindings) {
        if (binding.key.empty())
            return false;
        if (store.info(binding.id) == nullptr)
            return false;
        if (!ids.emplace(binding.id).second)
            return false;
        if (!key_to_id->emplace(binding.key, binding.id).second)
            return false;
    }
    if (key_to_id->empty())
        return false;

    register_set_parameter(bridge,
                           [&store, owner_alive, key_to_id](const SetParameterRequest& request) {
                               if (!runtime::AliveToken::is_alive(owner_alive))
                                   return false;
                               const auto found = key_to_id->find(request.key);
                               if (found == key_to_id->end())
                                   return false;
                               const auto value = static_cast<float>(request.value);
                               // The wire contract carries a double, while StateStore stores
                               // float. A finite double can still overflow during narrowing;
                               // reject it instead of letting StateStore sanitize it to the
                               // parameter default while reporting accepted=true.
                               if (!std::isfinite(value))
                                   return false;
                               store.set_value(found->second, value);
                               return true;
                           });
    return true;
}
} // namespace pulp::view::editor_bridge_contract
