#pragma once

// Convenience header — includes all pulp-signal DSP utilities
#include <pulp/signal/smoothed_value.hpp>
#include <pulp/signal/adsr.hpp>
#include <pulp/signal/bias.hpp>
#include <pulp/signal/biquad.hpp>
#include <pulp/signal/sos_cascade.hpp>
#include <pulp/signal/oscillator.hpp>
#include <pulp/signal/delay_line.hpp>
#include <pulp/signal/cross_feedback_multitap_delay.hpp>
#include <pulp/signal/fractional_delay.hpp>
#include <pulp/signal/dry_wet_mixer.hpp>
#include <pulp/signal/gain.hpp>
#include <pulp/signal/compressor.hpp>
#include <pulp/signal/de_esser.hpp>
#include <pulp/signal/expander.hpp>
#include <pulp/signal/svf.hpp>
#include <pulp/signal/waveshaper.hpp>
#include <pulp/signal/oversampling.hpp>
#include <pulp/signal/noise_gate.hpp>
#include <pulp/signal/panner.hpp>
#include <pulp/signal/chorus.hpp>
#include <pulp/signal/phaser.hpp>
#include <pulp/signal/reverb.hpp>
#include <pulp/signal/ladder_filter.hpp>
#include <pulp/signal/analog_vcf.hpp>
#include <pulp/signal/linkwitz_riley.hpp>
#include <pulp/signal/windowing.hpp>
#include <pulp/signal/fft.hpp>
#include <pulp/signal/fir_filter.hpp>
#include <pulp/signal/halfband_iir.hpp>
#include <pulp/signal/ballistics_filter.hpp>
#include <pulp/signal/log_ramped_value.hpp>
#include <pulp/signal/matrix.hpp>
#include <pulp/signal/audio_matrix_mixer.hpp>
#include <pulp/signal/mid_side.hpp>
#include <pulp/signal/mirrored_history_buffer.hpp>
#include <pulp/signal/modal_bank.hpp>
#include <pulp/signal/nway_crossfade.hpp>
#include <pulp/signal/path_latency_aligner.hpp>
#include <pulp/signal/path_switcher.hpp>
#include <pulp/signal/square_osc_bank.hpp>
#include <pulp/signal/processor_chain.hpp>
#include <pulp/signal/processor_duplicator.hpp>
#include <pulp/signal/lookup_table.hpp>
#include <pulp/signal/simd_buffer.hpp>
#include <pulp/signal/soft_bypass.hpp>
#include <pulp/signal/transition_mixer.hpp>
#include <pulp/signal/tpt_filter.hpp>
#include <pulp/signal/interpolator.hpp>
#include <pulp/signal/filter_design.hpp>
#include <pulp/signal/fast_math.hpp>
#include <pulp/signal/poly_math.hpp>
#include <pulp/signal/stft.hpp>
#include <pulp/signal/spectral_frame_engine.hpp>
#include <pulp/signal/spectral_gate_blur.hpp>
#include <pulp/signal/spectral_morph.hpp>
#include <pulp/signal/spectral_band_mask.hpp>
#include <pulp/signal/multichannel_phase_coordinator.hpp>
#include <pulp/signal/source_filter_analysis.hpp>
#include <pulp/signal/spectral_envelope_shifter.hpp>
#include <pulp/signal/realtime_pitch_time_processor.hpp>
#include <pulp/signal/offline_stretch.hpp>
#include <pulp/signal/latency_aware_control_smoother.hpp>
#include <pulp/signal/transient_phase_policy.hpp>
#include <pulp/signal/freeze_hold.hpp>
#include <pulp/signal/pitched_feedback_delay.hpp>
#include <pulp/signal/resampler.hpp>
#include <pulp/signal/sinc_resampler.hpp>
#include <pulp/signal/spectrogram.hpp>
#include <pulp/signal/multi_channel_meter.hpp>
#include <pulp/signal/convolver.hpp>

// Modulation and utility toolkit — deterministic randomness, LFO, control-signal
// tools, the trigger/gate event kit, the envelope family, VCA, low-pass gate,
// mod matrix, unit conversions, and a chaos source.
#include <pulp/signal/rng.hpp>
#include <pulp/signal/units.hpp>
#include <pulp/signal/mod_tools.hpp>
#include <pulp/signal/lfo.hpp>
#include <pulp/signal/trigger.hpp>
#include <pulp/signal/envelope.hpp>
#include <pulp/signal/vca.hpp>
#include <pulp/signal/lpg.hpp>
#include <pulp/signal/mod_matrix.hpp>
#include <pulp/signal/chaos.hpp>
